CREATE TABLE message_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,template_key text NOT NULL,name text NOT NULL,body text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,template_key));
CREATE TABLE automation_lifecycle_settings(tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,confirmation_enabled boolean NOT NULL DEFAULT true,reminder_minutes integer[] NOT NULL DEFAULT ARRAY[1440,120],thank_you_delay_minutes integer NOT NULL DEFAULT 60,review_delay_minutes integer NOT NULL DEFAULT 1440,birthday_enabled boolean NOT NULL DEFAULT true,winback_days integer NOT NULL DEFAULT 30,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE customer_automation_profiles(tenant_id uuid NOT NULL,customer_id uuid NOT NULL,birthday date,automation_opt_out boolean NOT NULL DEFAULT false,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,customer_id),FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id) ON DELETE CASCADE);
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'BOOKING_CONFIRMATION','Booking confirmation','Hi {{customer_name}}, booking {{service_name}} anda disahkan pada {{booking_time}}.' FROM tenants ON CONFLICT DO NOTHING;
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'BOOKING_REMINDER','Booking reminder','Reminder: {{service_name}} anda pada {{booking_time}}.' FROM tenants ON CONFLICT DO NOTHING;
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'THANK_YOU','Thank you','Terima kasih {{customer_name}} kerana datang hari ini.' FROM tenants ON CONFLICT DO NOTHING;
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'REVIEW_REQUEST','Review request','Hi {{customer_name}}, bagaimana pengalaman anda? Balas mesej ini untuk berkongsi maklum balas.' FROM tenants ON CONFLICT DO NOTHING;
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'BIRTHDAY','Birthday','Selamat hari lahir {{customer_name}}! Semoga hari anda indah.' FROM tenants ON CONFLICT DO NOTHING;
INSERT INTO message_templates(tenant_id,template_key,name,body) SELECT id,'WINBACK','Win-back','Hi {{customer_name}}, sudah lama tidak berjumpa. Mahu tempah slot baru?' FROM tenants ON CONFLICT DO NOTHING;
