DO $$ BEGIN CREATE TYPE wsb_campaign_status AS ENUM ('DRAFT','READY','SENDING','SENT','CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE wsb_campaign_recipient_status AS ENUM ('PLANNED','QUEUED','SKIPPED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE wsb_survey_status AS ENUM ('OPEN','COMPLETED','EXPIRED','REVOKED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE marketing_campaigns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name text NOT NULL,body text NOT NULL,segment jsonb NOT NULL DEFAULT '{}'::jsonb,status wsb_campaign_status NOT NULL DEFAULT 'DRAFT',scheduled_at timestamptz,created_by_user_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id));
CREATE INDEX marketing_campaigns_tenant_status_idx ON marketing_campaigns(tenant_id,status,created_at DESC);
CREATE TABLE marketing_campaign_recipients(tenant_id uuid NOT NULL,campaign_id uuid NOT NULL,customer_id uuid NOT NULL,status wsb_campaign_recipient_status NOT NULL DEFAULT 'PLANNED',automation_job_id uuid,reason text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,campaign_id,customer_id),FOREIGN KEY(tenant_id,campaign_id) REFERENCES marketing_campaigns(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(automation_job_id) REFERENCES automation_jobs(id) ON DELETE SET NULL);
CREATE TABLE customer_surveys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,booking_id uuid,customer_id uuid NOT NULL,token_hash char(64) NOT NULL UNIQUE,status wsb_survey_status NOT NULL DEFAULT 'OPEN',questions jsonb NOT NULL DEFAULT '[]'::jsonb,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,booking_id) REFERENCES bookings(tenant_id,id) ON DELETE SET NULL,FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id) ON DELETE CASCADE);
CREATE INDEX customer_surveys_customer_idx ON customer_surveys(tenant_id,customer_id,created_at DESC);
CREATE TABLE customer_survey_responses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),survey_id uuid NOT NULL UNIQUE REFERENCES customer_surveys(id) ON DELETE CASCADE,answers jsonb NOT NULL,submitted_at timestamptz NOT NULL DEFAULT now());
