ALTER TABLE businesses ADD COLUMN IF NOT EXISTS registration_number text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS contact_email text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS phone_e164 text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS website_url text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS address_line_1 text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS address_line_2 text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS postcode text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS country_code char(2) NOT NULL DEFAULT 'MY';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS business_type text NOT NULL DEFAULT 'GENERAL';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS business_subtype text;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS offering_kind text NOT NULL DEFAULT 'PACKAGE';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS workflow_kind text NOT NULL DEFAULT 'ENQUIRY';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS setup_config jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS property_type text NOT NULL DEFAULT 'OTHER_PROPERTY';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS unit_count integer NOT NULL DEFAULT 1 CHECK(unit_count > 0);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS room_count integer NOT NULL DEFAULT 1 CHECK(room_count >= 0);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS public_holiday_price_minor bigint NOT NULL DEFAULT 0 CHECK(public_holiday_price_minor >= 0);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS peak_season_price_minor bigint NOT NULL DEFAULT 0 CHECK(peak_season_price_minor >= 0);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS extra_guest_charge_minor bigint NOT NULL DEFAULT 0 CHECK(extra_guest_charge_minor >= 0);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS private_pool boolean NOT NULL DEFAULT false;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS availability_rules jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS booking_rules jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS business_offerings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  business_id uuid NOT NULL,
  source_key text NOT NULL,
  offering_type text NOT NULL CHECK(offering_type IN('SERVICE','PROPERTY','PRODUCT','CLASS','PACKAGE')),
  name text NOT NULL,
  description text,
  price_minor bigint NOT NULL DEFAULT 0 CHECK(price_minor >= 0),
  currency char(3) NOT NULL DEFAULT 'MYR',
  duration_minutes integer CHECK(duration_minutes IS NULL OR duration_minutes > 0),
  capacity integer NOT NULL DEFAULT 1 CHECK(capacity > 0),
  deposit_minor bigint NOT NULL DEFAULT 0 CHECK(deposit_minor >= 0),
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_domain text,
  source_id uuid,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id,business_id,source_key),
  FOREIGN KEY(tenant_id,business_id) REFERENCES businesses(tenant_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS business_offerings_tenant_active_idx ON business_offerings(tenant_id,offering_type,active,name);

INSERT INTO saas_plans(code,name,monthly_price_minor,currency,entitlements)
VALUES(
  'TRIAL',
  'Free Trial',
  0,
  'MYR',
  '{"ai_requests":200,"bookings_monthly":200,"campaigns_monthly":10,"marketing":true,"advanced_booking":true,"whatsapp":true}'::jsonb
)
ON CONFLICT(code) DO UPDATE SET
  name=excluded.name,
  monthly_price_minor=excluded.monthly_price_minor,
  currency=excluded.currency,
  entitlements=excluded.entitlements,
  active=true,
  updated_at=now();

COMMENT ON COLUMN businesses.registration_number IS 'Tenant-entered company or business registration number.';
COMMENT ON COLUMN businesses.contact_email IS 'Operational company contact email; authentication email remains on users.';
COMMENT ON COLUMN businesses.setup_config IS 'Validated workflow, payment and WhatsApp AI configuration generated by the dynamic setup wizard.';
COMMENT ON TABLE business_offerings IS 'Universal tenant offering catalogue projected into a domain table only when that domain exists.';
