import test from 'node:test';import assert from 'node:assert/strict';
import { BookingConflictError,BookingService,BookingStateError,assertPositiveMinutes,type Booking,type BookingAuditEvent,type BookingRepository } from './index.js';
import type { AvailabilityRepository } from '@wsadmin-business/availability';
import { DEFAULT_BOOKING_POLICY } from '@wsadmin-business/booking-policy';
class AvailabilityRepo implements AvailabilityRepository{busy=0;lastExclude:string|undefined;policy={...DEFAULT_BOOKING_POLICY,minimumLeadMinutes:0,bookingHorizonDays:365,cancellationDeadlineMinutes:0};async getTenantTimezone(){return'Asia/Kuala_Lumpur';}async getBookingPolicy(){return this.policy;}async getService(){return{id:'svc',active:true,durationMinutes:60,bufferBeforeMinutes:15,bufferAfterMinutes:15};}async listEligibleStaff(){return[{id:'staff',active:true,bookingCapacity:1}];}async getWeeklyHours(){return[{weekday:1,startMinute:540,endMinute:1080}];}async getShiftOverrides(){return[];}async getTimeBlocks(){return[];}async listCompatibleResources(){return[{id:'room',active:true,capacity:1}];}async countBusyBookings(q:any){this.lastExclude=q.excludeBookingId;return this.busy;}}
class BookingRepo implements BookingRepository{rows:Booking[]=[];audits:BookingAuditEvent[]=[];conflict=false;async createWithConflictGuard(i:any){if(this.conflict)throw new BookingConflictError();const r:Booking={id:`b${this.rows.length+1}`,...i,createdAt:new Date(),updatedAt:new Date()};this.rows.push(r);return r;}async get(t:string,id:string){return this.rows.find(x=>x.tenantId===t&&x.id===id)??null;}async transitionStatus(i:any){const r=await this.get(i.tenantId,i.bookingId);if(!r)throw new Error('missing');if(!i.allowedFrom.includes(r.status))throw new BookingStateError('bad state');r.status=i.toStatus;r.updatedAt=new Date();return r;}async rescheduleWithConflictGuard(i:any){const r=await this.get(i.tenantId,i.bookingId);if(!r)throw new Error('missing');Object.assign(r,{staffId:i.staffId,resourceId:i.resourceId,startsAt:i.startsAt,endsAt:i.endsAt,effectiveStartsAt:i.effectiveStartsAt,effectiveEndsAt:i.effectiveEndsAt,updatedAt:new Date()});return r;}async listAudit(t:string,id:string){return this.audits.filter(x=>x.tenantId===t&&x.bookingId===id);}}
test('booking duration requires positive integer minutes',()=>{assert.equal(assertPositiveMinutes(30,'duration'),30);assert.throws(()=>assertPositiveMinutes(0,'duration'));});
test('booking service persists only an availability candidate',async()=>{const repo=new BookingRepo(),svc=new BookingService(new AvailabilityRepo(),repo);const row=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'});assert.equal(row.staffId,'staff');assert.equal(row.resourceId,'room');assert.equal(row.status,'CONFIRMED');});
test('booking service surfaces transaction conflict',async()=>{const repo=new BookingRepo();repo.conflict=true;const svc=new BookingService(new AvailabilityRepo(),repo);await assert.rejects(()=>svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}),BookingConflictError);});
test('booking lifecycle rejects invalid terminal transition',async()=>{const repo=new BookingRepo(),svc=new BookingService(new AvailabilityRepo(),repo);const row=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'});const cancelled=await svc.cancel('t',row.id,'owner','customer request');assert.equal(cancelled.status,'CANCELLED');await assert.rejects(()=>svc.complete('t',row.id,'owner'),BookingStateError);});
test('reschedule excludes the booking itself from capacity checks',async()=>{const repo=new BookingRepo(),availability=new AvailabilityRepo(),svc=new BookingService(availability,repo);const row=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'});const moved=await svc.reschedule({tenantId:'t',bookingId:row.id,startsAt:'2026-08-31T04:00:00Z'});assert.equal(moved.startsAt.toISOString(),'2026-08-31T04:00:00.000Z');assert.equal(availability.lastExclude,row.id);});
test('complete and no-show are valid terminal outcomes from confirmed',async()=>{const repo=new BookingRepo(),svc=new BookingService(new AvailabilityRepo(),repo);const completed=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'});assert.equal((await svc.complete('t',completed.id,'owner')).status,'COMPLETED');const missed=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T04:00:00Z'});assert.equal((await svc.noShow('t',missed.id,'owner')).status,'NO_SHOW');});

test('booking service enforces cancellation deadline',async()=>{const repo=new BookingRepo(),availability=new AvailabilityRepo();availability.policy={...availability.policy,cancellationDeadlineMinutes:10080};const svc=new BookingService(availability,repo,()=>new Date('2026-08-28T00:00:00Z'));const row=await svc.create({tenantId:'t',serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'});await assert.rejects(()=>svc.cancel('t',row.id,'owner'),(e:any)=>e?.name==='BookingPolicyError'&&e?.reason==='cancellation_deadline');});
