import type{WhatsAppMessageProvider,WhatsAppProviderName}from'@wsadmin-business/whatsapp';
export const DELIVERY_STATUSES=['QUEUED','SENDING','RETRY','RATE_LIMITED','SENT','FAILED']as const;
export type DeliveryStatus=(typeof DELIVERY_STATUSES)[number];
export type OutboundDelivery={id:string;tenantId:string;instanceId:string;provider:WhatsAppProviderName;providerInstanceName:string;conversationId:string|null;toE164:string;textContent:string;idempotencyKey:string;status:DeliveryStatus;attemptCount:number;maxAttempts:number;nextAttemptAt:Date;providerMessageId:string|null;lastError:string|null;createdAt:Date;updatedAt:Date};
export interface DeliveryRepository{enqueue(input:{tenantId:string;instanceId:string;provider:WhatsAppProviderName;providerInstanceName:string;conversationId?:string|null;toE164:string;textContent:string;idempotencyKey:string;maxAttempts?:number}):Promise<{delivery:OutboundDelivery;duplicate:boolean}>;claim(now:Date):Promise<OutboundDelivery|null>;markSent(id:string,providerMessageId:string):Promise<void>;markRetry(id:string,input:{status:'RETRY'|'RATE_LIMITED'|'FAILED';nextAttemptAt:Date;lastError:string}):Promise<void>;}
export class DeliveryValidationError extends Error{constructor(message:string){super(message);this.name='DeliveryValidationError';}}
function e164(v:string){const x=v.replace(/\s+/g,'');if(!/^\+[1-9]\d{6,14}$/.test(x))throw new DeliveryValidationError('toE164 must be E.164');return x;}
function text(v:string){const x=v.trim();if(!x)throw new DeliveryValidationError('textContent required');if(x.length>4096)throw new DeliveryValidationError('textContent too long');return x;}
function key(v:string){const x=v.trim();if(!x||x.length>200)throw new DeliveryValidationError('idempotencyKey required');return x;}
export class DeliveryService{
 constructor(private readonly repo:DeliveryRepository,private readonly providerFor:(name:WhatsAppProviderName)=>WhatsAppMessageProvider,private readonly clock:()=>Date=()=>new Date()){}
 enqueue(input:{tenantId:string;instanceId:string;provider:WhatsAppProviderName;providerInstanceName:string;conversationId?:string|null;toE164:string;textContent:string;idempotencyKey:string;maxAttempts?:number}){const max=input.maxAttempts??5;if(!Number.isInteger(max)||max<1||max>10)throw new DeliveryValidationError('maxAttempts must be 1 to 10');return this.repo.enqueue({...input,toE164:e164(input.toE164),textContent:text(input.textContent),idempotencyKey:key(input.idempotencyKey),maxAttempts:max});}
 async processOne(){const row=await this.repo.claim(this.clock());if(!row)return null;try{const p=this.providerFor(row.provider);const sent=await p.sendText({tenantId:row.tenantId,providerInstanceName:row.providerInstanceName,to:row.toE164,text:row.textContent,idempotencyKey:row.idempotencyKey});await this.repo.markSent(row.id,sent.providerMessageId);return{...row,status:'SENT' as const,providerMessageId:sent.providerMessageId};}catch(error){const attempt=row.attemptCount;const rate=Number((error as any)?.status)===429||String((error as any)?.code??'').includes('rate');const failed=attempt>=row.maxAttempts;const seconds=failed?0:Math.min(rate?60*Math.pow(2,attempt-1):30*Math.pow(2,attempt-1),900);const status=failed?'FAILED':rate?'RATE_LIMITED':'RETRY';const next=new Date(this.clock().getTime()+seconds*1000);await this.repo.markRetry(row.id,{status,nextAttemptAt:next,lastError:error instanceof Error?error.message:'delivery failed'});return{...row,status};}}
}
