import{AvailabilityEngine,type AvailabilityCandidate,type AvailabilityRepository}from'@wsadmin-business/availability';
import{BookingConflictError,BookingService,BookingUnavailableError,type Booking,type BookingRepository}from'@wsadmin-business/booking';
export const FLOW_STATES=['AWAIT_LOCATION','AWAIT_SERVICE','AWAIT_DATE','AWAIT_SLOT','AWAIT_CONFIRM'] as const;
export type FlowState=(typeof FLOW_STATES)[number];
export type BookingFlowSession={tenantId:string;conversationId:string;state:FlowState;locationId:string|null;serviceId:string|null;localDate:string|null;slotOptions:string[];selectedStartsAt:Date|null;expiresAt:Date};
export type FlowConversation={tenantId:string;conversationId:string;instanceId:string;customerId:string|null;remoteJid:string;status:'OPEN'|'HUMAN'|'BOT_PAUSED'|'CLOSED'};
export type FlowLocation={id:string;name:string};
export type FlowService={id:string;name:string;priceMinor:number;currency:string};
export type FlowReply={handled:boolean;text:string|null;outboundMessageId:string|null;booking:Booking|null;state:FlowState|null};
export interface WhatsAppBookingFlowRepository{
 getConversation(tenantId:string,conversationId:string):Promise<FlowConversation|null>;
 getSession(tenantId:string,conversationId:string):Promise<BookingFlowSession|null>;
 saveSession(session:BookingFlowSession):Promise<BookingFlowSession>;
 clearSession(tenantId:string,conversationId:string):Promise<void>;
 listLocations(tenantId:string):Promise<FlowLocation[]>;
 listServices(tenantId:string,locationId:string|null):Promise<FlowService[]>;
 getService(tenantId:string,serviceId:string):Promise<FlowService|null>;
 getTimezone(tenantId:string,locationId:string|null):Promise<string>;
 enqueueReply(input:{tenantId:string;instanceId:string;conversationId:string;toJid:string;text:string;idempotencyKey:string}):Promise<{id:string}>;
}
export class WhatsAppBookingFlowError extends Error{constructor(message:string){super(message);this.name='WhatsAppBookingFlowError';}}
function choice(text:string,max:number){const n=Number(text.trim());return Number.isInteger(n)&&n>=1&&n<=max?n-1:-1;}
function validDate(text:string){const v=text.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return null;const d=new Date(`${v}T00:00:00Z`);return Number.isNaN(d.valueOf())||d.toISOString().slice(0,10)!==v?null:v;}
function money(value:number,currency:string){return currency==='MYR'?`RM${(value/100).toFixed(2)}`:`${currency} ${(value/100).toFixed(2)}`;}
function trigger(text:string){return ['booking','book','tempah','appointment','buat tempahan','nak booking'].includes(text.trim().toLowerCase());}
function cancelWord(text:string){return ['cancel','batal','stop','keluar'].includes(text.trim().toLowerCase());}
export class WhatsAppBookingFlowService{
 constructor(private readonly repo:WhatsAppBookingFlowRepository,private readonly deps:{findSlots:(input:{tenantId:string;locationId?:string;serviceId:string;localDate:string;limit?:number})=>Promise<AvailabilityCandidate[]>;createBooking:(input:{tenantId:string;locationId?:string;customerId?:string|null;serviceId:string;startsAt:string;source:'WHATSAPP'})=>Promise<Booking>}){}
 private async reply(c:FlowConversation,eventKey:string,text:string,state:FlowState|null,booking:Booking|null=null):Promise<FlowReply>{const row=await this.repo.enqueueReply({tenantId:c.tenantId,instanceId:c.instanceId,conversationId:c.conversationId,toJid:c.remoteJid,text,idempotencyKey:`flow:${eventKey}:${state??'done'}:${createKey(text)}`});return{handled:true,text,outboundMessageId:row.id,booking,state};}
 private async askServices(c:FlowConversation,eventKey:string,locationId:string|null){const services=await this.repo.listServices(c.tenantId,locationId);if(!services.length){await this.repo.clearSession(c.tenantId,c.conversationId);return this.reply(c,eventKey,'Tiada servis aktif untuk tempahan sekarang.',null);}await this.repo.saveSession({tenantId:c.tenantId,conversationId:c.conversationId,state:'AWAIT_SERVICE',locationId,serviceId:null,localDate:null,slotOptions:[],selectedStartsAt:null,expiresAt:new Date(Date.now()+30*60000)});const lines=services.map((s,i)=>`${i+1}. ${s.name} — ${money(s.priceMinor,s.currency)}`);return this.reply(c,eventKey,`Pilih servis:\n${lines.join('\n')}\n\nBalas nombor pilihan.`, 'AWAIT_SERVICE');}
 async handleInbound(input:{tenantId:string;conversationId:string;text:string;eventKey:string}):Promise<FlowReply>{const c=await this.repo.getConversation(input.tenantId,input.conversationId);if(!c)throw new WhatsAppBookingFlowError('conversation not found');if(c.status!=='OPEN')return{handled:false,text:null,outboundMessageId:null,booking:null,state:null};let session=await this.repo.getSession(c.tenantId,c.conversationId);if(session&&session.expiresAt<=new Date()){await this.repo.clearSession(c.tenantId,c.conversationId);session=null;}
  if(cancelWord(input.text)&&session){await this.repo.clearSession(c.tenantId,c.conversationId);return this.reply(c,input.eventKey,'Tempahan dibatalkan. Balas “booking” untuk mula semula.',null);}
  if(!session){if(!trigger(input.text))return{handled:false,text:null,outboundMessageId:null,booking:null,state:null};const locations=await this.repo.listLocations(c.tenantId);if(locations.length>1){await this.repo.saveSession({tenantId:c.tenantId,conversationId:c.conversationId,state:'AWAIT_LOCATION',locationId:null,serviceId:null,localDate:null,slotOptions:[],selectedStartsAt:null,expiresAt:new Date(Date.now()+30*60000)});return this.reply(c,input.eventKey,`Pilih lokasi:\n${locations.map((l,i)=>`${i+1}. ${l.name}`).join('\n')}\n\nBalas nombor pilihan.`,'AWAIT_LOCATION');}return this.askServices(c,input.eventKey,locations[0]?.id??null);}
  if(session.state==='AWAIT_LOCATION'){const locations=await this.repo.listLocations(c.tenantId),i=choice(input.text,locations.length);if(i<0)return this.reply(c,input.eventKey,'Pilihan lokasi tidak sah. Balas nombor lokasi yang dipaparkan.','AWAIT_LOCATION');return this.askServices(c,input.eventKey,locations[i]!.id);}
  if(session.state==='AWAIT_SERVICE'){const services=await this.repo.listServices(c.tenantId,session.locationId),i=choice(input.text,services.length);if(i<0)return this.reply(c,input.eventKey,'Pilihan servis tidak sah. Balas nombor servis yang dipaparkan.','AWAIT_SERVICE');const service=services[i]!;session={...session,state:'AWAIT_DATE',serviceId:service.id,localDate:null,slotOptions:[],selectedStartsAt:null,expiresAt:new Date(Date.now()+30*60000)};await this.repo.saveSession(session);return this.reply(c,input.eventKey,`Anda pilih ${service.name}. Masukkan tarikh dalam format YYYY-MM-DD, contoh 2026-09-01.`,'AWAIT_DATE');}
  if(session.state==='AWAIT_DATE'){const date=validDate(input.text);if(!date)return this.reply(c,input.eventKey,'Format tarikh tidak sah. Gunakan YYYY-MM-DD, contoh 2026-09-01.','AWAIT_DATE');if(!session.serviceId)throw new WhatsAppBookingFlowError('flow session missing service');const slots=await this.deps.findSlots({tenantId:c.tenantId,locationId:session.locationId??undefined,serviceId:session.serviceId,localDate:date,limit:12});if(!slots.length)return this.reply(c,input.eventKey,'Tiada slot tersedia pada tarikh itu. Cuba tarikh lain (YYYY-MM-DD).','AWAIT_DATE');const tz=await this.repo.getTimezone(c.tenantId,session.locationId),options=slots.map(s=>s.startsAt.toISOString());session={...session,state:'AWAIT_SLOT',localDate:date,slotOptions:options,selectedStartsAt:null,expiresAt:new Date(Date.now()+30*60000)};await this.repo.saveSession(session);const lines=options.map((iso,i)=>`${i+1}. ${formatTime(new Date(iso),tz)}`);return this.reply(c,input.eventKey,`Slot tersedia ${date}:\n${lines.join('\n')}\n\nBalas nombor slot.`,'AWAIT_SLOT');}
  if(session.state==='AWAIT_SLOT'){const i=choice(input.text,session.slotOptions.length);if(i<0)return this.reply(c,input.eventKey,'Pilihan masa tidak sah. Balas nombor slot yang dipaparkan.','AWAIT_SLOT');if(!session.serviceId)throw new WhatsAppBookingFlowError('flow session missing service');const startsAt=new Date(session.slotOptions[i]!);const service=await this.repo.getService(c.tenantId,session.serviceId);if(!service)throw new WhatsAppBookingFlowError('service no longer available');const tz=await this.repo.getTimezone(c.tenantId,session.locationId);session={...session,state:'AWAIT_CONFIRM',selectedStartsAt:startsAt,expiresAt:new Date(Date.now()+30*60000)};await this.repo.saveSession(session);return this.reply(c,input.eventKey,`Sahkan tempahan:\n${service.name}\n${session.localDate} ${formatTime(startsAt,tz)}\n${money(service.priceMinor,service.currency)}\n\nBalas YA untuk sahkan atau BATAL.`,'AWAIT_CONFIRM');}
  if(session.state==='AWAIT_CONFIRM'){const yes=['ya','yes','confirm','sahkan','1'].includes(input.text.trim().toLowerCase());if(!yes)return this.reply(c,input.eventKey,'Balas YA untuk sahkan atau BATAL untuk batalkan.','AWAIT_CONFIRM');if(!session.serviceId||!session.selectedStartsAt)throw new WhatsAppBookingFlowError('flow session incomplete');try{const booking=await this.deps.createBooking({tenantId:c.tenantId,locationId:session.locationId??undefined,customerId:c.customerId,serviceId:session.serviceId,startsAt:session.selectedStartsAt.toISOString(),source:'WHATSAPP'});await this.repo.clearSession(c.tenantId,c.conversationId);const tz=await this.repo.getTimezone(c.tenantId,session.locationId);return this.reply(c,input.eventKey,`Tempahan berjaya disahkan ✅\nTarikh: ${formatDateTime(booking.startsAt,tz)}\nRujukan: ${booking.id.slice(0,8).toUpperCase()}`,null,booking);}catch(e){if(e instanceof BookingUnavailableError||e instanceof BookingConflictError){session={...session,state:'AWAIT_DATE',slotOptions:[],selectedStartsAt:null,expiresAt:new Date(Date.now()+30*60000)};await this.repo.saveSession(session);return this.reply(c,input.eventKey,'Maaf, slot itu baru sahaja tidak tersedia. Masukkan tarikh semula untuk lihat slot terkini.','AWAIT_DATE');}throw e;}}
  return{handled:false,text:null,outboundMessageId:null,booking:null,state:session.state};
 }
}
function formatTime(date:Date,timeZone:string){return new Intl.DateTimeFormat('ms-MY',{timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date);}
function formatDateTime(date:Date,timeZone:string){return new Intl.DateTimeFormat('ms-MY',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date);}
function createKey(text:string){let h=2166136261;for(const ch of text){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
export * from './management.js';
