import{BookingConflictError,BookingPolicyError,BookingStateError,BookingUnavailableError,type Booking}from'@wsadmin-business/booking';import type{AvailabilityCandidate}from'@wsadmin-business/availability';
export const MANAGEMENT_STATES=['AWAIT_BOOKING','AWAIT_ACTION','AWAIT_RESCHEDULE_DATE','AWAIT_RESCHEDULE_SLOT','AWAIT_CANCEL_CONFIRM'] as const;
export type ManagementState=(typeof MANAGEMENT_STATES)[number];export type ManagementAction='RESCHEDULE'|'CANCEL';
export type ManagementSession={tenantId:string;conversationId:string;state:ManagementState;requestedAction:ManagementAction|null;bookingOptions:string[];bookingId:string|null;localDate:string|null;slotOptions:string[];expiresAt:Date};
export type UpcomingBooking={id:string;locationId:string|null;serviceId:string;serviceName:string;startsAt:Date;status:string;optionIds:string[]};
export type ManagementConversation={tenantId:string;conversationId:string;instanceId:string;customerId:string|null;remoteJid:string;status:'OPEN'|'HUMAN'|'BOT_PAUSED'|'CLOSED'};
export interface WhatsAppBookingManagementRepository{
 getConversation(tenantId:string,conversationId:string):Promise<ManagementConversation|null>;getSession(tenantId:string,conversationId:string):Promise<ManagementSession|null>;
 saveSession(session:ManagementSession):Promise<ManagementSession>;clearSession(tenantId:string,conversationId:string):Promise<void>;
 listUpcomingBookings(tenantId:string,customerId:string):Promise<UpcomingBooking[]>;getBooking(tenantId:string,bookingId:string):Promise<UpcomingBooking|null>;
 getTimezone(tenantId:string,locationId:string|null):Promise<string>;enqueueReply(input:{tenantId:string;instanceId:string;conversationId:string;toJid:string;text:string;idempotencyKey:string}):Promise<{id:string}>;
}
export type ManagementReply={handled:boolean;text:string|null;outboundMessageId:string|null;booking:Booking|null;state:ManagementState|null};
function choice(text:string,max:number){const n=Number(text.trim());return Number.isInteger(n)&&n>=1&&n<=max?n-1:-1;}
function dateValue(text:string){const v=text.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return null;const d=new Date(`${v}T00:00:00Z`);return Number.isNaN(d.valueOf())||d.toISOString().slice(0,10)!==v?null:v;}
function trigger(text:string):ManagementAction|'MANAGE'|null{const v=text.trim().toLowerCase();if(['tukar booking','tukar tempahan','reschedule','reschedule booking'].includes(v))return'RESCHEDULE';if(['batal tempahan','batal booking','cancel booking','cancel appointment'].includes(v))return'CANCEL';if(['booking saya','tempahan saya','my booking','my bookings','urus booking','urus tempahan'].includes(v))return'MANAGE';return null;}
function cancelFlow(text:string){return['keluar','stop','kembali','exit'].includes(text.trim().toLowerCase());}
function yes(text:string){return['ya','yes','confirm','sahkan','1'].includes(text.trim().toLowerCase());}
function time(date:Date,tz:string){return new Intl.DateTimeFormat('ms-MY',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date);}
function smallKey(text:string){let h=2166136261;for(const ch of text){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
export class WhatsAppBookingManagementService{
 constructor(private readonly repo:WhatsAppBookingManagementRepository,private readonly deps:{findSlots:(input:{tenantId:string;locationId?:string;serviceId:string;localDate:string;optionIds?:string[];excludeBookingId?:string;limit?:number})=>Promise<AvailabilityCandidate[]>;reschedule:(input:{tenantId:string;bookingId:string;startsAt:string;actorUserId?:string|null})=>Promise<Booking>;cancel:(tenantId:string,bookingId:string,actorUserId?:string|null,reason?:string|null)=>Promise<Booking>}){}
 private async reply(c:ManagementConversation,eventKey:string,text:string,state:ManagementState|null,booking:Booking|null=null):Promise<ManagementReply>{const row=await this.repo.enqueueReply({tenantId:c.tenantId,instanceId:c.instanceId,conversationId:c.conversationId,toJid:c.remoteJid,text,idempotencyKey:`manage:${eventKey}:${state??'done'}:${smallKey(text)}`});return{handled:true,text,outboundMessageId:row.id,booking,state};}
 private expiry(){return new Date(Date.now()+30*60000);}
 private async begin(c:ManagementConversation,eventKey:string,action:ManagementAction|'MANAGE'){if(!c.customerId)return this.reply(c,eventKey,'Tiada rekod pelanggan untuk nombor ini.',null);const rows=await this.repo.listUpcomingBookings(c.tenantId,c.customerId);if(!rows.length)return this.reply(c,eventKey,'Tiada tempahan aktif yang akan datang.',null);const tz=await this.repo.getTimezone(c.tenantId,null);const list=rows.map((b,i)=>`${i+1}. ${b.serviceName} — ${time(b.startsAt,tz)}`);await this.repo.saveSession({tenantId:c.tenantId,conversationId:c.conversationId,state:'AWAIT_BOOKING',requestedAction:action==='MANAGE'?null:action,bookingOptions:rows.map(x=>x.id),bookingId:null,localDate:null,slotOptions:[],expiresAt:this.expiry()});return this.reply(c,eventKey,`Pilih tempahan:\n${list.join('\n')}\n\nBalas nombor pilihan.`,'AWAIT_BOOKING');}
 async handleInbound(input:{tenantId:string;conversationId:string;text:string;eventKey:string}):Promise<ManagementReply>{const c=await this.repo.getConversation(input.tenantId,input.conversationId);if(!c)return{handled:false,text:null,outboundMessageId:null,booking:null,state:null};if(c.status!=='OPEN')return{handled:false,text:null,outboundMessageId:null,booking:null,state:null};let s=await this.repo.getSession(c.tenantId,c.conversationId);if(s&&s.expiresAt<=new Date()){await this.repo.clearSession(c.tenantId,c.conversationId);s=null;}if(cancelFlow(input.text)&&s){await this.repo.clearSession(c.tenantId,c.conversationId);return this.reply(c,input.eventKey,'Pengurusan tempahan dihentikan.',null);}if(!s){const intent=trigger(input.text);return intent?this.begin(c,input.eventKey,intent):{handled:false,text:null,outboundMessageId:null,booking:null,state:null};}
  if(s.state==='AWAIT_BOOKING'){const i=choice(input.text,s.bookingOptions.length);if(i<0)return this.reply(c,input.eventKey,'Pilihan tempahan tidak sah. Balas nombor yang dipaparkan.','AWAIT_BOOKING');const bookingId=s.bookingOptions[i]!,booking=await this.repo.getBooking(c.tenantId,bookingId);if(!booking){await this.repo.clearSession(c.tenantId,c.conversationId);return this.reply(c,input.eventKey,'Tempahan itu tidak lagi tersedia.',null);}s={...s,bookingId,expiresAt:this.expiry()};if(s.requestedAction==='RESCHEDULE'){s={...s,state:'AWAIT_RESCHEDULE_DATE'};await this.repo.saveSession(s);return this.reply(c,input.eventKey,'Masukkan tarikh baru (YYYY-MM-DD).','AWAIT_RESCHEDULE_DATE');}if(s.requestedAction==='CANCEL'){s={...s,state:'AWAIT_CANCEL_CONFIRM'};await this.repo.saveSession(s);return this.reply(c,input.eventKey,`Sahkan pembatalan ${booking.serviceName} pada ${time(booking.startsAt,await this.repo.getTimezone(c.tenantId,booking.locationId))}. Balas YA atau KELUAR.`,'AWAIT_CANCEL_CONFIRM');}s={...s,state:'AWAIT_ACTION'};await this.repo.saveSession(s);return this.reply(c,input.eventKey,'Apa yang anda mahu lakukan?\n1. Tukar tarikh/masa\n2. Batal tempahan','AWAIT_ACTION');}
  if(s.state==='AWAIT_ACTION'){const i=choice(input.text,2);if(i<0)return this.reply(c,input.eventKey,'Balas 1 untuk tukar tarikh/masa atau 2 untuk batal.','AWAIT_ACTION');s={...s,state:i===0?'AWAIT_RESCHEDULE_DATE':'AWAIT_CANCEL_CONFIRM',requestedAction:i===0?'RESCHEDULE':'CANCEL',expiresAt:this.expiry()};await this.repo.saveSession(s);if(i===0)return this.reply(c,input.eventKey,'Masukkan tarikh baru (YYYY-MM-DD).','AWAIT_RESCHEDULE_DATE');const b=s.bookingId?await this.repo.getBooking(c.tenantId,s.bookingId):null;return this.reply(c,input.eventKey,`Sahkan pembatalan${b?` ${b.serviceName}`:''}. Balas YA atau KELUAR.`,'AWAIT_CANCEL_CONFIRM');}
  if(s.state==='AWAIT_RESCHEDULE_DATE'){const date=dateValue(input.text);if(!date)return this.reply(c,input.eventKey,'Format tarikh tidak sah. Gunakan YYYY-MM-DD.','AWAIT_RESCHEDULE_DATE');if(!s.bookingId)throw new Error('management session missing booking');const b=await this.repo.getBooking(c.tenantId,s.bookingId);if(!b)throw new Error('booking missing');const slots=await this.deps.findSlots({tenantId:c.tenantId,locationId:b.locationId??undefined,serviceId:b.serviceId,localDate:date,optionIds:b.optionIds,excludeBookingId:b.id,limit:12});if(!slots.length)return this.reply(c,input.eventKey,'Tiada slot tersedia pada tarikh itu. Cuba tarikh lain.','AWAIT_RESCHEDULE_DATE');const tz=await this.repo.getTimezone(c.tenantId,b.locationId),opts=slots.map(x=>x.startsAt.toISOString());s={...s,state:'AWAIT_RESCHEDULE_SLOT',localDate:date,slotOptions:opts,expiresAt:this.expiry()};await this.repo.saveSession(s);return this.reply(c,input.eventKey,`Slot baru ${date}:\n${opts.map((x,i)=>`${i+1}. ${new Intl.DateTimeFormat('ms-MY',{timeZone:tz,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(x))}`).join('\n')}\n\nBalas nombor slot.`,'AWAIT_RESCHEDULE_SLOT');}
  if(s.state==='AWAIT_RESCHEDULE_SLOT'){const i=choice(input.text,s.slotOptions.length);if(i<0)return this.reply(c,input.eventKey,'Pilihan slot tidak sah.','AWAIT_RESCHEDULE_SLOT');if(!s.bookingId)throw new Error('management session missing booking');try{const booking=await this.deps.reschedule({tenantId:c.tenantId,bookingId:s.bookingId,startsAt:s.slotOptions[i]!,actorUserId:`whatsapp:${c.conversationId}`});await this.repo.clearSession(c.tenantId,c.conversationId);const tz=await this.repo.getTimezone(c.tenantId,booking.locationId);return this.reply(c,input.eventKey,`Tempahan berjaya ditukar. Tarikh baru: ${time(booking.startsAt,tz)}.`,null,booking);}catch(e){if(e instanceof BookingUnavailableError||e instanceof BookingConflictError){s={...s,state:'AWAIT_RESCHEDULE_DATE',slotOptions:[],expiresAt:this.expiry()};await this.repo.saveSession(s);return this.reply(c,input.eventKey,'Slot itu sudah tidak tersedia. Masukkan tarikh semula.','AWAIT_RESCHEDULE_DATE');}throw e;}}
  if(s.state==='AWAIT_CANCEL_CONFIRM'){if(!yes(input.text))return this.reply(c,input.eventKey,'Balas YA untuk batalkan atau KELUAR untuk hentikan.','AWAIT_CANCEL_CONFIRM');if(!s.bookingId)throw new Error('management session missing booking');try{const booking=await this.deps.cancel(c.tenantId,s.bookingId,`whatsapp:${c.conversationId}`,'customer WhatsApp cancellation');await this.repo.clearSession(c.tenantId,c.conversationId);return this.reply(c,input.eventKey,'Tempahan berjaya dibatalkan.',null,booking);}catch(e){await this.repo.clearSession(c.tenantId,c.conversationId);if(e instanceof BookingPolicyError)return this.reply(c,input.eventKey,'Tempahan ini sudah melepasi had masa pembatalan. Sila hubungi staff.',null);if(e instanceof BookingStateError)return this.reply(c,input.eventKey,'Tempahan ini tidak lagi boleh dibatalkan.',null);throw e;}}
  return{handled:false,text:null,outboundMessageId:null,booking:null,state:s.state};
 }
}
