export type DashboardSnapshot={tenantId:string;locationId:string|null;localDate:string;timezone:string;bookings:{total:number;pending:number;confirmed:number;completed:number;cancelled:number;noShow:number};utilization:{activeStaff:number;bookedMinutes:number;scheduledMinutes:number;percentage:number};pendingActions:{pendingBookings:number;noShows:number;attentionCount:number};recent:{id:string;status:string;startsAt:string;endsAt:string;customerName:string|null;serviceName:string;staffName:string;resourceName:string|null}[];byLocation:{locationId:string|null;locationName:string;totalBookings:number;confirmed:number;pending:number;cancelled:number}[]};
export type InboxConversation={id:string;tenantId:string;instanceId:string;customerId:string|null;channel:'WHATSAPP';remoteJid:string;contactE164:string|null;displayName:string|null;status:'OPEN'|'HUMAN'|'BOT_PAUSED'|'CLOSED';unreadCount:number;lastMessageAt:string|null;lastMessagePreview:string|null;aiIntent?:string|null;aiConfidence?:number|null;aiAction?:'EXECUTE'|'CLARIFY'|'HANDOFF'|null;aiReason?:string|null;aiAttentionState?:'NONE'|'CLARIFICATION'|'HUMAN';aiUpdatedAt?:string|null};
export type InboxMessage={id:string;conversationId:string;direction:'INBOUND'|'OUTBOUND';messageType:string|null;textContent:string|null;occurredAt:string;status:string;mediaKind?:'AUDIO'|'IMAGE'|'VIDEO'|'DOCUMENT'|null};
export type UatRole='SYSTEM_OWNER'|'TENANT_OWNER'|'MANAGER'|'STAFF'|'VIEWER';
export const uatTenantId=String((import.meta as any).env?.VITE_UAT_TENANT_ID??'').trim();
const configuredRole=String((import.meta as any).env?.VITE_UAT_ROLE??'TENANT_OWNER').trim();
export const uatRole:UatRole=(['SYSTEM_OWNER','TENANT_OWNER','MANAGER','STAFF','VIEWER'].includes(configuredRole)?configuredRole:'TENANT_OWNER') as UatRole;
async function parseResponse<T>(response:Response):Promise<T>{if(!response.ok){let message=`Request failed (${response.status})`;try{const data=await response.json();message=data?.message??data?.error??message}catch{}throw new Error(message)}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
function actorHeaders(withTenant=true){return{'x-wsadmin-role':uatRole,'x-wsadmin-user-id':'uat-web',...(withTenant&&uatTenantId?{'x-wsadmin-tenant-id':uatTenantId}:{})};}
async function tenantRequest<T>(path:string,init:RequestInit={}):Promise<T>{if(!uatTenantId)throw new Error('UAT tenant is not configured');const response=await fetch(`/api/v1/tenants/${uatTenantId}${path}`,{...init,headers:{...(init.body!==undefined?{'content-type':'application/json'}:{}),...actorHeaders(),...(init.headers??{})}});return parseResponse<T>(response)}
export function tenantGet<T>(path:string,signal?:AbortSignal){return tenantRequest<T>(path,{signal})}export function tenantPatch<T>(path:string,body:unknown){return tenantRequest<T>(path,{method:'PATCH',body:JSON.stringify(body)})}export function tenantPost<T>(path:string,body?:unknown){return tenantRequest<T>(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)})}export function tenantPut<T>(path:string,body:unknown){return tenantRequest<T>(path,{method:'PUT',body:JSON.stringify(body)})}
export async function platformGet<T>(path:string,signal?:AbortSignal){return parseResponse<T>(await fetch(`/api/v1${path}`,{signal,headers:actorHeaders()}))}
export async function systemGet<T>(path:string,signal?:AbortSignal){if(uatRole!=='SYSTEM_OWNER')throw new Error('System Owner role is required');return parseResponse<T>(await fetch(`/api/v1/system${path}`,{signal,headers:actorHeaders(false)}))}
export async function publicGet<T>(tenantId:string,path:string,signal?:AbortSignal){return parseResponse<T>(await fetch(`/api/v1/public/${encodeURIComponent(tenantId)}${path}`,{signal}))}
export async function publicPost<T>(tenantId:string,path:string,body:unknown){return parseResponse<T>(await fetch(`/api/v1/public/${encodeURIComponent(tenantId)}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}))}
export type Booking={id:string;tenantId:string;locationId:string|null;customerId:string|null;serviceId:string;staffId:string;resourceId:string|null;status:'PENDING'|'CONFIRMED'|'COMPLETED'|'CANCELLED'|'NO_SHOW';source:string;assignmentMode:string;optionIds:string[];durationMinutes:number;priceMinor:number;currency:string;notes:string|null;startsAt:string;endsAt:string;createdAt:string;updatedAt:string};
export type Service={id:string;name:string;durationMinutes:number;priceMinor:number;currency:string;active:boolean};export type Staff={id:string;displayName:string;active:boolean;bookingCapacity:number;photoUrl:string|null};
export type AvailabilityResult={available:boolean;reason?:string;candidates:{staffId:string;staffDisplayName:string;resourceId:string|null;startsAt:string;endsAt:string;durationMinutes:number;priceMinor:number;currency:string}[]};
export type CalendarSnapshot={tenantId:string;locationId:string|null;view:'staff'|'resource';from:string;to:string;rows:{id:string;name:string;kind:'STAFF'|'RESOURCE';capacity:number;photoUrl:string|null;resourceType:string|null}[];bookings:{id:string;rowId:string;status:string;startsAt:string;endsAt:string;customerId:string|null;customerName:string|null;serviceId:string;serviceName:string;staffId:string;staffName:string;resourceId:string|null;resourceName:string|null}[];blocks:{id:string;rowId:string;type:'LEAVE'|'BLOCKED'|'STOP_SALE';startsAt:string;endsAt:string;reason:string|null;source?:string;recurrence?:string}[]};
export type CalendarControlBlock={id:string;tenantId:string;scope:'TENANT'|'STAFF'|'RESOURCE';staffId:string|null;resourceId:string|null;type:'STOP_SALE'|'BLOCKED';startsAt:string;endsAt:string;recurrence:'NONE'|'DAILY'|'WEEKLY';recurrenceUntil:string|null;reason:string|null};

export function tenantDelete(path:string){return tenantRequest<unknown>(path,{method:'DELETE'})}
export type StaffProfile={id:string;displayName:string;phone:string|null;email:string|null;active:boolean;bookingCapacity:number;sortOrder:number};
export type ServiceCategory={id:string;name:string;active:boolean;sortOrder:number};
export type CatalogService={id:string;categoryId:string|null;name:string;description:string|null;durationMinutes:number;bufferBeforeMinutes:number;bufferAfterMinutes:number;priceMinor:number;currency:string;active:boolean;sortOrder:number};
export type ServiceOptionGroup={id:string;serviceId:string;name:string;selectionMode:'SINGLE'|'MULTIPLE';required:boolean;active:boolean;sortOrder:number};
export type ServiceOption={id:string;groupId:string;name:string;durationDeltaMinutes:number;priceDeltaMinor:number;requiredResourceType:string|null;active:boolean;sortOrder:number};
export type BusinessResource={id:string;locationId:string|null;name:string;type:'ROOM'|'PROPERTY'|'EQUIPMENT'|'CHAIR'|'BAY'|'VEHICLE'|'OTHER';capacity:number;active:boolean;description:string|null};
export type BusinessLocation={id:string;businessId:string;name:string;code:string;timezone:string|null;address:string|null;active:boolean;sortOrder:number};
export type WeeklyHours={weekday:number;startMinute:number;endMinute:number};
export type Customer={id:string;tenantId:string;name:string|null;phone:string|null;email:string|null;locale:string;status:'ACTIVE'|'ARCHIVED';createdAt:string;updatedAt:string};export type CustomerTag={id:string;tenantId:string;name:string;createdAt:string};
export type CustomerNote={id:string;note:string;actorUserId:string|null;createdAt:string};export type CustomerFieldValue={definitionId:string;key:string;label:string;fieldType:'TEXT'|'NUMBER'|'BOOLEAN'|'DATE'|'JSON';value:unknown;updatedAt:string};export type TimelineItem={id:string;type:string;sourceType:string;sourceId:string|null;title:string;detail:Record<string,unknown>;occurredAt:string};
export type CustomerCrm={tags:CustomerTag[];notes:CustomerNote[];customFields:CustomerFieldValue[];timeline:TimelineItem[]};export type CustomerRestriction={customerId:string;blacklisted:boolean;reason:string|null;blacklistedAt:string|null;mergedIntoCustomerId:string|null;mergedAt:string|null};
export type TreatmentMedia={id:string;mediaKind:'PHOTO'|'VIDEO'|'SKETCH'|'DOCUMENT';storageRef:string;caption:string|null;customerVisible:boolean;createdAt:string};export type TreatmentRecord={id:string;customerId:string;bookingId:string|null;staffId:string|null;serviceId:string|null;occurredAt:string;summary:string;notes:string|null;status:'DRAFT'|'FINAL';media:TreatmentMedia[];createdAt:string};
export type CustomerFieldDefinition={id:string;key:string;label:string;fieldType:'TEXT'|'NUMBER'|'BOOLEAN'|'DATE'|'JSON';active:boolean;sortOrder:number};
export type PaymentRecord={id:string;tenantId:string;bookingId:string;customerId:string|null;provider:string;providerPaymentId:string|null;purpose:'DEPOSIT'|'FULL';amountMinor:number;currency:string;status:'PENDING'|'REQUIRES_ACTION'|'PAID'|'FAILED'|'REFUNDED'|'PARTIALLY_REFUNDED'|'CANCELLED';paidAt:string|null;refundedMinor:number;createdAt:string;updatedAt:string};
export type AutomationTrigger='BOOKING_CONFIRMED'|'BOOKING_REMINDER'|'BOOKING_COMPLETED'|'BIRTHDAY'|'WINBACK'|'REVIEW_REQUEST'|'MANUAL_CAMPAIGN'|'SURVEY_INVITE';
export type AutomationRule={id:string;tenantId:string;name:string;trigger:AutomationTrigger;active:boolean;offsetMinutes:number;config:Record<string,unknown>;createdAt:string;updatedAt:string};
export type AutomationAudit={id:string;tenantId:string;jobId:string|null;ruleId:string|null;eventType:string;detail:Record<string,unknown>;createdAt:string};
export type MessageTemplate={id:string;tenantId:string;templateKey:'BOOKING_CONFIRMATION'|'BOOKING_REMINDER'|'THANK_YOU'|'REVIEW_REQUEST'|'BIRTHDAY'|'WINBACK';name:string;body:string;active:boolean;createdAt:string;updatedAt:string};
export type LifecycleSettings={tenantId:string;confirmationEnabled:boolean;reminderMinutes:number[];thankYouDelayMinutes:number;reviewDelayMinutes:number;birthdayEnabled:boolean;winbackDays:number;updatedAt:string};
export type MessagingPolicy={tenantId:string;timezone:string;quietStartMinute:number;quietEndMinute:number;allowedWeekdays:number[];marketingEnabled:boolean;transactionalEnabled:boolean;maxMessagesPerMinute:number;updatedAt:string};
export type CampaignSegment={tagIds?:string[];lastVisitAfter?:string;lastVisitBefore?:string;minCompletedBookings?:number};
export type MarketingCampaign={id:string;tenantId:string;name:string;body:string;segment:CampaignSegment;status:'DRAFT'|'READY'|'SENDING'|'SENT'|'CANCELLED';scheduledAt:string|null;createdByUserId:string|null;createdAt:string;updatedAt:string};
export type CustomerSurvey={id:string;tenantId:string;bookingId:string|null;customerId:string;status:'OPEN'|'COMPLETED'|'EXPIRED'|'REVOKED';questions:unknown[];expiresAt:string;createdAt:string;completedAt:string|null};
export type ReportDailyPoint={localDate:string;bookings:number;completed:number;revenueMinor:number;refundedMinor:number};
export type BusinessReportSnapshot={tenantId:string;from:string;to:string;timezone:string;currency:string;bookings:{total:number;pending:number;confirmed:number;completed:number;cancelled:number;noShow:number};revenue:{grossMinor:number;refundedMinor:number;netMinor:number;paidCount:number};utilization:{activeStaff:number;bookedMinutes:number;scheduledMinutes:number;percentage:number};customers:{total:number;newCustomers:number;engagedCustomers:number;repeatCustomers:number;repeatRatePercentage:number};automation:{total:number;queued:number;dispatched:number;skipped:number;failed:number};ai:{requests:number;successful:number;failed:number;inputTokens:number;outputTokens:number;latencyAvgMs:number};daily:ReportDailyPoint[]};
export type IntegrationStatus={ai:{providers:{provider:'GROQ'|'OPENAI';configured:boolean}[]};payment:{provider:string|null;mode:'TEST'|'DISABLED';configured:boolean};calendar:{provider:'GOOGLE_CALENDAR';configured:boolean};whatsapp:{provider:'EVOLUTION';configured:boolean;provisioned:boolean;status:'NOT_PROVISIONED'|'DISCONNECTED'|'PAIRING'|'CONNECTED'|'ERROR'|'DISABLED';phoneE164:string|null};secretPolicy:'SERVER_ONLY'};
export type AiSettings={enabled:boolean;primaryProvider:'OPENAI'|'GROQ';primaryModel:string;fallbackProvider:'OPENAI'|'GROQ'|null;fallbackModel:string|null;timeoutMs:number};
export type AiKnowledgeSource={id:string;type:'FAQ'|'SERVICE'|'STAFF'|'RESOURCE'|'LOCATION'|'BOOKING_POLICY';title:string;content:string};
export type AiKnowledgeSourceResponse={query:string;sources:AiKnowledgeSource[]};
export type AiFaqEntry={id:string;tenantId:string;question:string;answer:string;active:boolean;sortOrder:number;createdAt:string;updatedAt:string};
export type AiUnansweredQuestion={id:string;tenantId:string;question:string;normalizedQuestion:string;occurrenceCount:number;status:'OPEN'|'RESOLVED';firstAskedAt:string;lastAskedAt:string;resolvedAt:string|null;resolvedByFaqId:string|null};
export type PrivacyPolicy={tenantId:string;retentionDays:number;messageRetentionDays:number;auditRetentionDays:number;updatedAt:string};
export type BookingPolicy={bookingHorizonDays:number;slotIntervalMinutes:number;minimumLeadMinutes:number;sameDayCutoffMinute:number|null;cancellationDeadlineMinutes:number};
export type WhatsAppPairingResponse={instance:{status:string};qrCode:string|null;pairingCode:string|null;expiresAt:string|null};
export type OnboardingStep='BUSINESS_PROFILE'|'VERTICAL'|'WHATSAPP'|'SERVICES'|'STAFF'|'HOURS'|'COMPLETE';
export type OnboardingState={tenantId:string;currentStep:OnboardingStep;completed:boolean;data:Partial<Record<Exclude<OnboardingStep,'COMPLETE'>,Record<string,unknown>>>;updatedAt:string};
export type SaaSPlan={id:string;code:string;name:string;monthlyPriceMinor:number;currency:string;entitlements:Record<string,number|boolean>;active:boolean};
export type TenantPlanOverview={tenantId:string;periodKey:string;subscription:{tenantId:string;planCode:string;status:'TRIAL'|'ACTIVE'|'PAST_DUE'|'CANCELLED';trialEndsAt:string|null;currentPeriodEndsAt:string|null;cancelAtPeriodEnd:boolean;updatedAt:string}|null;plan:SaaSPlan|null;quotas:{key:string;kind:'QUOTA'|'FEATURE';limit:number|null;used:number|null;remaining:number|null;enabled:boolean}[]};
export type SystemDashboard={tenants:number;subscriptions:Record<string,number>;whatsapp:Record<string,number>;automation:Record<string,number>;ai:{requests:number;inputTokens:number;outputTokens:number;latencyAvgMs:number;estimatedCostMicrousd:number};tenantHealth:{tenantId:string;name:string;subscriptionStatus:string|null;planCode:string|null;whatsappStatus:string|null;openJobs:number;aiRequests:number;aiCostMicrousd:number}[]};
export type PublicService={id:string;name:string;description:string|null;durationMinutes:number;priceMinor:number;currency:string};
export type PublicStaff={id:string;displayName:string;photoUrl:string|null};
export type PublicCatalog={services:PublicService[];payment:{payNowAvailable:boolean}};
export type PublicSlot={staffId:string;staffDisplayName:string;staffPhotoUrl:string|null;resourceId:string|null;startsAt:string;endsAt:string;durationMinutes:number;priceMinor:number;currency:string};
export type PublicAvailability={localDate:string;timezone:string;slots:PublicSlot[]};
export type PublicBookingResponse={booking:{id:string;status:string;customerId:string|null;serviceId:string;staffId:string;resourceId:string|null;priceMinor:number;currency:string;startsAt:string;endsAt:string};paymentChoice:'PAY_NOW'|'PAY_LATER';payment:{payment:{id:string;status:string};link:{paymentId:string;url:string;expiresAt:string|null}}|null;paymentError:string|null};
