import { useCallback,useEffect,useMemo,useState } from 'react';
import { tenantGet,type DashboardSnapshot,type TenantBusinessContext } from './api';

const timeOf=(value:string,timeZone:string)=>new Intl.DateTimeFormat('en-MY',{timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
const prettyDate=(value:string)=>new Intl.DateTimeFormat('en-MY',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00+08:00`));
const statusClass=(value:string)=>value.toLowerCase().replace('_','-');
const human=(value:string|null|undefined)=>value?value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,character=>character.toUpperCase()):'Business';
const money=(minor:number,currency='MYR')=>new Intl.NumberFormat('en-MY',{style:'currency',currency}).format(minor/100);

export function DashboardPreview({businessContext,onNavigate}:{businessContext?:TenantBusinessContext|null;onNavigate?:(module:string)=>void}){
  const[data,setData]=useState<DashboardSnapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const tailored=businessContext?.offeringKind==='PROPERTY'||businessContext?.offeringKind==='PRODUCT';
  const load=useCallback(async(signal?:AbortSignal)=>{if(tailored){setLoading(false);return;}setLoading(true);setError(null);try{setData(await tenantGet<DashboardSnapshot>('/dashboard',signal));}catch(error){if((error as any)?.name!=='AbortError')setError(error instanceof Error?error.message:'Unable to load dashboard');}finally{setLoading(false);}},[tailored]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  if(tailored&&businessContext)return <TailoredDashboard context={businessContext} onNavigate={onNavigate}/>;
  const transactions=businessContext?.labels.transactionPlural??'Bookings',offering=businessContext?.labels.offeringSingular??'Service',staff=businessContext?.labels.staffSingular??'Staff';
  return <>
    <header className="page-header"><div><p className="eyebrow">{businessContext?human(businessContext.businessSubtype):'WSadmin Business'}</p><h1>{businessContext?`${transactions} overview`:'Business overview'}</h1><p className="muted">Live tenant data for {transactions.toLowerCase()}, {offering.toLowerCase()} availability and items that need attention.</p></div><div className="header-actions"><span className="status">{data?`${prettyDate(data.localDate)} · ${data.timezone}`:'Live dashboard'}</span><button className="secondary-button" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></header>
    {error?<div className="data-banner error"><strong>Dashboard unavailable</strong><span>{error}</span><button onClick={()=>void load()}>Retry</button></div>:null}
    {businessContext?<section className="workspace-card business-engine-strip"><div><small>Business engine</small><strong>{human(businessContext.businessSubtype)}</strong></div><b>→</b><div><small>Manage</small><strong>{businessContext.labels.offeringPlural}</strong></div><b>→</b><div><small>Primary journey</small><strong>{human(businessContext.workflowKind)}</strong></div><b>→</b><div><small>AI role</small><strong>{human(businessContext.businessSubtype)} Assistant</strong></div><button className="secondary-button" onClick={()=>onNavigate?.(businessContext.labels.offeringPlural)}>Open {businessContext.labels.offeringPlural.toLowerCase()}</button></section>:null}
    {loading&&!data?<section className="metric-grid">{[1,2,3,4].map(index=><article className="metric-card skeleton" key={index}><div><small>Loading</small><strong>—</strong></div></article>)}</section>:data?<><section className="metric-grid"><article className="metric-card"><div><small>Today {transactions.toLowerCase()}</small><strong>{data.bookings.total}</strong></div><span className="metric-note positive">{data.bookings.confirmed} confirmed</span></article><article className="metric-card"><div><small>{staff} utilization</small><strong>{data.utilization.percentage}%</strong></div><span className="metric-note">{data.utilization.bookedMinutes} / {data.utilization.scheduledMinutes} min</span></article><article className="metric-card"><div><small>Needs attention</small><strong>{data.pendingActions.attentionCount}</strong></div><span className={`metric-note ${data.pendingActions.attentionCount?'warning':''}`}>{data.pendingActions.pendingBookings} pending</span></article><article className="metric-card"><div><small>Cancellations</small><strong>{data.bookings.cancelled}</strong></div><span className="metric-note">{data.bookings.noShow} no-show</span></article></section><section className="dashboard-grid"><article className="dashboard-table-card"><div className="section-head"><div><p className="eyebrow">Live schedule</p><h2>Today {transactions.toLowerCase()}</h2></div><span className="demo-chip">Live data</span></div>{data.recent.length?<div className="booking-list">{data.recent.map(row=><div className="booking-row" key={row.id}><time>{timeOf(row.startsAt,data.timezone)}</time><div><strong>{row.customerName??'Walk-in / unlinked'}</strong><small>{row.serviceName}</small></div><div><strong>{row.staffName}</strong><small>{row.resourceName??'No resource'}</small></div><span className={`booking-status ${statusClass(row.status)}`}>{row.status.replace('_',' ')}</span></div>)}</div>:<div className="empty-inline"><strong>No {transactions.toLowerCase()} today</strong><span>Create the first {businessContext?.labels.transactionSingular.toLowerCase()??'booking'} or let WhatsApp AI handle a customer request.</span></div>}</article><aside className="attention-card"><p className="eyebrow">Attention</p><h2>What needs action</h2><div className="attention-item"><span>{data.pendingActions.pendingBookings}</span><div><strong>Pending confirmations</strong><small>Waiting for confirmation</small></div></div><div className="attention-item muted-item"><span>{data.pendingActions.noShows}</span><div><strong>No-shows</strong><small>Follow-up candidates</small></div></div><div className="attention-item"><span>{data.byLocation.length}</span><div><strong>Locations active today</strong><small>{data.utilization.activeStaff} {staff.toLowerCase()} scheduled</small></div></div></aside></section></>:null}
  </>;
}

function TailoredDashboard({context,onNavigate}:{context:TenantBusinessContext;onNavigate?:(module:string)=>void}){
  const rows=context.offerings.filter(row=>row.active),activeCount=rows.length,totalCapacity=rows.reduce((sum,row)=>sum+row.capacity,0),prices=rows.map(row=>row.priceMinor).filter(value=>value>=0),startingPrice=prices.length?Math.min(...prices):0;
  const ai=useMemo(()=>context.setupConfig.whatsappAi as Record<string,any>|undefined,[context.setupConfig]);
  const property=context.offeringKind==='PROPERTY',stock=rows.reduce((sum,row)=>sum+Number((row.attributes as any)?.stockQuantity??0),0);
  return <>
    <header className="page-header tailored-dashboard-head"><div><p className="eyebrow">{human(context.businessSubtype)} workspace</p><h1>{property?'Property booking overview':'Order & product overview'}</h1><p className="muted">This dashboard follows the tenant wizard: {context.labels.offeringPlural} → {context.labels.transactionPlural} → payment → AI assistant.</p></div><div className="header-actions"><span className="status">{human(context.workflowKind)} workflow</span><button className="primary-button" onClick={()=>onNavigate?.(context.labels.offeringPlural)}>Manage {context.labels.offeringPlural.toLowerCase()}</button></div></header>
    <section className="metric-grid tailored-metrics"><article className="metric-card"><div><small>Active {context.labels.offeringPlural.toLowerCase()}</small><strong>{activeCount}</strong></div><span className="metric-note positive">AI knowledge ready</span></article><article className="metric-card"><div><small>{property?'Total guest capacity':'Opening stock'}</small><strong>{property?totalCapacity:stock}</strong></div><span className="metric-note">Across active {context.labels.offeringPlural.toLowerCase()}</span></article><article className="metric-card"><div><small>Starting price</small><strong>{money(startingPrice)}</strong></div><span className="metric-note">Tenant catalogue</span></article><article className="metric-card"><div><small>AI assistant</small><strong>{ai?.aiEnabled===false?'Off':'On'}</strong></div><span className={`metric-note ${ai?.aiEnabled===false?'warning':'positive'}`}>{human(context.businessSubtype)} trained context</span></article></section>
    <section className="tailored-dashboard-grid"><article className="workspace-card tailored-snapshot"><div className="section-head"><div><p className="eyebrow">Quick view</p><h2>{context.labels.offeringPlural}</h2></div><button className="secondary-button" onClick={()=>onNavigate?.(context.labels.offeringPlural)}>View all</button></div><div className="tailored-snapshot-list">{rows.slice(0,6).map(row=><div key={row.id}><span>{row.name.slice(0,2).toUpperCase()}</span><div><strong>{row.name}</strong><small>{property?`${row.capacity} guests · ${String((row.attributes as any)?.roomType??'Unit')}`:`${Number((row.attributes as any)?.stockQuantity??0)} in stock`}</small></div><b>{money(row.priceMinor,row.currency)}</b></div>)}{!rows.length?<div className="empty-inline"><strong>Finish offering setup</strong><span>Add the first item in Onboarding.</span></div>:null}</div></article><aside className="workspace-card tailored-actions"><p className="eyebrow">Simple next actions</p><h2>Run your {human(context.businessSubtype)}</h2><button onClick={()=>onNavigate?.(context.labels.offeringPlural)}><span>1</span><div><strong>Review {context.labels.offeringPlural.toLowerCase()}</strong><small>Price, capacity and availability</small></div></button><button onClick={()=>onNavigate?.('AI Inbox')}><span>2</span><div><strong>Answer customers</strong><small>AI-grounded WhatsApp inbox</small></div></button><button onClick={()=>onNavigate?.('Onboarding')}><span>3</span><div><strong>Update business rules</strong><small>Workflow, payment and AI behaviour</small></div></button></aside></section>
    <section className="workspace-card ai-dashboard-summary"><div className="ai-role-icon">AI</div><div><p className="eyebrow">Tenant AI role</p><h2>{human(context.businessSubtype)} {context.labels.transactionSingular} Assistant</h2><p>{String(ai?.businessSummary??'Complete Step 8 to generate tenant-specific AI knowledge.')}</p></div><span className={ai?.aiEnabled===false?'settings-status':'settings-status configured'}>{ai?.aiEnabled===false?'Disabled':'Grounded'}</span></section>
  </>;
}
