const data:Record<string,{eyebrow:string;title:string;description:string;metrics:[string,string,string][];rows:{title:string;meta:string;state:string}[];action:string}>={
'AI Inbox':{eyebrow:'AI receptionist',title:'AI Inbox',description:'See what customers ask, what AI understood and where a human should step in.',metrics:[['Open conversations','14','Today'],['AI handled','91%','Last 24h'],['Needs attention','2','Review now']],rows:[{title:'Sarah Lim · “nak tukar booking ke 5 petang”',meta:'RESCHEDULE · confidence 0.94',state:'AI handled'},{title:'Ahmad · “ada slot sabtu petang?”',meta:'AVAILABILITY · confidence 0.89',state:'Waiting reply'},{title:'Nadia · voice note',meta:'BOOK · confidence 0.61',state:'Human review'}],action:'Open conversation'},
'Bookings':{eyebrow:'Booking operations',title:'Bookings',description:'Manage bookings from WhatsApp, web and staff-entered reservations in one place.',metrics:[['Today','8','5 confirmed'],['Pending','2','Needs action'],['This week','46','+12%']],rows:[{title:'10:00 · Fatin Rahman',meta:'Glow Facial · Aina',state:'Confirmed'},{title:'14:00 · Hana Lee',meta:'Deep Tissue · Aina',state:'Pending'},{title:'17:00 · Siti Noor',meta:'Aromatherapy · Sarah',state:'Confirmed'}],action:'Create booking'},
'Customers':{eyebrow:'Customer intelligence',title:'Customers',description:'CRM profiles combine conversations, booking history, notes, tags and treatment records.',metrics:[['Customers','1,284','Active'],['Returning','68%','30 days'],['VIP','42','Tagged']],rows:[{title:'Sarah Lim',meta:'12 bookings · RM1,820 lifetime value',state:'VIP'},{title:'Fatin Rahman',meta:'5 bookings · last visit today',state:'Active'},{title:'Hana Lee',meta:'2 bookings · follow-up due',state:'Follow up'}],action:'Add customer'},
'Staff':{eyebrow:'Team operations',title:'Staff',description:'Manage staff skills, booking capacity, shifts, leave and service assignments.',metrics:[['Active staff','6','3 on shift'],['Utilization','42%','Today'],['On leave','1','Tomorrow']],rows:[{title:'Aina',meta:'Therapist · Facial, Massage',state:'On shift'},{title:'Sarah',meta:'Therapist · Facial, Aromatherapy',state:'On shift'},{title:'Linda',meta:'Therapist · Massage',state:'Break'}],action:'Add staff'},
'Services':{eyebrow:'Service catalog',title:'Services',description:'Configure categories, duration, pricing, options, buffers and staff/resource requirements.',metrics:[['Services','18','Active'],['Categories','5','Published'],['Avg duration','62 min','Today']],rows:[{title:'Glow Facial',meta:'60 min · RM160 · Facial',state:'Active'},{title:'Deep Tissue Massage',meta:'75 min · RM180 · Massage',state:'Active'},{title:'Aromatherapy',meta:'75 min · RM190 · Massage',state:'Active'}],action:'Add service'},
'Resources':{eyebrow:'Capacity',title:'Resources',description:'Rooms, equipment and other constrained resources share the same availability engine.',metrics:[['Resources','7','Active'],['Rooms','3','Cap 1'],['Equipment','4','Shared']],rows:[{title:'Treatment Room 1',meta:'Room · capacity 1',state:'Available'},{title:'Treatment Room 2',meta:'Room · capacity 1',state:'In use'},{title:'Treatment Bed 1',meta:'Equipment · capacity 2',state:'Available'}],action:'Add resource'},
'Payments':{eyebrow:'Revenue operations',title:'Payments',description:'Track deposits, full payments, provider reconciliation, refunds and booking-linked receipts.',metrics:[['Collected today','RM1,280','8 payments'],['Pending','RM320','2 deposits'],['Refunded','RM0','Today']],rows:[{title:'Fatin Rahman · RM160',meta:'Glow Facial · receipt RCP-2026-001',state:'Paid'},{title:'Hana Lee · RM90',meta:'50% deposit · Deep Tissue',state:'Deposit'},{title:'Siti Noor · RM190',meta:'Aromatherapy · reconciled',state:'Paid'}],action:'View transactions'},
'Automation':{eyebrow:'Lifecycle automation',title:'Automation',description:'Run confirmations, reminders, thank-you, review, birthday and win-back journeys safely.',metrics:[['Active rules','9','Enabled'],['Queued','14','Next 24h'],['Delivery','98.7%','7 days']],rows:[{title:'24-hour reminder',meta:'Booking reminder · WhatsApp',state:'Active'},{title:'Thank you + review',meta:'60 min after completion',state:'Active'},{title:'30-day win-back',meta:'Inactive customers',state:'Active'}],action:'New automation'},
'Marketing':{eyebrow:'Customer growth',title:'Marketing',description:'Build consent-aware customer segments, campaigns and post-visit surveys.',metrics:[['Segments','6','Saved'],['Campaign reach','412','This month'],['Survey score','4.7/5','30 days']],rows:[{title:'VIP Re-engagement',meta:'VIP tag · no visit 30+ days',state:'Draft'},{title:'August birthday offer',meta:'Birthday segment · opted in',state:'Scheduled'},{title:'Post-visit survey',meta:'Completed bookings',state:'Active'}],action:'New campaign'},
'Reports':{eyebrow:'Business intelligence',title:'Reports',description:'Understand bookings, revenue, utilization, customers, automation and AI operations.',metrics:[['Revenue','RM18.4k','This month'],['Bookings','126','This month'],['Repeat rate','68%','30 days']],rows:[{title:'Revenue & payments',meta:'Daily / weekly / monthly trends',state:'Ready'},{title:'Staff utilization',meta:'Capacity and booked minutes',state:'Ready'},{title:'AI operations',meta:'Requests, latency and estimated cost',state:'Ready'}],action:'Export report'},
'Settings':{eyebrow:'Platform settings',title:'Settings',description:'Manage business profile, WhatsApp, AI, payments, messaging policy, privacy and integrations.',metrics:[['WhatsApp','Not paired','UAT'],['AI provider','Not configured','Required'],['Payment','Test mode','Gateway']],rows:[{title:'Business & locations',meta:'Timezone · currency · operating hours',state:'Configured'},{title:'WhatsApp connection',meta:'Dedicated tenant instance',state:'Action needed'},{title:'AI & payment providers',meta:'Secrets stored server-side only',state:'Action needed'}],action:'Configure'}
};
export function WorkspacePreview({module}:{module:string}){const d=data[module]??{eyebrow:'Workspace',title:module,description:'Operational workspace.',metrics:[],rows:[],action:'Open'};return <><header className="page-header"><div><p className="eyebrow">{d.eyebrow}</p><h1>{d.title}</h1><p className="muted">{d.description}</p></div><button className="primary-button">{d.action}</button></header><section className="metric-grid metric-grid-three">{d.metrics.map(([label,value,note])=><article className="metric-card" key={label}><div><small>{label}</small><strong>{value}</strong></div><span className="metric-note">{note}</span></article>)}</section><section className="workspace-card"><div className="section-head"><div><p className="eyebrow">UAT workspace</p><h2>{d.title} overview</h2></div><span className="demo-chip">Demo data</span></div><div className="workspace-rows">{d.rows.map(r=><div className="workspace-row" key={r.title}><div className="row-avatar">{r.title.slice(0,2).toUpperCase()}</div><div><strong>{r.title}</strong><small>{r.meta}</small></div><span className="row-state">{r.state}</span><button className="row-menu" aria-label={`Open ${r.title}`}>···</button></div>)}</div></section></>}
