import{decideConfidence}from'./confidence.js';import{AiRouterError}from'./router.js';import type{AiIntent,AiIntentResult}from'./intent.js';import{assertAiToolAllowed,detectPromptInjection,guardAiBusinessTools}from'./security.js';
export type AiResolvedService={id:string;name:string;priceMinor:number;currency:string};
export type AiResolvedLocation={id:string;name:string};
export type AiSlot={startsAt:string;label:string};
export type AiUpcomingBooking={id:string;serviceId:string;serviceName:string;locationId:string|null;startsAt:string};
export interface AiBusinessTools{
 resolveService(tenantId:string,name:string):Promise<AiResolvedService|null>;resolveLocation(tenantId:string,name:string):Promise<AiResolvedLocation|null>;
 findSlots(input:{tenantId:string;serviceId:string;locationId?:string;date:string}):Promise<AiSlot[]>;
 createBooking(input:{tenantId:string;customerId?:string|null;serviceId:string;locationId?:string;startsAt:string}):Promise<{id:string;startsAt:Date}>;
 listUpcoming(tenantId:string,customerId:string):Promise<AiUpcomingBooking[]>;reschedule(tenantId:string,bookingId:string,startsAt:string):Promise<{id:string;startsAt:Date}>;cancel(tenantId:string,bookingId:string):Promise<{id:string}>;
 answerFaq(tenantId:string,question:string):Promise<{answer:string;sources:string[]}|null>;enqueueReply(input:{tenantId:string;instanceId:string;conversationId:string;toJid:string;text:string;idempotencyKey:string}):Promise<{id:string}>;
}
export interface IntentInterpreterLike{interpret(input:{tenantId:string;text:string;conversationId?:string|null}):Promise<AiIntentResult>;}
export type AiOrchestratorResult={handled:boolean;action:'EXECUTE'|'CLARIFY'|'HANDOFF';intent:string;confidence:number;reason:string;reply:string|null;outboundMessageId:string|null;bookingId:string|null};
function money(n:number,c:string){return c==='MYR'?`RM${(n/100).toFixed(2)}`:`${c} ${(n/100).toFixed(2)}`;}
function selectSlot(slots:AiSlot[],time:string|null){if(!slots.length)return null;if(!time)return slots[0]!;const normalized=time.trim().slice(0,5);return slots.find(s=>s.label.startsWith(normalized)||s.label.includes(normalized))??null;}
export class AiBookingOrchestrator{
 constructor(private readonly interpreter:IntentInterpreterLike,private readonly tools:AiBusinessTools){}
 private async send(ctx:any,text:string,key:string,result:Omit<AiOrchestratorResult,'reply'|'outboundMessageId'>){assertAiToolAllowed(result.intent as AiIntent,'SEND_REPLY');const row=await this.tools.enqueueReply({tenantId:ctx.tenantId,instanceId:ctx.instanceId,conversationId:ctx.conversationId,toJid:ctx.remoteJid,text,idempotencyKey:`ai:${ctx.eventKey}:${key}`});return{...result,reply:text,outboundMessageId:row.id};}
 async handle(ctx:{tenantId:string;conversationId:string;instanceId:string;remoteJid:string;customerId?:string|null;text:string;eventKey:string}):Promise<AiOrchestratorResult>{const risk=detectPromptInjection(ctx.text);if(risk.blocked)return{handled:false,action:'HANDOFF',intent:'HANDOFF',confidence:0,reason:risk.reason??'security_handoff',reply:null,outboundMessageId:null,bookingId:null};let intent:AiIntentResult;try{intent=await this.interpreter.interpret({tenantId:ctx.tenantId,conversationId:ctx.conversationId,text:ctx.text});}catch(e){return{handled:false,action:'HANDOFF',intent:'HANDOFF',confidence:0,reason:e instanceof AiRouterError?e.code:'intent_error',reply:null,outboundMessageId:null,bookingId:null};}const tools=guardAiBusinessTools(intent.intent,this.tools);const d=decideConfidence(intent);const base={handled:true,action:d.action,intent:intent.intent,confidence:intent.confidence,reason:d.reason,bookingId:null};if(d.action==='HANDOFF')return{...base,reply:null,outboundMessageId:null};if(d.action==='CLARIFY')return this.send(ctx,d.question??'Boleh jelaskan sedikit?',`clarify:${intent.intent}`,base);
  const service=intent.entities.service?await tools.resolveService(ctx.tenantId,intent.entities.service):null;const location=intent.entities.location?await tools.resolveLocation(ctx.tenantId,intent.entities.location):null;
  if(['BOOK','PRICE','AVAILABILITY'].includes(intent.intent)&&!service)return this.send(ctx,'Saya tidak dapat padankan servis itu. Boleh berikan nama servis yang tepat?',`service:${intent.intent}`,{...base,action:'CLARIFY',reason:'service_not_resolved'});
  if(intent.entities.location&&!location)return this.send(ctx,'Saya tidak dapat padankan lokasi itu. Lokasi/cawangan mana yang anda maksudkan?',`location:${intent.intent}`,{...base,action:'CLARIFY',reason:'location_not_resolved'});
  if(intent.intent==='PRICE'&&service)return this.send(ctx,`${service.name}: ${money(service.priceMinor,service.currency)}.`, 'price',base);
  if((intent.intent==='AVAILABILITY'||intent.intent==='BOOK')&&service){if(!intent.entities.date)return this.send(ctx,'Tarikh bila yang anda mahu?',`date:${intent.intent}`,{...base,action:'CLARIFY',reason:'date_missing'});const slots=await tools.findSlots({tenantId:ctx.tenantId,serviceId:service.id,locationId:location?.id,date:intent.entities.date});if(!slots.length)return this.send(ctx,'Tiada slot tersedia pada tarikh tersebut. Cuba tarikh lain.',`none:${intent.intent}`,{...base,action:'CLARIFY',reason:'no_slots'});if(intent.intent==='AVAILABILITY')return this.send(ctx,`Slot tersedia: ${slots.slice(0,5).map(s=>s.label).join(', ')}.`,`availability`,base);const slot=selectSlot(slots,intent.entities.time);if(!slot)return this.send(ctx,`Masa itu tidak tersedia. Pilihan: ${slots.slice(0,5).map(s=>s.label).join(', ')}.`,`slot`,{...base,action:'CLARIFY',reason:'time_not_available'});const booking=await tools.createBooking({tenantId:ctx.tenantId,customerId:ctx.customerId,serviceId:service.id,locationId:location?.id,startsAt:slot.startsAt});return this.send(ctx,`Tempahan ${service.name} berjaya disahkan pada ${slot.label}. Rujukan ${booking.id.slice(0,8).toUpperCase()}.`,'book',{...base,bookingId:booking.id});}
  if(intent.intent==='RESCHEDULE'||intent.intent==='CANCEL'){if(!ctx.customerId)return{...base,handled:false,action:'HANDOFF',reason:'customer_not_linked',reply:null,outboundMessageId:null};const rows=await tools.listUpcoming(ctx.tenantId,ctx.customerId);if(rows.length!==1)return this.send(ctx,rows.length?'Anda ada lebih daripada satu tempahan aktif. Sila nyatakan tempahan yang mahu diurus.':'Tiada tempahan aktif ditemui.',`manage:${intent.intent}`,{...base,action:rows.length?'CLARIFY':'HANDOFF',reason:rows.length?'booking_ambiguous':'booking_not_found'});const b=rows[0]!;if(intent.intent==='CANCEL'){const cancelled=await tools.cancel(ctx.tenantId,b.id);return this.send(ctx,`Tempahan ${b.serviceName} berjaya dibatalkan.`,'cancel',{...base,bookingId:cancelled.id});}if(!intent.entities.date)return this.send(ctx,'Tarikh baru bila yang anda mahu?','reschedule-date',{...base,action:'CLARIFY',reason:'date_missing'});const slots=await tools.findSlots({tenantId:ctx.tenantId,serviceId:b.serviceId,locationId:b.locationId??undefined,date:intent.entities.date});const slot=selectSlot(slots,intent.entities.time);if(!slot)return this.send(ctx,`Masa itu tidak tersedia. Pilihan: ${slots.slice(0,5).map(s=>s.label).join(', ')}.`,'reschedule-slot',{...base,action:'CLARIFY',reason:'time_not_available'});const moved=await tools.reschedule(ctx.tenantId,b.id,slot.startsAt);return this.send(ctx,`Tempahan ${b.serviceName} berjaya ditukar ke ${slot.label}.`,'reschedule',{...base,bookingId:moved.id});}
  if(intent.intent==='FAQ'){const faq=await tools.answerFaq(ctx.tenantId,ctx.text);if(!faq)return{...base,handled:false,action:'HANDOFF',reason:'faq_not_grounded',reply:null,outboundMessageId:null};return this.send(ctx,faq.answer,'faq',base);}
  return{...base,handled:false,action:'HANDOFF',reason:'unsupported_execution',reply:null,outboundMessageId:null};
 }
}
