import type{AiIntent}from'./intent.js';
export const AI_TOOLS=['READ_BUSINESS_CONTEXT','RESOLVE_SERVICE','RESOLVE_LOCATION','CHECK_AVAILABILITY','CREATE_BOOKING','LIST_BOOKINGS','RESCHEDULE_BOOKING','CANCEL_BOOKING','RESOLVE_PROPERTY','CHECK_PROPERTY_AVAILABILITY','CREATE_PROPERTY_STAY','LIST_PROPERTY_STAYS','RESCHEDULE_PROPERTY_STAY','CANCEL_PROPERTY_STAY','READ_PRICE','READ_FAQ','SEND_REPLY']as const;
export type AiTool=(typeof AI_TOOLS)[number];
const allowed:Record<AiIntent,ReadonlySet<AiTool>>={
 BOOK:new Set(['READ_BUSINESS_CONTEXT','RESOLVE_SERVICE','RESOLVE_LOCATION','CHECK_AVAILABILITY','CREATE_BOOKING','RESOLVE_PROPERTY','CHECK_PROPERTY_AVAILABILITY','CREATE_PROPERTY_STAY','READ_FAQ','SEND_REPLY']),
 RESCHEDULE:new Set(['READ_BUSINESS_CONTEXT','LIST_BOOKINGS','CHECK_AVAILABILITY','RESCHEDULE_BOOKING','LIST_PROPERTY_STAYS','CHECK_PROPERTY_AVAILABILITY','RESCHEDULE_PROPERTY_STAY','SEND_REPLY']),CANCEL:new Set(['READ_BUSINESS_CONTEXT','LIST_BOOKINGS','CANCEL_BOOKING','LIST_PROPERTY_STAYS','CANCEL_PROPERTY_STAY','SEND_REPLY']),
 PRICE:new Set(['READ_BUSINESS_CONTEXT','RESOLVE_SERVICE','RESOLVE_PROPERTY','READ_PRICE','READ_FAQ','SEND_REPLY']),AVAILABILITY:new Set(['READ_BUSINESS_CONTEXT','RESOLVE_SERVICE','RESOLVE_LOCATION','CHECK_AVAILABILITY','RESOLVE_PROPERTY','CHECK_PROPERTY_AVAILABILITY','READ_FAQ','SEND_REPLY']),FAQ:new Set(['READ_BUSINESS_CONTEXT','READ_FAQ','SEND_REPLY']),HANDOFF:new Set(['READ_BUSINESS_CONTEXT'])
};
export class AiSecurityError extends Error{constructor(message:string,public readonly code='ai_security_error'){super(message);this.name='AiSecurityError';}}
export function assertAiToolAllowed(intent:AiIntent,tool:AiTool){if(!allowed[intent].has(tool))throw new AiSecurityError(`Tool ${tool} is not allowed for ${intent}`,'tool_not_allowed');return true;}
const injectionPatterns=[/ignore\s+(all\s+)?(previous|system|developer)\s+(instructions?|prompts?)/i,/reveal|show|print.{0,20}(system prompt|developer message|hidden prompt)/i,/bypass.{0,20}(guard|policy|restriction)/i,/(drop|truncate|delete).{0,12}(database|table)/i,/(execute|run).{0,12}(shell|terminal|command)/i,/pretend you are.{0,30}(admin|system|developer)/i];
export function detectPromptInjection(text:string){const clean=text.replace(/[\u0000-\u001f\u007f]/g,' ').slice(0,8000);const matched=injectionPatterns.find(p=>p.test(clean));return{blocked:Boolean(matched),reason:matched?'prompt_injection_pattern':null,clean};}
export const AI_SECURITY_POLICY='ALLOWLISTED_TOOLS_NO_DIRECT_DB' as const;
const methodTools:Record<string,AiTool>={getBusinessContext:'READ_BUSINESS_CONTEXT',resolveService:'RESOLVE_SERVICE',resolveLocation:'RESOLVE_LOCATION',findSlots:'CHECK_AVAILABILITY',createBooking:'CREATE_BOOKING',listUpcoming:'LIST_BOOKINGS',reschedule:'RESCHEDULE_BOOKING',cancel:'CANCEL_BOOKING',resolveProperty:'RESOLVE_PROPERTY',propertyAvailable:'CHECK_PROPERTY_AVAILABILITY',createPropertyStay:'CREATE_PROPERTY_STAY',listUpcomingStays:'LIST_PROPERTY_STAYS',reschedulePropertyStay:'RESCHEDULE_PROPERTY_STAY',cancelPropertyStay:'CANCEL_PROPERTY_STAY',answerFaq:'READ_FAQ',enqueueReply:'SEND_REPLY'};
export function guardAiBusinessTools<T extends object>(intent:AiIntent,tools:T):T{return new Proxy(tools,{get(target,prop,receiver){const value=Reflect.get(target,prop,receiver);const tool=methodTools[String(prop)];if(!tool||typeof value!=='function')return value;return(...args:any[])=>{assertAiToolAllowed(intent,tool);return value.apply(target,args);};}});}
