import Fastify from 'fastify';
import { Redis } from 'ioredis';
import { CAPABILITIES, ROLES, AccessDeniedError, authorize, type Actor, type Capability, type Role } from '@wsadmin-business/auth';
import { createAiSettingsRepository,createCustomerRepository, createPool, createServiceOptionRepository,createServiceRepository, createStaffRepository, createStaffScheduleRepository, createResourceRepository, createAvailabilityRepository, createBookingPolicyRepository,createBookingRepository, createCalendarControlRepository,createCalendarRepository, createDashboardRepository,createLocationRepository,createWhatsAppInstanceRepository,createWhatsAppProviderEventRepository,createInboxRepository,createWhatsAppBookingFlowRepository,createWhatsAppBookingManagementRepository, probeDatabase } from '@wsadmin-business/database';
import { registerAiSettingsRoutes } from './ai-settings-routes.js';
import { registerCustomerRoutes } from './customer-routes.js';
import { registerServiceRoutes } from './service-routes.js';
import { registerServiceOptionRoutes } from './service-option-routes.js';
import { registerStaffRoutes } from './staff-routes.js';
import { registerStaffScheduleRoutes } from './staff-schedule-routes.js';
import { registerResourceRoutes } from './resource-routes.js';
import { registerAvailabilityRoutes } from './availability-routes.js';
import { registerBookingRoutes } from './booking-routes.js';
import { registerBookingPolicyRoutes } from './booking-policy-routes.js';
import { registerCalendarRoutes } from './calendar-routes.js';
import { registerCalendarControlRoutes } from './calendar-control-routes.js';
import { registerDashboardRoutes } from './dashboard-routes.js';
import { registerInboxRoutes } from './inbox-routes.js';
import { registerLocationRoutes } from './location-routes.js';
import { createWhatsAppConnectionProviderFromEnv } from '@wsadmin-business/whatsapp';
import { registerWhatsAppInstanceRoutes } from './whatsapp-instance-routes.js';
import { createEvolutionWebhookVerifier,registerEvolutionWebhookRoutes } from './evolution-webhook-routes.js';
import { readFileSync } from 'node:fs';
import { findAvailabilitySlots } from '@wsadmin-business/availability';
import { BookingService } from '@wsadmin-business/booking';
import { WhatsAppBookingFlowService,WhatsAppBookingManagementService } from '@wsadmin-business/whatsapp-booking';
export function buildApp(options:{enableDevRbacProbe?:boolean;customerRepository?:import('@wsadmin-business/customers').CustomerRepository;serviceRepository?:import('@wsadmin-business/services').ServiceRepository;staffRepository?:import('@wsadmin-business/staff').StaffRepository;staffScheduleRepository?:import('@wsadmin-business/staff').StaffScheduleRepository;resourceRepository?:import('@wsadmin-business/resources').ResourceRepository;availabilityRepository?:import('@wsadmin-business/availability').AvailabilityRepository;bookingRepository?:import('@wsadmin-business/booking').BookingRepository;calendarRepository?:import('@wsadmin-business/calendar').CalendarRepository;dashboardRepository?:import('@wsadmin-business/dashboard').DashboardRepository;inboxRepository?:import('@wsadmin-business/inbox').InboxRepository;whatsappInstanceRepository?:import('@wsadmin-business/whatsapp').WhatsAppInstanceRepository;whatsappConnectionProvider?:import('@wsadmin-business/whatsapp').WhatsAppConnectionProvider}={}) {
  const app = Fastify({ logger: false });
  const pool = createPool();
  const redis = new Redis(process.env.REDIS_URL ?? 'redis://127.0.0.1:56379/0',{lazyConnect:true,maxRetriesPerRequest:2});
  async function probeRedis(){if(redis.status==='wait')await redis.connect();const pong=await redis.ping();return {status:pong==='PONG'?'ok':'error',namespace:'wsb:'};}
  app.get('/health',async(_request,reply)=>{try{const[database,cache]=await Promise.all([probeDatabase(pool),probeRedis()]);return{service:'wsadmin-business-api',status:'ok',product:'WSadmin Business',isolation:'mvoc-separate',database,cache,timezone:'Asia/Kuala_Lumpur'};}catch(error){reply.code(503);return{service:'wsadmin-business-api',status:'error',error:error instanceof Error?error.message:'health probe failed'};}});
  app.get('/api/v1',async()=>({name:'WSadmin Business API',version:'0.1.0',phase:'P1-booking-core',aiPolicy:'NO_DIRECT_DATABASE_WRITES'}));
  registerAiSettingsRoutes(app,createAiSettingsRepository(pool));
  registerCustomerRoutes(app,options.customerRepository??createCustomerRepository(pool));
  registerServiceRoutes(app,options.serviceRepository??createServiceRepository(pool));
  registerServiceOptionRoutes(app,createServiceOptionRepository(pool));
  registerStaffRoutes(app,options.staffRepository??createStaffRepository(pool));
  registerStaffScheduleRoutes(app,options.staffScheduleRepository??createStaffScheduleRepository(pool));
  registerResourceRoutes(app,options.resourceRepository??createResourceRepository(pool));
  const availabilityRepository=options.availabilityRepository??createAvailabilityRepository(pool);
  const bookingRepository=options.bookingRepository??createBookingRepository(pool);
  registerAvailabilityRoutes(app,availabilityRepository);
  registerBookingRoutes(app,availabilityRepository,bookingRepository);
  registerBookingPolicyRoutes(app,createBookingPolicyRepository(pool));
  registerCalendarRoutes(app,options.calendarRepository??createCalendarRepository(pool));
  registerCalendarControlRoutes(app,createCalendarControlRepository(pool));
  registerDashboardRoutes(app,options.dashboardRepository??createDashboardRepository(pool));
  registerLocationRoutes(app,createLocationRepository(pool));
  registerWhatsAppInstanceRoutes(app,options.whatsappInstanceRepository??createWhatsAppInstanceRepository(pool),options.whatsappConnectionProvider??createWhatsAppConnectionProviderFromEnv());
  let webhookSecret=process.env.EVOLUTION_WEBHOOK_TOKEN;const webhookFile=process.env.EVOLUTION_WEBHOOK_TOKEN_FILE;if(!webhookSecret&&webhookFile){try{webhookSecret=readFileSync(webhookFile,'utf8').trim();}catch{webhookSecret=undefined;}}
  const inboxRepository=options.inboxRepository??createInboxRepository(pool);
  const bookingDomainService=new BookingService(availabilityRepository,bookingRepository);
  const bookingFlow=new WhatsAppBookingFlowService(createWhatsAppBookingFlowRepository(pool),{findSlots:(input)=>findAvailabilitySlots(availabilityRepository,input),createBooking:(input)=>bookingDomainService.create(input)});
  const bookingManagement=new WhatsAppBookingManagementService(createWhatsAppBookingManagementRepository(pool),{findSlots:(input)=>findAvailabilitySlots(availabilityRepository,input),reschedule:(input)=>bookingDomainService.reschedule(input),cancel:(tenantId,bookingId,actorUserId,reason)=>bookingDomainService.cancel(tenantId,bookingId,actorUserId,reason)});
  registerEvolutionWebhookRoutes(app,createWhatsAppProviderEventRepository(pool),createEvolutionWebhookVerifier(webhookSecret),inboxRepository,bookingFlow,bookingManagement);
  registerInboxRoutes(app,inboxRepository);
  if(options.enableDevRbacProbe){app.get('/api/v1/dev/rbac',async(request,reply)=>{const headers=request.headers;const role=String(headers['x-wsadmin-role']??'') as Role;const tenantId=String(headers['x-wsadmin-tenant-id']??'');const targetTenantId=String(headers['x-wsadmin-target-tenant-id']??tenantId);const capability=String(headers['x-wsadmin-capability']??'TENANT_READ') as Capability;if(!ROLES.includes(role)||!CAPABILITIES.includes(capability)||(!tenantId&&role!=='SYSTEM_OWNER'))return reply.code(400).send({error:'invalid_dev_actor'});const actor:Actor={userId:String(headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};try{authorize(actor,targetTenantId,capability);return{allowed:true,role,tenantId:targetTenantId,capability};}catch(error){if(error instanceof AccessDeniedError)return reply.code(403).send({allowed:false,error:error.message});throw error;}});}
  app.addHook('onClose',async()=>{await pool.end();redis.disconnect();});
  return app;
}
