import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{AutomationService,AutomationValidationError,type AutomationRepository}from'@wsadmin-business/automation';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof AutomationValidationError)return reply.code(400).send({error:'automation_validation',message:e.message});throw e;}
export function registerAutomationRoutes(app:FastifyInstance,repo:AutomationRepository){const svc=new AutomationService(repo);
 app.post('/api/v1/tenants/:tenantId/automation/rules',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return reply.code(201).send(await svc.createRule(tenantId,(r.body??{})as any));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/automation/rules',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.listRules(tenantId);});
 app.patch('/api/v1/tenants/:tenantId/automation/rules/:ruleId',async(r,reply)=>{const{tenantId,ruleId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{const row=await svc.updateRule(tenantId,ruleId,(r.body??{})as any);return row??reply.code(404).send({error:'rule_not_found'});}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/automation/jobs',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return reply.code(201).send(await svc.schedule({tenantId,...(r.body??{})as any}));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/automation/audit',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.audit(tenantId,(r.query as any)?.jobId);});
}
