import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{LifecycleAutomationService,TEMPLATE_KEYS,type AutomationRepository,type LifecycleRepository,type TemplateKey}from'@wsadmin-business/automation';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
export function registerAutomationLifecycleRoutes(app:FastifyInstance,lifecycle:LifecycleRepository,automation:AutomationRepository){const planner=new LifecycleAutomationService(lifecycle,automation);
 app.get('/api/v1/tenants/:tenantId/automation/templates',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return lifecycle.listTemplates(tenantId);});
 app.put('/api/v1/tenants/:tenantId/automation/templates/:templateKey',async(r,reply)=>{const{tenantId,templateKey}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;if(!TEMPLATE_KEYS.includes(templateKey))return reply.code(400).send({error:'invalid_template_key'});const b=(r.body??{})as any;if(!String(b.name??'').trim()||!String(b.body??'').trim())return reply.code(400).send({error:'template_name_and_body_required'});return lifecycle.upsertTemplate(tenantId,templateKey as TemplateKey,{name:String(b.name).trim(),body:String(b.body).trim(),active:b.active??true});});
 app.get('/api/v1/tenants/:tenantId/automation/lifecycle-settings',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return lifecycle.getSettings(tenantId);});
 app.put('/api/v1/tenants/:tenantId/automation/lifecycle-settings',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;const b=(r.body??{})as any;if(b.reminderMinutes&&!Array.isArray(b.reminderMinutes))return reply.code(400).send({error:'reminder_minutes_must_be_array'});return lifecycle.upsertSettings(tenantId,b);});
 app.put('/api/v1/tenants/:tenantId/customers/:customerId/automation-profile',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return await lifecycle.upsertCustomerProfile(tenantId,customerId,(r.body??{})as any);}catch(e){if(e instanceof Error&&e.message==='customer_not_found')return reply.code(404).send({error:'customer_not_found'});throw e;}});
 app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/automation/confirmed',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;if(!guard(r,reply,tenantId,'BOOKING_WRITE'))return reply;return{scheduled:await planner.planConfirmed(tenantId,bookingId)};});
 app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/automation/completed',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;if(!guard(r,reply,tenantId,'BOOKING_WRITE'))return reply;return{scheduled:await planner.planCompleted(tenantId,bookingId)};});
 app.post('/api/v1/tenants/:tenantId/automation/daily',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;const d=String((r.body as any)?.localDate??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return reply.code(400).send({error:'localDate_required'});return{scheduled:await planner.planDaily(tenantId,d)};});
}
