import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role } from '@wsadmin-business/auth';
import { BOOKING_SOURCES,BOOKING_STATUSES,BookingConflictError,BookingNotFoundError,BookingPolicyError,BookingService,BookingStateError,BookingUnavailableError,BookingValidationError,type BookingRepository } from '@wsadmin-business/booking';
import type { AvailabilityRepository } from '@wsadmin-business/availability';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof BookingValidationError)return reply.code(400).send({error:'booking_validation',message:e.message});if(e instanceof BookingNotFoundError)return reply.code(404).send({error:'booking_not_found'});if(e instanceof BookingUnavailableError)return reply.code(409).send({error:'booking_unavailable',reason:e.reason});if(e instanceof BookingConflictError)return reply.code(409).send({error:'booking_conflict',message:e.message});if(e instanceof BookingPolicyError)return reply.code(409).send({error:'booking_policy',reason:e.reason,message:e.message});if(e instanceof BookingStateError)return reply.code(409).send({error:'booking_state',message:e.message});throw e;}
export function registerBookingRoutes(app:FastifyInstance,availabilityRepo:AvailabilityRepository,bookingRepo:BookingRepository){const service=new BookingService(availabilityRepo,bookingRepo);
  app.get('/api/v1/tenants/:tenantId/bookings',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{const q=r.query as any;const from=q.from?new Date(q.from):undefined,to=q.to?new Date(q.to):undefined;if(from&&Number.isNaN(from.valueOf()))throw new BookingValidationError('invalid from');if(to&&Number.isNaN(to.valueOf()))throw new BookingValidationError('invalid to');if(q.status&&!BOOKING_STATUSES.includes(q.status))throw new BookingValidationError('invalid status');if(q.source&&!BOOKING_SOURCES.includes(q.source))throw new BookingValidationError('invalid source');return await service.search(tenantId,{from,to,status:q.status,source:q.source,customerId:q.customerId,limit:q.limit?Number(q.limit):undefined,offset:q.offset?Number(q.offset):undefined});}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/manual-batch',async(r,reply)=>{const{tenantId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return reply.code(201).send(await service.createManualBatch({tenantId,...((r.body??{}) as any),actorUserId:actor.userId}));}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings',async(r,reply)=>{const{tenantId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return reply.code(201).send(await service.create({tenantId,...((r.body??{}) as any),actorUserId:actor.userId}));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/bookings/:bookingId',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await service.get(tenantId,bookingId);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/reschedule',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return await service.reschedule({tenantId,bookingId,...((r.body??{}) as any),actorUserId:actor.userId});}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/confirm',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return await service.confirm(tenantId,bookingId,actor.userId);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/cancel',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return await service.cancel(tenantId,bookingId,actor.userId,(r.body as any)?.reason);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/complete',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return await service.complete(tenantId,bookingId,actor.userId);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/no-show',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;const actor=guard(r,reply,tenantId,'BOOKING_WRITE');if(!actor)return reply;try{return await service.noShow(tenantId,bookingId,actor.userId);}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/bookings/:bookingId/audit',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await service.audit(tenantId,bookingId);}catch(e){return fail(reply,e);}});
}
