import test from 'node:test';import assert from 'node:assert/strict';import { buildApp } from './app.js';
import { BookingConflictError,BookingStateError,type Booking,type BookingAuditEvent,type BookingRepository } from '@wsadmin-business/booking';
import type { AvailabilityRepository } from '@wsadmin-business/availability';
process.env.DATABASE_URL??='postgresql://invalid:invalid@127.0.0.1:1/invalid';
class AvailabilityRepo implements AvailabilityRepository{async getTenantTimezone(){return'Asia/Kuala_Lumpur';}async getService(){return{id:'svc',active:true,durationMinutes:60,bufferBeforeMinutes:15,bufferAfterMinutes:15};}async listEligibleStaff(){return[{id:'staff',active:true,bookingCapacity:1}];}async getWeeklyHours(){return[{weekday:1,startMinute:540,endMinute:1080}];}async getShiftOverrides(){return[];}async getTimeBlocks(){return[];}async listCompatibleResources(){return[{id:'room',active:true,capacity:1}];}async countBusyBookings(){return 0;}}
class BookingRepo implements BookingRepository{rows:Booking[]=[];audits:BookingAuditEvent[]=[];conflict=false;async createWithConflictGuard(i:any){if(this.conflict)throw new BookingConflictError();const r:Booking={id:`b${this.rows.length+1}`,...i,createdAt:new Date(),updatedAt:new Date()};this.rows.push(r);return r;}async get(t:string,id:string){return this.rows.find(x=>x.tenantId===t&&x.id===id)??null;}async transitionStatus(i:any){const r=await this.get(i.tenantId,i.bookingId);if(!r)throw new Error('missing');if(!i.allowedFrom.includes(r.status))throw new BookingStateError('bad state');r.status=i.toStatus;return r;}async rescheduleWithConflictGuard(i:any){const r=await this.get(i.tenantId,i.bookingId);if(!r)throw new Error('missing');Object.assign(r,{staffId:i.staffId,resourceId:i.resourceId,startsAt:i.startsAt,endsAt:i.endsAt,effectiveStartsAt:i.effectiveStartsAt,effectiveEndsAt:i.effectiveEndsAt});return r;}async listAudit(t:string,id:string){return this.audits.filter(x=>x.tenantId===t&&x.bookingId===id);}}
const h=(role='TENANT_OWNER',tenant='ta')=>({'x-wsadmin-role':role,'x-wsadmin-tenant-id':tenant,'x-wsadmin-user-id':'owner-1'});
test('booking API creates an availability-approved booking',async()=>{const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:new BookingRepo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h(),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,201);assert.equal(res.json().staffId,'staff');assert.equal(res.json().resourceId,'room');await app.close();});
test('booking API maps transaction conflict to 409',async()=>{const repo=new BookingRepo();repo.conflict=true;const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:repo});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h(),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,409);assert.equal(res.json().error,'booking_conflict');await app.close();});
test('viewer cannot create bookings',async()=>{const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:new BookingRepo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h('VIEWER'),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,403);await app.close();});
test('booking reschedule and cancellation endpoints enforce lifecycle',async()=>{const repo=new BookingRepo(),app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:repo});const created=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h(),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});const id=created.json().id;const moved=await app.inject({method:'POST',url:`/api/v1/tenants/ta/bookings/${id}/reschedule`,headers:h(),payload:{startsAt:'2026-08-31T04:00:00Z'}});assert.equal(moved.statusCode,200);const cancelled=await app.inject({method:'POST',url:`/api/v1/tenants/ta/bookings/${id}/cancel`,headers:h(),payload:{reason:'changed mind'}});assert.equal(cancelled.json().status,'CANCELLED');const complete=await app.inject({method:'POST',url:`/api/v1/tenants/ta/bookings/${id}/complete`,headers:h()});assert.equal(complete.statusCode,409);assert.equal(complete.json().error,'booking_state');await app.close();});
