import test from 'node:test';import assert from 'node:assert/strict';import { buildApp } from './app.js';
import { BookingConflictError,type Booking,type BookingRepository } from '@wsadmin-business/booking';
import type { AvailabilityRepository } from '@wsadmin-business/availability';
process.env.DATABASE_URL??='postgresql://invalid:invalid@127.0.0.1:1/invalid';
class AvailabilityRepo implements AvailabilityRepository{async getTenantTimezone(){return'Asia/Kuala_Lumpur';}async getService(){return{id:'svc',active:true,durationMinutes:60,bufferBeforeMinutes:15,bufferAfterMinutes:15};}async listEligibleStaff(){return[{id:'staff',active:true,bookingCapacity:1}];}async getWeeklyHours(){return[{weekday:1,startMinute:540,endMinute:1080}];}async getShiftOverrides(){return[];}async getTimeBlocks(){return[];}async listCompatibleResources(){return[{id:'room',active:true,capacity:1}];}async countBusyBookings(){return 0;}}
class BookingRepo implements BookingRepository{conflict=false;async createWithConflictGuard(i:any){if(this.conflict)throw new BookingConflictError();return{id:'b1',...i,createdAt:new Date(),updatedAt:new Date()} as Booking;}}
const h=(role='TENANT_OWNER',tenant='ta')=>({'x-wsadmin-role':role,'x-wsadmin-tenant-id':tenant});
test('booking API creates an availability-approved booking',async()=>{const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:new BookingRepo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h(),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,201);assert.equal(res.json().staffId,'staff');assert.equal(res.json().resourceId,'room');await app.close();});
test('booking API maps transaction conflict to 409',async()=>{const repo=new BookingRepo();repo.conflict=true;const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:repo});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h(),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,409);assert.equal(res.json().error,'booking_conflict');await app.close();});
test('viewer cannot create bookings',async()=>{const app=buildApp({availabilityRepository:new AvailabilityRepo(),bookingRepository:new BookingRepo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/bookings',headers:h('VIEWER'),payload:{serviceId:'svc',startsAt:'2026-08-31T02:00:00Z'}});assert.equal(res.statusCode,403);await app.close();});
