import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{CalendarControlService,CalendarControlValidationError,type CalendarControlRepository}from'@wsadmin-business/calendar';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof CalendarControlValidationError)return reply.code(400).send({error:'calendar_control_validation',message:e.message});throw e;}
export function registerCalendarControlRoutes(app:FastifyInstance,repo:CalendarControlRepository){const service=new CalendarControlService(repo);
  app.post('/api/v1/tenants/:tenantId/calendar/blocks',async(r,reply)=>{const{tenantId}=r.params as any;const actor=guard(r,reply,tenantId,'SETTINGS_WRITE');if(!actor)return reply;try{return reply.code(201).send(await service.create(tenantId,{...((r.body??{}) as any),createdByUserId:actor.userId}));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/calendar/blocks',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return await service.list(tenantId,q.from??'',q.to??'');}catch(e){return fail(reply,e);}});
  app.delete('/api/v1/tenants/:tenantId/calendar/blocks/:blockId',async(r,reply)=>{const{tenantId,blockId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;const ok=await service.remove(tenantId,blockId);return ok?reply.code(204).send():reply.code(404).send({error:'calendar_block_not_found'});});
}
