import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{CustomerControlError,CustomerControlService,type CustomerControlRepository}from'@wsadmin-business/customers';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof CustomerControlError){const code=e.code==='not_found'?404:e.code==='conflict'?409:400;return reply.code(code).send({error:e.code,message:e.message});}throw e;}
export function registerCustomerControlRoutes(app:FastifyInstance,repo:CustomerControlRepository){const svc=new CustomerControlService(repo);
 app.get('/api/v1/tenants/:tenantId/customers/:customerId/restrictions',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await svc.get(tenantId,customerId);}catch(e){return fail(reply,e);}});
 app.put('/api/v1/tenants/:tenantId/customers/:customerId/blacklist',async(r,reply)=>{const{tenantId,customerId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{return await svc.blacklist(tenantId,customerId,{...(r.body as any),actorUserId:a.userId});}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/customers/:targetCustomerId/merge',async(r,reply)=>{const{tenantId,targetCustomerId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{return await svc.merge(tenantId,targetCustomerId,String((r.body as any)?.sourceCustomerId??''),a.userId);}catch(e){return fail(reply,e);}});
}
