import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{CustomerCrmService,CustomerCrmValidationError,type CustomerCrmRepository}from'@wsadmin-business/customers';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof CustomerCrmValidationError)return reply.code(400).send({error:'customer_crm_validation',message:e.message});if(e instanceof Error&&['customer_not_found','field_not_found'].includes(e.message))return reply.code(404).send({error:e.message});throw e;}
export function registerCustomerCrmRoutes(app:FastifyInstance,repo:CustomerCrmRepository){const svc=new CustomerCrmService(repo);
 app.post('/api/v1/tenants/:tenantId/customer-tags',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return reply.code(201).send(await svc.createTag(tenantId,String((r.body as any)?.name??'')));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/customer-tags',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.listTags(tenantId);});
 app.put('/api/v1/tenants/:tenantId/customers/:customerId/tags',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return{tags:await svc.setTags(tenantId,customerId,Array.isArray((r.body as any)?.tagIds)?(r.body as any).tagIds:[])}}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/customers/:customerId/notes',async(r,reply)=>{const{tenantId,customerId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{return reply.code(201).send(await svc.addNote(tenantId,customerId,a.userId,String((r.body as any)?.note??'')));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/customers/:customerId/timeline',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return svc.timeline(tenantId,customerId,q.limit?Number(q.limit):100,q.offset?Number(q.offset):0);}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/customers/:customerId/crm',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await svc.profile(tenantId,customerId);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/customer-fields',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return reply.code(201).send(await svc.createField(tenantId,(r.body??{})as any));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/customer-fields',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.listFields(tenantId,(r.query as any)?.includeInactive==='true');});
 app.put('/api/v1/tenants/:tenantId/customers/:customerId/fields/:definitionId',async(r,reply)=>{const{tenantId,customerId,definitionId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return await svc.setField(tenantId,customerId,definitionId,(r.body as any)?.value);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/customers/:customerId/events',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return reply.code(201).send(await svc.recordEvent(tenantId,customerId,(r.body??{})as any));}catch(e){return fail(reply,e);}});
}
