import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{ConversationNotFoundError,InboxService,InboxValidationError,type ConversationStatus,type InboxRepository}from'@wsadmin-business/inbox';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof InboxValidationError)return reply.code(400).send({error:'inbox_validation',message:e.message});if(e instanceof ConversationNotFoundError)return reply.code(404).send({error:'conversation_not_found'});throw e;}
export function registerInboxRoutes(app:FastifyInstance,repo:InboxRepository){const service=new InboxService(repo);
 app.get('/api/v1/tenants/:tenantId/inbox/conversations',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return await service.list(tenantId,{status:q.status as ConversationStatus|undefined,q:q.q,limit:q.limit?Number(q.limit):undefined,offset:q.offset?Number(q.offset):undefined});}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/inbox/conversations/:conversationId',async(r,reply)=>{const{tenantId,conversationId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await service.get(tenantId,conversationId);}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/inbox/conversations/:conversationId/messages',async(r,reply)=>{const{tenantId,conversationId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return await service.messages(tenantId,conversationId,q.limit?Number(q.limit):50,q.offset?Number(q.offset):0);}catch(e){return fail(reply,e);}});
 app.patch('/api/v1/tenants/:tenantId/inbox/conversations/:conversationId/status',async(r,reply)=>{const{tenantId,conversationId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return await service.status(tenantId,conversationId,String((r.body as any)?.status??'') as ConversationStatus);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/inbox/conversations/:conversationId/read',async(r,reply)=>{const{tenantId,conversationId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return await service.markRead(tenantId,conversationId);}catch(e){return fail(reply,e);}});
}
