import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{LocationDirectory,LocationNotFoundError,LocationValidationError,type LocationRepository}from'@wsadmin-business/locations';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof LocationValidationError)return reply.code(400).send({error:'location_validation',message:e.message});if(e instanceof LocationNotFoundError)return reply.code(404).send({error:'location_not_found'});throw e;}
export function registerLocationRoutes(app:FastifyInstance,repo:LocationRepository){const d=new LocationDirectory(repo);
 app.post('/api/v1/tenants/:tenantId/locations',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return reply.code(201).send(await d.create(tenantId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/locations',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;return d.list(tenantId,q.includeInactive==='true');});
 app.get('/api/v1/tenants/:tenantId/locations/:locationId',async(r,reply)=>{const{tenantId,locationId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await d.get(tenantId,locationId);}catch(e){return fail(reply,e);}});
 app.patch('/api/v1/tenants/:tenantId/locations/:locationId',async(r,reply)=>{const{tenantId,locationId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return await d.update(tenantId,locationId,(r.body??{}) as any);}catch(e){return fail(reply,e);}});
 app.put('/api/v1/tenants/:tenantId/locations/:locationId/staff',async(r,reply)=>{const{tenantId,locationId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return{staffIds:await d.setStaff(tenantId,locationId,Array.isArray((r.body as any)?.staffIds)?(r.body as any).staffIds:[]) };}catch(e){return fail(reply,e);}});
 app.put('/api/v1/tenants/:tenantId/locations/:locationId/services',async(r,reply)=>{const{tenantId,locationId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return{serviceIds:await d.setServices(tenantId,locationId,Array.isArray((r.body as any)?.serviceIds)?(r.body as any).serviceIds:[]) };}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/locations/:locationId/assignments',async(r,reply)=>{const{tenantId,locationId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await d.assignments(tenantId,locationId);}catch(e){return fail(reply,e);}});
}
