import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{MarketingAutomationService,MarketingValidationError,type AutomationRepository,type MarketingRepository}from'@wsadmin-business/automation';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof MarketingValidationError){const code=e.message.endsWith('_not_found')?404:400;return reply.code(code).send({error:'marketing_validation',message:e.message});}throw e;}
export function registerMarketingRoutes(app:FastifyInstance,repo:MarketingRepository,automation:AutomationRepository,publicBaseUrl:string){const svc=new MarketingAutomationService(repo,automation,publicBaseUrl);
 app.post('/api/v1/tenants/:tenantId/campaigns',async(r,reply)=>{const{tenantId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{return reply.code(201).send(await svc.createCampaign(tenantId,{...(r.body??{})as any,createdByUserId:a.userId}));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/campaigns',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.listCampaigns(tenantId);});
 app.post('/api/v1/tenants/:tenantId/campaigns/:campaignId/plan',async(r,reply)=>{const{tenantId,campaignId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return await svc.planCampaign(tenantId,campaignId);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/bookings/:bookingId/survey',async(r,reply)=>{const{tenantId,bookingId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{const b=(r.body??{})as any;return reply.code(201).send(await svc.createPostVisitSurvey(tenantId,bookingId,b.questions,b.expiresDays));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/surveys',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return svc.listSurveys(tenantId);});
 app.get('/api/v1/public/surveys/:token',async(r,reply)=>{const{token}=r.params as any;const s=await svc.publicSurvey(token);if(!s)return reply.code(404).send({error:'survey_not_available'});return{id:s.id,questions:s.questions,expiresAt:s.expiresAt};});
 app.post('/api/v1/public/surveys/:token/responses',async(r,reply)=>{const{token}=r.params as any;try{const s=await svc.submitSurvey(token,(r.body as any)?.answers??{});if(!s)return reply.code(404).send({error:'survey_not_available'});return{status:s.status,completedAt:s.completedAt};}catch(e){return fail(reply,e);}});
}
