import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import type{MessagingPolicyRepository}from'@wsadmin-business/automation';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function validatePolicy(b:any){for(const k of ['quietStartMinute','quietEndMinute'])if(b[k]!==undefined&&(!Number.isInteger(b[k])||b[k]<0||b[k]>1439))throw new Error('invalid_quiet_minute');if(b.maxMessagesPerMinute!==undefined&&(!Number.isInteger(b.maxMessagesPerMinute)||b.maxMessagesPerMinute<1||b.maxMessagesPerMinute>1000))throw new Error('invalid_rate_limit');if(b.allowedWeekdays!==undefined&&(!Array.isArray(b.allowedWeekdays)||b.allowedWeekdays.some((x:any)=>!Number.isInteger(x)||x<0||x>6)))throw new Error('invalid_weekdays');if(b.timezone!==undefined){try{new Intl.DateTimeFormat('en',{timeZone:b.timezone}).format()}catch{throw new Error('invalid_timezone')}}return b;}
export function registerMessagingPolicyRoutes(app:FastifyInstance,repo:MessagingPolicyRepository){
 app.get('/api/v1/tenants/:tenantId/messaging-policy',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return repo.getPolicy(tenantId);});
 app.put('/api/v1/tenants/:tenantId/messaging-policy',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return await repo.upsertPolicy(tenantId,validatePolicy((r.body??{})as any));}catch(e){if(e instanceof Error&&e.message.startsWith('invalid_'))return reply.code(400).send({error:e.message});throw e;}});
 app.get('/api/v1/tenants/:tenantId/customers/:customerId/channel-preferences',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await repo.getPreference(tenantId,customerId);}catch(e){if(e instanceof Error&&e.message==='customer_not_found')return reply.code(404).send({error:'customer_not_found'});throw e;}});
 app.put('/api/v1/tenants/:tenantId/customers/:customerId/channel-preferences',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{const b=(r.body??{})as any;return await repo.upsertPreference(tenantId,customerId,{whatsappEnabled:b.whatsappEnabled,marketingOptIn:b.marketingOptIn});}catch(e){if(e instanceof Error&&e.message==='customer_not_found')return reply.code(404).send({error:'customer_not_found'});throw e;}});
}
