import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role } from '@wsadmin-business/auth';
import { RESOURCE_TYPES,ResourceConflictError,ResourceDirectory,ResourceNotFoundError,ResourceValidationError,type ResourceRepository,type ResourceType } from '@wsadmin-business/resources';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof ResourceValidationError)return reply.code(400).send({error:'resource_validation',message:e.message});if(e instanceof ResourceNotFoundError||e instanceof Error&&e.message==='resource_not_found')return reply.code(404).send({error:'resource_not_found'});if(e instanceof ResourceConflictError)return reply.code(409).send({error:'resource_conflict',message:e.message});throw e;}
export function registerResourceRoutes(app:FastifyInstance,repo:ResourceRepository){const directory=new ResourceDirectory(repo);
  app.post('/api/v1/tenants/:tenantId/resources',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'RESOURCE_WRITE'))return reply;try{return reply.code(201).send(await directory.create(tenantId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/resources',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as Record<string,string|undefined>;try{return directory.search(tenantId,{q:q.q,type:q.type as ResourceType|undefined,active:q.active===undefined?undefined:q.active==='true',serviceId:q.serviceId,limit:q.limit?Number(q.limit):undefined,offset:q.offset?Number(q.offset):undefined});}catch(e){return fail(reply,e);}});
  app.get('/api/v1/resource-types',async()=>({resourceTypes:RESOURCE_TYPES}));
  app.get('/api/v1/tenants/:tenantId/resources/:resourceId',async(r,reply)=>{const{tenantId,resourceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await directory.get(tenantId,resourceId);}catch(e){return fail(reply,e);}});
  app.patch('/api/v1/tenants/:tenantId/resources/:resourceId',async(r,reply)=>{const{tenantId,resourceId}=r.params as any;if(!guard(r,reply,tenantId,'RESOURCE_WRITE'))return reply;try{return await directory.update(tenantId,resourceId,(r.body??{}) as any);}catch(e){return fail(reply,e);}});
  app.put('/api/v1/tenants/:tenantId/resources/:resourceId/services',async(r,reply)=>{const{tenantId,resourceId}=r.params as any;if(!guard(r,reply,tenantId,'RESOURCE_WRITE'))return reply;try{return{serviceIds:await directory.setServices(tenantId,resourceId,Array.isArray((r.body as any)?.serviceIds)?(r.body as any).serviceIds:[])};}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/resources/:resourceId/services',async(r,reply)=>{const{tenantId,resourceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return{serviceIds:await directory.getServices(tenantId,resourceId)};}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/resources/:resourceId/services/:serviceId/compatibility',async(r,reply)=>{const{tenantId,resourceId,serviceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return{compatible:await repo.isCompatible(tenantId,resourceId,serviceId)};});
}
