import test from 'node:test';import assert from 'node:assert/strict';import { buildApp } from './app.js';
import type { Resource,ResourceRepository } from '@wsadmin-business/resources';
process.env.DATABASE_URL??='postgresql://invalid:invalid@127.0.0.1:1/invalid';
class Repo implements ResourceRepository{rows:Resource[]=[];links=new Map<string,string[]>();async create(t:string,i:any){const r:any={id:`r${this.rows.length+1}`,tenantId:t,name:i.name,type:i.type,capacity:i.capacity??1,active:i.active??true,sortOrder:i.sortOrder??0,description:i.description??null,createdAt:new Date(),updatedAt:new Date()};this.rows.push(r);return r;}async get(t:string,id:string){return this.rows.find(x=>x.tenantId===t&&x.id===id)??null;}async search(t:string,q:any){return this.rows.filter(x=>x.tenantId===t&&(q.active===undefined||x.active===q.active)&&(!q.type||x.type===q.type)&&(!q.q||x.name.toLowerCase().includes(String(q.q).toLowerCase()))&&(!q.serviceId||(this.links.get(`${t}:${x.id}`)??[]).includes(q.serviceId)));}async update(t:string,id:string,i:any){const r=await this.get(t,id);if(!r)return null;Object.assign(r,i);return r;}async setServices(t:string,r:string,ids:string[]){this.links.set(`${t}:${r}`,ids);return ids;}async getServices(t:string,r:string){return this.links.get(`${t}:${r}`)??[];}async isCompatible(t:string,r:string,s:string){return(await this.getServices(t,r)).includes(s);}}
const h=(role='TENANT_OWNER',tenant='ta')=>({'x-wsadmin-role':role,'x-wsadmin-tenant-id':tenant});
test('resource CRUD and service compatibility work',async()=>{const repo=new Repo(),app=buildApp({resourceRepository:repo});const created=await app.inject({method:'POST',url:'/api/v1/tenants/ta/resources',headers:h(),payload:{name:'Treatment Room 1',type:'ROOM',capacity:2}});assert.equal(created.statusCode,201);const id=created.json().id;const assigned=await app.inject({method:'PUT',url:`/api/v1/tenants/ta/resources/${id}/services`,headers:h(),payload:{serviceIds:['svc1']}});assert.deepEqual(assigned.json().serviceIds,['svc1']);const compatible=await app.inject({method:'GET',url:`/api/v1/tenants/ta/resources/${id}/services/svc1/compatibility`,headers:h()});assert.equal(compatible.json().compatible,true);await app.close();});
test('resource validation rejects zero capacity',async()=>{const app=buildApp({resourceRepository:new Repo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/resources',headers:h(),payload:{name:'Bad',type:'ROOM',capacity:0}});assert.equal(res.statusCode,400);await app.close();});
test('staff cannot configure resources',async()=>{const app=buildApp({resourceRepository:new Repo()});const res=await app.inject({method:'POST',url:'/api/v1/tenants/ta/resources',headers:h('STAFF'),payload:{name:'Room',type:'ROOM'}});assert.equal(res.statusCode,403);await app.close();});
test('cross tenant resource read is blocked',async()=>{const app=buildApp({resourceRepository:new Repo()});const res=await app.inject({method:'GET',url:'/api/v1/tenants/tb/resources',headers:h('STAFF','ta')});assert.equal(res.statusCode,403);await app.close();});
