import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{ServiceOptions,ServiceOptionValidationError,type ServiceOptionRepository}from'@wsadmin-business/services';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof ServiceOptionValidationError)return reply.code(400).send({error:'service_option_validation',message:e.message});throw e;}
export function registerServiceOptionRoutes(app:FastifyInstance,repo:ServiceOptionRepository){const service=new ServiceOptions(repo);
 app.post('/api/v1/tenants/:tenantId/services/:serviceId/option-groups',async(r,reply)=>{const{tenantId,serviceId}=r.params as any;if(!guard(r,reply,tenantId,'SERVICE_WRITE'))return reply;try{return reply.code(201).send(await service.createGroup(tenantId,serviceId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/services/:serviceId/option-groups',async(r,reply)=>{const{tenantId,serviceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;return service.listGroups(tenantId,serviceId,q.includeInactive==='true');});
 app.post('/api/v1/tenants/:tenantId/option-groups/:groupId/options',async(r,reply)=>{const{tenantId,groupId}=r.params as any;if(!guard(r,reply,tenantId,'SERVICE_WRITE'))return reply;try{return reply.code(201).send(await service.createOption(tenantId,groupId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
 app.patch('/api/v1/tenants/:tenantId/service-options/:optionId',async(r,reply)=>{const{tenantId,optionId}=r.params as any;if(!guard(r,reply,tenantId,'SERVICE_WRITE'))return reply;try{return await service.updateOption(tenantId,optionId,(r.body??{}) as any);}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/services/:serviceId/options',async(r,reply)=>{const{tenantId,serviceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;return service.listOptions(tenantId,serviceId,q.includeInactive==='true');});
}
