import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role } from '@wsadmin-business/auth';
import { StaffScheduleService,StaffScheduleValidationError,type StaffScheduleRepository } from '@wsadmin-business/staff';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof StaffScheduleValidationError)return reply.code(400).send({error:'staff_schedule_validation',message:e.message});if(e instanceof Error&&e.message==='staff_not_found')return reply.code(404).send({error:'staff_not_found'});throw e;}
export function registerStaffScheduleRoutes(app:FastifyInstance,repo:StaffScheduleRepository){const schedule=new StaffScheduleService(repo);
  app.put('/api/v1/tenants/:tenantId/staff/:staffId/working-hours',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return{intervals:await schedule.setWeeklyHours(tenantId,staffId,Array.isArray((r.body as any)?.intervals)?(r.body as any).intervals:[])};}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId/working-hours',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return{intervals:await schedule.getWeeklyHours(tenantId,staffId)};});
  app.post('/api/v1/tenants/:tenantId/staff/:staffId/shift-overrides',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return reply.code(201).send(await schedule.addShiftOverride(tenantId,staffId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId/shift-overrides',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return schedule.listShiftOverrides(tenantId,staffId,q.from,q.to);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/staff/:staffId/time-blocks',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return reply.code(201).send(await schedule.addTimeBlock(tenantId,staffId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId/time-blocks',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;try{return schedule.listTimeBlocks(tenantId,staffId,q.from,q.to);}catch(e){return fail(reply,e);}});
}
