import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role } from '@wsadmin-business/auth';
import { StaffConflictError,StaffDirectory,StaffNotFoundError,StaffValidationError,type StaffRepository } from '@wsadmin-business/staff';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof StaffValidationError)return reply.code(400).send({error:'staff_validation',message:e.message});if(e instanceof StaffNotFoundError)return reply.code(404).send({error:'staff_not_found'});if(e instanceof StaffConflictError)return reply.code(409).send({error:'staff_conflict',message:e.message});throw e;}
export function registerStaffRoutes(app:FastifyInstance,repo:StaffRepository){const directory=new StaffDirectory(repo);
  app.post('/api/v1/tenants/:tenantId/staff',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return reply.code(201).send(await directory.createStaff(tenantId,(r.body??{}) as any));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;return directory.listStaff(tenantId,q.includeInactive==='true');});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await directory.getStaff(tenantId,staffId);}catch(e){return fail(reply,e);}});
  app.patch('/api/v1/tenants/:tenantId/staff/:staffId',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return await directory.updateStaff(tenantId,staffId,(r.body??{}) as any);}catch(e){return fail(reply,e);}});
  app.post('/api/v1/tenants/:tenantId/skills',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return reply.code(201).send(await directory.createSkill(tenantId,String((r.body as any)?.name??'')));}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/skills',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return directory.listSkills(tenantId);});
  app.put('/api/v1/tenants/:tenantId/staff/:staffId/skills',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return{skillIds:await directory.setSkills(tenantId,staffId,Array.isArray((r.body as any)?.skillIds)?(r.body as any).skillIds:[]) };}catch(e){return fail(reply,e);}});
  app.put('/api/v1/tenants/:tenantId/staff/:staffId/services',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'STAFF_WRITE'))return reply;try{return{serviceIds:await directory.setServices(tenantId,staffId,Array.isArray((r.body as any)?.serviceIds)?(r.body as any).serviceIds:[]) };}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId/services',async(r,reply)=>{const{tenantId,staffId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{await directory.getStaff(tenantId,staffId);return{serviceIds:await repo.getStaffServices(tenantId,staffId)};}catch(e){return fail(reply,e);}});
  app.get('/api/v1/tenants/:tenantId/staff/:staffId/services/:serviceId/eligibility',async(r,reply)=>{const{tenantId,staffId,serviceId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;return{eligible:await repo.isEligibleForService(tenantId,staffId,serviceId)};});
}
