import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{TreatmentShareError,TreatmentSharingService,type TreatmentSharingRepository}from'@wsadmin-business/treatments';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof TreatmentShareError)return reply.code(e.code==='not_found'?404:400).send({error:e.code,message:e.message});if(e instanceof Error&&e.message==='treatment_not_found')return reply.code(404).send({error:'treatment_not_found'});throw e;}
export function registerTreatmentSharingRoutes(app:FastifyInstance,repo:TreatmentSharingRepository){const svc=new TreatmentSharingService(repo);
 app.post('/api/v1/tenants/:tenantId/treatments/:recordId/shares',async(r,reply)=>{const{tenantId,recordId}=r.params as any;const a=guard(r,reply,tenantId,'TREATMENT_SHARE_WRITE');if(!a)return reply;try{return reply.code(201).send(await svc.create(tenantId,recordId,{...(r.body as any),actorUserId:a.userId}));}catch(e){return fail(reply,e);}});
 app.delete('/api/v1/tenants/:tenantId/treatments/:recordId/shares/:shareId',async(r,reply)=>{const{tenantId,recordId,shareId}=r.params as any;const a=guard(r,reply,tenantId,'TREATMENT_SHARE_WRITE');if(!a)return reply;try{await svc.revoke(tenantId,recordId,shareId,a.userId);return reply.code(204).send();}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/treatments/:recordId/audit',async(r,reply)=>{const{tenantId,recordId}=r.params as any;if(!guard(r,reply,tenantId,'TREATMENT_SHARE_WRITE'))return reply;return svc.audit(tenantId,recordId,(r.query as any)?.limit?Number((r.query as any).limit):100);});
 app.patch('/api/v1/tenants/:tenantId/treatments/:recordId/media/:mediaId/visibility',async(r,reply)=>{const{tenantId,recordId,mediaId}=r.params as any;const a=guard(r,reply,tenantId,'TREATMENT_SHARE_WRITE');if(!a)return reply;try{return await svc.mediaVisibility(tenantId,recordId,mediaId,(r.body as any)?.customerVisible,a.userId);}catch(e){return fail(reply,e);}});
 app.get('/public/treatment-shares/:token',async(r,reply)=>{const{token}=r.params as any;const view=await svc.public(String(token));return view??reply.code(404).send({error:'share_not_found'});});
}
