import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{TreatmentNotFoundError,TreatmentService,TreatmentValidationError,type TreatmentRepository}from'@wsadmin-business/treatments';
function actor(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'')as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actor(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied'});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof TreatmentValidationError)return reply.code(400).send({error:'treatment_validation',message:e.message});if(e instanceof TreatmentNotFoundError||e instanceof Error&&e.message==='treatment_not_found')return reply.code(404).send({error:'treatment_not_found'});if(typeof e==='object'&&e&&'code'in e&&(e as any).code==='23503')return reply.code(400).send({error:'treatment_reference_invalid'});throw e;}
export function registerTreatmentRoutes(app:FastifyInstance,repo:TreatmentRepository){const svc=new TreatmentService(repo);app.addContentTypeParser('text/csv',{parseAs:'string'},(_req,body,done)=>done(null,body));
 app.post('/api/v1/tenants/:tenantId/treatments',async(r,reply)=>{const{tenantId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{return reply.code(201).send(await svc.create(tenantId,(r.body??{})as any,a.userId));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/treatments/:recordId',async(r,reply)=>{const{tenantId,recordId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await svc.get(tenantId,recordId);}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/customers/:customerId/treatments',async(r,reply)=>{const{tenantId,customerId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;const q=r.query as any;return svc.list(tenantId,customerId,q.limit?Number(q.limit):50,q.offset?Number(q.offset):0);});
 app.post('/api/v1/tenants/:tenantId/treatments/:recordId/media',async(r,reply)=>{const{tenantId,recordId}=r.params as any;if(!guard(r,reply,tenantId,'CUSTOMER_WRITE'))return reply;try{return reply.code(201).send(await svc.addMedia(tenantId,recordId,r.body as any));}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/treatments/import',async(r,reply)=>{const{tenantId}=r.params as any;const a=guard(r,reply,tenantId,'CUSTOMER_WRITE');if(!a)return reply;try{const csv=typeof r.body==='string'?r.body:String((r.body as any)?.csv??'');const rows=await svc.importCsv(tenantId,csv,a.userId);return{imported:rows.length,ids:rows.map(x=>x.id)};}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/treatments/export.csv',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{const csv=await svc.exportCsv(tenantId,(r.query as any)?.customerId);return reply.type('text/csv; charset=utf-8').header('content-disposition','attachment; filename="wsadmin-treatments.csv"').send(csv);}catch(e){return fail(reply,e);}});
}
