import type{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{AccessDeniedError,ROLES,authorize,type Actor,type Capability,type Role}from'@wsadmin-business/auth';import{WhatsAppConnectionService,WhatsAppInstanceError,type WhatsAppConnectionProvider,type WhatsAppInstanceRepository}from'@wsadmin-business/whatsapp';
function actorFrom(r:FastifyRequest):Actor|null{const role=String(r.headers['x-wsadmin-role']??'') as Role;if(!ROLES.includes(role))return null;const tenantId=String(r.headers['x-wsadmin-tenant-id']??'');return{userId:String(r.headers['x-wsadmin-user-id']??'dev-user'),role,...(tenantId?{tenantId}:{})};}
function guard(r:FastifyRequest,reply:FastifyReply,t:string,c:Capability){const a=actorFrom(r);if(!a){reply.code(401).send({error:'authentication_required'});return null;}try{authorize(a,t,c);return a;}catch(e){if(e instanceof AccessDeniedError){reply.code(403).send({error:'access_denied',message:e.message});return null;}throw e;}}
function fail(reply:FastifyReply,e:unknown){if(e instanceof WhatsAppInstanceError){if(e.code==='not_found')return reply.code(404).send({error:e.code,message:e.message});if(e.code==='provider_error'||e.code==='provider_http'||e.code==='provider_config')return reply.code(503).send({error:e.code,message:e.message});return reply.code(400).send({error:e.code,message:e.message});}throw e;}
export function registerWhatsAppInstanceRoutes(app:FastifyInstance,repo:WhatsAppInstanceRepository,provider:WhatsAppConnectionProvider){const service=new WhatsAppConnectionService(repo,provider);
 app.post('/api/v1/tenants/:tenantId/whatsapp/instance',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return reply.code(201).send(await service.provision(tenantId));}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/whatsapp/instance',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await service.get(tenantId);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/whatsapp/instance/pair',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return await service.pair(tenantId);}catch(e){return fail(reply,e);}});
 app.get('/api/v1/tenants/:tenantId/whatsapp/instance/status',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'TENANT_READ'))return reply;try{return await service.refresh(tenantId);}catch(e){return fail(reply,e);}});
 app.post('/api/v1/tenants/:tenantId/whatsapp/instance/disconnect',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{return await service.disconnect(tenantId);}catch(e){return fail(reply,e);}});
 app.delete('/api/v1/tenants/:tenantId/whatsapp/instance',async(r,reply)=>{const{tenantId}=r.params as any;if(!guard(r,reply,tenantId,'SETTINGS_WRITE'))return reply;try{await service.remove(tenantId);return reply.code(204).send();}catch(e){return fail(reply,e);}});
}
