export const WHATSAPP_STATUSES=['DISCONNECTED','PAIRING','CONNECTED','ERROR','DISABLED'] as const;
export type WhatsAppStatus=(typeof WHATSAPP_STATUSES)[number];
export type WhatsAppProviderName='EVOLUTION'|'META_CLOUD';
export type WhatsAppInstance={id:string;tenantId:string;provider:WhatsAppProviderName;providerInstanceName:string;displayName:string;phoneE164:string|null;status:WhatsAppStatus;qrExpiresAt:Date|null;lastConnectedAt:Date|null;lastError:string|null;createdAt:Date;updatedAt:Date};
export type WhatsAppConnectionState={status:WhatsAppStatus;phoneE164?:string|null;providerState?:string|null;error?:string|null};
export type WhatsAppPairingResult={status:WhatsAppStatus;qrCode?:string|null;pairingCode?:string|null;expiresAt?:Date|null};
export interface WhatsAppConnectionProvider{readonly providerName:WhatsAppProviderName;provision(instanceName:string):Promise<WhatsAppConnectionState>;pair(instanceName:string):Promise<WhatsAppPairingResult>;state(instanceName:string):Promise<WhatsAppConnectionState>;logout(instanceName:string):Promise<void>;remove(instanceName:string):Promise<void>;}
export interface WhatsAppInstanceRepository{
 create(tenantId:string,input:{provider:WhatsAppProviderName;providerInstanceName:string;displayName:string}):Promise<WhatsAppInstance>;
 get(tenantId:string):Promise<WhatsAppInstance|null>;
 updateState(tenantId:string,input:{status:WhatsAppStatus;phoneE164?:string|null;qrExpiresAt?:Date|null;lastConnectedAt?:Date|null;lastError?:string|null}):Promise<WhatsAppInstance>;
 remove(tenantId:string):Promise<boolean>;
 event(tenantId:string,instanceId:string,eventType:string,status:WhatsAppStatus,detail?:Record<string,unknown>):Promise<void>;
}
export class WhatsAppInstanceError extends Error{constructor(message:string,public readonly code='whatsapp_instance_error'){super(message);this.name='WhatsAppInstanceError';}}
function instanceName(tenantId:string){const compact=tenantId.toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,24);if(compact.length<8)throw new WhatsAppInstanceError('tenantId cannot form provider instance name');return`wsb-${compact}`;}
export class WhatsAppConnectionService{
 constructor(private readonly repo:WhatsAppInstanceRepository,private readonly provider:WhatsAppConnectionProvider){}
 async provision(tenantId:string){const existing=await this.repo.get(tenantId);if(existing)return existing;const providerInstanceName=instanceName(tenantId);try{const row=await this.repo.create(tenantId,{provider:this.provider.providerName,providerInstanceName,displayName:'WSadmin'});const state=await this.provider.provision(providerInstanceName);const updated=await this.repo.updateState(tenantId,{status:state.status,phoneE164:state.phoneE164??null,lastError:state.error??null,lastConnectedAt:state.status==='CONNECTED'?new Date():null});await this.repo.event(tenantId,updated.id,'PROVISIONED',updated.status,{providerState:state.providerState??null});return updated;}catch(error){throw error instanceof WhatsAppInstanceError?error:new WhatsAppInstanceError(error instanceof Error?error.message:'provider provision failed','provider_error');}}
 async get(tenantId:string){const row=await this.repo.get(tenantId);if(!row)throw new WhatsAppInstanceError('WhatsApp instance not provisioned','not_found');return row;}
 async pair(tenantId:string){const row=await this.get(tenantId);try{const result=await this.provider.pair(row.providerInstanceName);const updated=await this.repo.updateState(tenantId,{status:result.status,qrExpiresAt:result.expiresAt??null,lastError:null});await this.repo.event(tenantId,row.id,'PAIR_REQUESTED',updated.status,{hasQr:Boolean(result.qrCode),hasPairingCode:Boolean(result.pairingCode)});return{instance:updated,qrCode:result.qrCode??null,pairingCode:result.pairingCode??null,expiresAt:result.expiresAt??null};}catch(error){await this.repo.updateState(tenantId,{status:'ERROR',lastError:error instanceof Error?error.message:'pair failed'}).catch(()=>undefined);throw new WhatsAppInstanceError(error instanceof Error?error.message:'pair failed','provider_error');}}
 async refresh(tenantId:string){const row=await this.get(tenantId);try{const state=await this.provider.state(row.providerInstanceName);const updated=await this.repo.updateState(tenantId,{status:state.status,phoneE164:state.phoneE164??row.phoneE164,lastConnectedAt:state.status==='CONNECTED'?(row.lastConnectedAt??new Date()):row.lastConnectedAt,lastError:state.error??null});await this.repo.event(tenantId,row.id,'STATE_REFRESHED',updated.status,{providerState:state.providerState??null});return updated;}catch(error){const updated=await this.repo.updateState(tenantId,{status:'ERROR',lastError:error instanceof Error?error.message:'state failed'});await this.repo.event(tenantId,row.id,'STATE_ERROR',updated.status,{error:updated.lastError});return updated;}}
 async disconnect(tenantId:string){const row=await this.get(tenantId);await this.provider.logout(row.providerInstanceName);const updated=await this.repo.updateState(tenantId,{status:'DISCONNECTED',phoneE164:null,qrExpiresAt:null,lastError:null});await this.repo.event(tenantId,row.id,'DISCONNECTED',updated.status);return updated;}
 async remove(tenantId:string){const row=await this.get(tenantId);await this.provider.remove(row.providerInstanceName);await this.repo.event(tenantId,row.id,'REMOVED','DISABLED');return this.repo.remove(tenantId);}
}
