import { readFileSync } from 'node:fs';
import{WhatsAppInstanceError,type WhatsAppConnectionProvider,type WhatsAppConnectionState,type WhatsAppPairingResult,type WhatsAppStatus}from'./connections.js';
function statusOf(value:unknown):WhatsAppStatus{const s=String(value??'').toLowerCase();if(['open','connected','online'].includes(s))return'CONNECTED';if(['connecting','pairing'].includes(s))return'PAIRING';if(['close','closed','disconnected',''].includes(s))return'DISCONNECTED';return'ERROR';}
function stateValue(payload:any){return payload?.instance?.state??payload?.state??payload?.instance?.status??payload?.status??null;}
export class EvolutionConnectionProvider implements WhatsAppConnectionProvider{
 readonly providerName='EVOLUTION' as const;
 constructor(private readonly baseUrl:string,private readonly apiKey:string){if(!baseUrl||!apiKey)throw new WhatsAppInstanceError('Evolution provider configuration missing','provider_config');}
 private async request(path:string,init:RequestInit={}){const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}${path}`,{...init,headers:{'content-type':'application/json','apikey':this.apiKey,...(init.headers??{})}});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{data={raw:text};}if(!response.ok){const error=new WhatsAppInstanceError(data?.message?.toString?.()??data?.error??`Evolution HTTP ${response.status}`,'provider_http');(error as any).status=response.status;throw error;}return data;}
 async provision(instanceName:string):Promise<WhatsAppConnectionState>{try{const data=await this.request('/instance/create',{method:'POST',body:JSON.stringify({instanceName,qrcode:true,integration:'WHATSAPP-BAILEYS'})});const p=stateValue(data);return{status:statusOf(p),providerState:p};}catch(e){if((e as any)?.status===403||(e as any)?.status===409)return this.state(instanceName);throw e;}}
 async pair(instanceName:string):Promise<WhatsAppPairingResult>{const data=await this.request(`/instance/connect/${encodeURIComponent(instanceName)}`);const qr=data?.base64??data?.qrcode?.base64??data?.qrCode??null;const pairingCode=data?.pairingCode??data?.code??null;const p=stateValue(data);return{status:p?statusOf(p):'PAIRING',qrCode:qr,pairingCode,expiresAt:qr||pairingCode?new Date(Date.now()+60000):null};}
 async state(instanceName:string):Promise<WhatsAppConnectionState>{const data=await this.request(`/instance/connectionState/${encodeURIComponent(instanceName)}`);const p=stateValue(data);const number=data?.instance?.number??data?.number??null;return{status:statusOf(p),providerState:p,phoneE164:number?`+${String(number).replace(/\D/g,'')}`:null};}
 async logout(instanceName:string){await this.request(`/instance/logout/${encodeURIComponent(instanceName)}`,{method:'DELETE'});}
 async remove(instanceName:string){await this.request(`/instance/delete/${encodeURIComponent(instanceName)}`,{method:'DELETE'});}
}
export class UnavailableWhatsAppConnectionProvider implements WhatsAppConnectionProvider{readonly providerName='EVOLUTION' as const;private fail():never{throw new WhatsAppInstanceError('WhatsApp provider is not configured','provider_config');}async provision(){return this.fail();}async pair(){return this.fail();}async state(){return this.fail();}async logout(){this.fail();}async remove(){this.fail();}}
export function createWhatsAppConnectionProviderFromEnv(){const url=process.env.EVOLUTION_BASE_URL;let key=process.env.EVOLUTION_API_KEY;const file=process.env.EVOLUTION_API_KEY_FILE;if(!key&&file){try{key=readFileSync(file,'utf8').trim();}catch{key=undefined;}}return url&&key?new EvolutionConnectionProvider(url,key):new UnavailableWhatsAppConnectionProvider();}
