import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{WhatsAppWebhookIngestionService}from'@wsadmin-business/whatsapp';import{createCustomerCrmRepository,createInboxRepository,createPool,createWhatsAppProviderEventRepository}from'@wsadmin-business/database';
async function main(){const pool=createPool(),t=randomUUID();try{
 await pool.query(`INSERT INTO tenants(id,name,slug) VALUES($1,'CRM Acceptance',$2)`,[t,`crm-${t.slice(0,8)}`]);
 const c=(await pool.query(`INSERT INTO customers(tenant_id,name,phone) VALUES($1,'Sarah','+60123456789') RETURNING id`,[t])).rows[0].id;
 const s=(await pool.query(`INSERT INTO services(tenant_id,name,duration_minutes,price_minor,currency) VALUES($1,'Facial',60,12000,'MYR') RETURNING id`,[t])).rows[0].id;
 const staff=(await pool.query(`INSERT INTO staff_profiles(tenant_id,display_name,booking_capacity) VALUES($1,'Aina',1) RETURNING id`,[t])).rows[0].id;
 await pool.query(`INSERT INTO staff_services(tenant_id,staff_id,service_id) VALUES($1,$2,$3)`,[t,staff,s]);
 await pool.query(`INSERT INTO bookings(tenant_id,customer_id,service_id,staff_id,status,source,assignment_mode,duration_minutes,base_price_minor,option_price_minor,price_minor,currency,starts_at,ends_at,effective_starts_at,effective_ends_at) VALUES($1,$2,$3,$4,'CONFIRMED','ADMIN','REQUESTED',60,12000,0,12000,'MYR','2026-09-01T07:00:00Z','2026-09-01T08:00:00Z','2026-09-01T07:00:00Z','2026-09-01T08:00:00Z')`,[t,c,s,staff]);
 const instanceName=`wsb-${t.replace(/-/g,'').slice(0,24)}`;await pool.query(`INSERT INTO whatsapp_instances(tenant_id,provider,provider_instance_name,display_name,status) VALUES($1,'EVOLUTION',$2,'WSadmin','CONNECTED')`,[t,instanceName]);
 const payload={event:'messages.upsert',instance:instanceName,data:{key:{id:'CRM-MSG-1',remoteJid:'60123456789@s.whatsapp.net',fromMe:false},message:{conversation:'Terima kasih'},messageTimestamp:1787850000,messageType:'conversation'}};
 const ing=await new WhatsAppWebhookIngestionService(createWhatsAppProviderEventRepository(pool)).ingestEvolution(payload);await createInboxRepository(pool).project(ing.record,ing.event);
 const crm=createCustomerCrmRepository(pool);const tg=await crm.createTag(t,'VIP');await crm.setCustomerTags(t,c,[tg.id]);await crm.addNote(t,c,'owner','Prefers afternoon appointments');const fd=await crm.createField(t,{key:'skin_type',label:'Skin Type',fieldType:'TEXT'});await crm.setFieldValue(t,c,fd.id,'Sensitive');await crm.recordEvent(t,c,{eventType:'PAYMENT_RECEIVED',sourceType:'PAYMENT',sourceId:'pay-1',title:'Payment received',detail:{amountMinor:12000,currency:'MYR'}});
 const profile=await crm.profile(t,c);assert.equal(profile.tags[0]?.name,'VIP');assert.equal(profile.customFields[0]?.value,'Sensitive');const types=new Set(profile.timeline.map(x=>x.type));for(const required of['BOOKING','MESSAGE','NOTE','PAYMENT_RECEIVED'])assert.equal(types.has(required),true,`missing ${required}`);const message=profile.timeline.find(x=>x.type==='MESSAGE');assert.equal((message?.detail as any).text,'Terima kasih');console.log(JSON.stringify({status:'PASS',tags:profile.tags.length,fields:profile.customFields.length,timelineTypes:[...types]}));
 }finally{await pool.query('DELETE FROM tenants WHERE id=$1',[t]).catch(()=>undefined);await pool.end();}}
main().catch(e=>{console.error(e);process.exit(1);});
