import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{createBookingRepository,createCustomerControlRepository,createPool}from'@wsadmin-business/database';import{BookingConflictError}from'@wsadmin-business/booking';
async function main(){const pool=createPool();const tenantId=randomUUID();try{
 await pool.query('INSERT INTO tenants(id,name,slug) VALUES($1,$2,$3)',[tenantId,'CRM Merge Acceptance',`crm-${tenantId.slice(0,8)}`]);
 const target=(await pool.query(`INSERT INTO customers(tenant_id,name,phone) VALUES($1,'Target','+60111111111') RETURNING id`,[tenantId])).rows[0].id;
 const source=(await pool.query(`INSERT INTO customers(tenant_id,name,email) VALUES($1,'Source','source@example.test') RETURNING id`,[tenantId])).rows[0].id;
 const tag=(await pool.query(`INSERT INTO customer_tags(tenant_id,name) VALUES($1,'VIP') RETURNING id`,[tenantId])).rows[0].id;await pool.query('INSERT INTO customer_tag_links(tenant_id,customer_id,tag_id) VALUES($1,$2,$3)',[tenantId,source,tag]);await pool.query(`INSERT INTO customer_notes(tenant_id,customer_id,note) VALUES($1,$2,'source note')`,[tenantId,source]);
 const service=(await pool.query(`INSERT INTO services(tenant_id,name,duration_minutes,price_minor,currency) VALUES($1,'CRM Service',60,10000,'MYR') RETURNING id`,[tenantId])).rows[0].id;
 const staff=(await pool.query(`INSERT INTO staff_profiles(tenant_id,display_name) VALUES($1,'CRM Staff') RETURNING id`,[tenantId])).rows[0].id;await pool.query('INSERT INTO staff_services(tenant_id,staff_id,service_id) VALUES($1,$2,$3)',[tenantId,staff,service]);
 const resource=(await pool.query(`INSERT INTO resources(tenant_id,name,type) VALUES($1,'CRM Room','ROOM') RETURNING id`,[tenantId])).rows[0].id;await pool.query('INSERT INTO resource_services(tenant_id,resource_id,service_id) VALUES($1,$2,$3)',[tenantId,resource,service]);
 const bookingRepo=createBookingRepository(pool);const base={tenantId,locationId:null,customerId:source,serviceId:service,staffId:staff,resourceId:resource,status:'CONFIRMED' as const,source:'ADMIN' as const,assignmentMode:'REQUESTED' as const,optionIds:[],durationMinutes:60,basePriceMinor:10000,optionPriceMinor:0,priceMinor:10000,currency:'MYR',notes:null,effectiveStartsAt:new Date('2026-09-01T02:00:00Z'),effectiveEndsAt:new Date('2026-09-01T03:00:00Z'),startsAt:new Date('2026-09-01T02:00:00Z'),endsAt:new Date('2026-09-01T03:00:00Z'),actorUserId:'owner'};await bookingRepo.createWithConflictGuard(base);
 const controls=createCustomerControlRepository(pool);const merged=await controls.merge(tenantId,target,source,'owner');assert.equal(merged.moved.bookings,1);assert.equal(merged.moved.tags,1);assert.equal(merged.moved.notes,1);const moved=await pool.query('SELECT customer_id FROM bookings WHERE tenant_id=$1',[tenantId]);assert.equal(moved.rows[0].customer_id,target);const sourceState=await pool.query('SELECT status,merged_into_customer_id FROM customers WHERE tenant_id=$1 AND id=$2',[tenantId,source]);assert.equal(sourceState.rows[0].status,'ARCHIVED');assert.equal(sourceState.rows[0].merged_into_customer_id,target);
 await controls.setBlacklist(tenantId,target,{blacklisted:true,reason:'repeated no-show',actorUserId:'owner'});let blocked=false;try{await bookingRepo.createWithConflictGuard({...base,customerId:target,source:'WHATSAPP',startsAt:new Date('2026-09-01T04:00:00Z'),endsAt:new Date('2026-09-01T05:00:00Z'),effectiveStartsAt:new Date('2026-09-01T04:00:00Z'),effectiveEndsAt:new Date('2026-09-01T05:00:00Z')});}catch(e){blocked=e instanceof BookingConflictError;}assert.equal(blocked,true);await bookingRepo.createWithConflictGuard({...base,customerId:target,source:'ADMIN',startsAt:new Date('2026-09-01T06:00:00Z'),endsAt:new Date('2026-09-01T07:00:00Z'),effectiveStartsAt:new Date('2026-09-01T06:00:00Z'),effectiveEndsAt:new Date('2026-09-01T07:00:00Z')});
 console.log(JSON.stringify({status:'PASS',merged,blacklistSelfBookingBlocked:blocked,adminOverride:true}));
}finally{await pool.query('DELETE FROM tenants WHERE id=$1',[tenantId]).catch(()=>undefined);await pool.end();}}
main().catch(e=>{console.error(e);process.exit(1);});
