import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';import{createDeliveryRepository,createPool}from'@wsadmin-business/database';import{DeliveryService}from'@wsadmin-business/whatsapp-delivery';
async function main(){const pool=createPool(),tenantId=randomUUID();try{
await pool.query(`insert into tenants(id,name,slug) values($1,'P207 Delivery',$2)`,[tenantId,`p207-${tenantId.slice(0,8)}`]);
const instanceName=`wsb-${tenantId.replaceAll('-','').slice(0,24)}`;const inst=await pool.query(`insert into whatsapp_instances(tenant_id,provider,provider_instance_name,display_name,status) values($1,'EVOLUTION',$2,'WSadmin','CONNECTED') returning id`,[tenantId,instanceName]);
const repo=createDeliveryRepository(pool);let calls=0;const svc=new DeliveryService(repo,()=>({providerName:'EVOLUTION',async sendText(){calls++;if(calls===1){const e:any=new Error('rate limited');e.status=429;throw e;}return{provider:'EVOLUTION',providerMessageId:'provider-m1'};}}),()=>new Date('2026-08-28T00:00:00Z'));
const input={tenantId,instanceId:inst.rows[0].id,provider:'EVOLUTION' as const,providerInstanceName:instanceName,toE164:'+60123456789',textContent:'Hello from queue',idempotencyKey:'p207-one'};const a=await svc.enqueue(input),b=await svc.enqueue(input);assert.equal(a.duplicate,false);assert.equal(b.duplicate,true);
const first=await svc.processOne();assert.equal(first?.status,'RATE_LIMITED');await pool.query(`update whatsapp_outbound_deliveries set next_attempt_at='2026-08-27T23:59:00Z' where id=$1`,[a.delivery.id]);const second=await svc.processOne();assert.equal(second?.status,'SENT');
const row=await pool.query(`select status,attempt_count,provider_message_id from whatsapp_outbound_deliveries where id=$1`,[a.delivery.id]);assert.equal(row.rows[0].status,'SENT');assert.equal(row.rows[0].attempt_count,2);assert.equal(row.rows[0].provider_message_id,'provider-m1');console.log(JSON.stringify({status:'PASS',duplicate:b.duplicate,attempts:row.rows[0].attempt_count,final:row.rows[0].status}));
}finally{await pool.query('delete from tenants where id=$1',[tenantId]).catch(()=>{});await pool.end();}}
main().catch(e=>{console.error(e);process.exit(1)});
