export const TREATMENT_MEDIA_KINDS=['PHOTO','VIDEO','SKETCH','DOCUMENT'] as const;export type TreatmentMediaKind=(typeof TREATMENT_MEDIA_KINDS)[number];export type TreatmentStatus='DRAFT'|'FINAL';
export type TreatmentMedia={id:string;tenantId:string;treatmentRecordId:string;mediaKind:TreatmentMediaKind;storageRef:string;caption:string|null;customerVisible:boolean;createdAt:Date};
export type TreatmentRecord={id:string;tenantId:string;customerId:string;bookingId:string|null;staffId:string|null;serviceId:string|null;occurredAt:Date;summary:string;notes:string|null;status:TreatmentStatus;createdByUserId:string|null;createdAt:Date;updatedAt:Date;media:TreatmentMedia[]};
export type CreateTreatmentInput={customerId:string;bookingId?:string|null;staffId?:string|null;serviceId?:string|null;occurredAt?:Date|string;summary:string;notes?:string|null;status?:TreatmentStatus;media?:Array<{mediaKind:TreatmentMediaKind;storageRef:string;caption?:string|null;customerVisible?:boolean}>};
export interface TreatmentRepository{create(tenantId:string,input:CreateTreatmentInput&{occurredAt:Date;createdByUserId:string|null}):Promise<TreatmentRecord>;get(tenantId:string,id:string):Promise<TreatmentRecord|null>;listCustomer(tenantId:string,customerId:string,limit:number,offset:number):Promise<TreatmentRecord[]>;addMedia(tenantId:string,id:string,input:{mediaKind:TreatmentMediaKind;storageRef:string;caption:string|null;customerVisible:boolean}):Promise<TreatmentMedia>;exportRows(tenantId:string,customerId?:string):Promise<TreatmentRecord[]>;importMany(tenantId:string,rows:Array<CreateTreatmentInput&{occurredAt:Date;createdByUserId:string|null}>):Promise<TreatmentRecord[]>;}
export class TreatmentValidationError extends Error{constructor(message:string){super(message);this.name='TreatmentValidationError';}}export class TreatmentNotFoundError extends Error{constructor(){super('Treatment record not found');this.name='TreatmentNotFoundError';}}
const text=(v:unknown,n:string,m=4000)=>{if(typeof v!=='string'||!v.trim())throw new TreatmentValidationError(`${n} is required`);return v.trim().slice(0,m)};const opt=(v:unknown,m=8000)=>typeof v==='string'&&v.trim()?v.trim().slice(0,m):null;
function media(i:any){if(!TREATMENT_MEDIA_KINDS.includes(i?.mediaKind))throw new TreatmentValidationError('invalid media kind');return{mediaKind:i.mediaKind,storageRef:text(i.storageRef,'storageRef',1000),caption:opt(i.caption,500),customerVisible:Boolean(i.customerVisible)}}
export class TreatmentService{constructor(private readonly repo:TreatmentRepository){}private normalize(i:CreateTreatmentInput,a:string|null){if(!i.customerId?.trim())throw new TreatmentValidationError('customerId is required');const d=i.occurredAt instanceof Date?i.occurredAt:new Date(i.occurredAt??Date.now());if(Number.isNaN(d.valueOf()))throw new TreatmentValidationError('occurredAt must be valid');const status=i.status??'FINAL';if(!['DRAFT','FINAL'].includes(status))throw new TreatmentValidationError('invalid treatment status');return{...i,customerId:i.customerId.trim(),bookingId:i.bookingId??null,staffId:i.staffId??null,serviceId:i.serviceId??null,occurredAt:d,summary:text(i.summary,'summary',500),notes:opt(i.notes),status,media:(i.media??[]).slice(0,20).map(media),createdByUserId:a}}create(t:string,i:CreateTreatmentInput,a:string|null){return this.repo.create(t,this.normalize(i,a));}async get(t:string,id:string){const r=await this.repo.get(t,id);if(!r)throw new TreatmentNotFoundError();return r;}list(t:string,c:string,l=50,o=0){return this.repo.listCustomer(t,c,Math.min(Math.max(l,1),100),Math.max(o,0));}async addMedia(t:string,id:string,i:any){await this.get(t,id);return this.repo.addMedia(t,id,media(i));}async importCsv(t:string,csv:string,a:string|null){const rows=parseTreatmentCsv(csv).map(x=>this.normalize(x,a));return this.repo.importMany(t,rows);}async exportCsv(t:string,c?:string){return treatmentCsv(await this.repo.exportRows(t,c));}}
function parseCsv(input:string){const rows:string[][]=[];let row:string[]=[],cell='',q=false;for(let i=0;i<input.length;i++){const ch=input[i]!;if(q){if(ch==='"'&&input[i+1]==='"'){cell+='"';i++;}else if(ch==='"')q=false;else cell+=ch;}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(q)throw new TreatmentValidationError('unterminated CSV quote');if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows.filter(r=>r.some(v=>v!==''));}
const esc=(v:unknown)=>{const s=v===null||v===undefined?'':String(v);return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};
export function parseTreatmentCsv(csv:string):CreateTreatmentInput[]{if(typeof csv!=='string'||!csv.trim())throw new TreatmentValidationError('CSV is required');const rows=parseCsv(csv);if(rows.length<2)throw new TreatmentValidationError('CSV requires header and rows');if(rows.length>1001)throw new TreatmentValidationError('CSV import limited to 1000 rows');const h=rows[0]!.map(x=>x.trim().toLowerCase()),required=['customer_id','occurred_at','summary'];for(const x of required)if(!h.includes(x))throw new TreatmentValidationError(`CSV missing ${x}`);const col=(r:string[],n:string)=>r[h.indexOf(n)]??'';return rows.slice(1).map((r,idx)=>{let mediaRefs:CreateTreatmentInput['media']=[];const raw=col(r,'media_refs_json');if(raw){try{const x=JSON.parse(raw);if(!Array.isArray(x))throw new Error();mediaRefs=x.map(media);}catch{throw new TreatmentValidationError(`row ${idx+2} invalid media_refs_json`);}}return{customerId:col(r,'customer_id'),bookingId:col(r,'booking_id')||null,staffId:col(r,'staff_id')||null,serviceId:col(r,'service_id')||null,occurredAt:col(r,'occurred_at'),summary:col(r,'summary'),notes:col(r,'notes')||null,status:(col(r,'status')||'FINAL') as TreatmentStatus,media:mediaRefs};});}
export function treatmentCsv(rows:TreatmentRecord[]){const h=['customer_id','booking_id','staff_id','service_id','occurred_at','summary','notes','status','media_refs_json'];const lines=[h.join(',')];for(const r of rows){const m=r.media.map(x=>({mediaKind:x.mediaKind,storageRef:x.storageRef,caption:x.caption,customerVisible:x.customerVisible}));lines.push([r.customerId,r.bookingId??'',r.staffId??'',r.serviceId??'',r.occurredAt.toISOString(),r.summary,r.notes??'',r.status,JSON.stringify(m)].map(esc).join(','));}return lines.join('\n')+'\n';}
