export const AUTOMATION_TRIGGERS=['BOOKING_CONFIRMED','BOOKING_REMINDER','BOOKING_COMPLETED','BIRTHDAY','WINBACK','REVIEW_REQUEST','MANUAL_CAMPAIGN','SURVEY_INVITE'] as const;
export type AutomationTrigger=(typeof AUTOMATION_TRIGGERS)[number];
export const AUTOMATION_JOB_STATUSES=['QUEUED','CLAIMED','DEFERRED','DISPATCHED','SKIPPED','FAILED'] as const;
export type AutomationJobStatus=(typeof AUTOMATION_JOB_STATUSES)[number];
export type AutomationRule={id:string;tenantId:string;name:string;trigger:AutomationTrigger;active:boolean;offsetMinutes:number;config:Record<string,unknown>;createdAt:Date;updatedAt:Date};
export type AutomationJob={id:string;tenantId:string;ruleId:string|null;trigger:AutomationTrigger;triggerKey:string;windowKey:string;dedupeKey:string;customerId:string|null;bookingId:string|null;dueAt:Date;availableAt:Date;status:AutomationJobStatus;attemptCount:number;payload:Record<string,unknown>;lastError:string|null;createdAt:Date;updatedAt:Date};
export type AutomationAudit={id:string;tenantId:string;jobId:string|null;ruleId:string|null;eventType:string;detail:Record<string,unknown>;createdAt:Date};
export interface AutomationRepository{createRule(tenantId:string,input:{name:string;trigger:AutomationTrigger;active:boolean;offsetMinutes:number;config:Record<string,unknown>}):Promise<AutomationRule>;listRules(tenantId:string):Promise<AutomationRule[]>;updateRule(tenantId:string,id:string,input:Partial<Pick<AutomationRule,'name'|'active'|'offsetMinutes'|'config'>>):Promise<AutomationRule|null>;schedule(input:{tenantId:string;ruleId?:string|null;trigger:AutomationTrigger;triggerKey:string;windowKey:string;dedupeKey:string;customerId?:string|null;bookingId?:string|null;dueAt:Date;payload?:Record<string,unknown>}):Promise<{job:AutomationJob;duplicate:boolean}>;claim(now:Date):Promise<AutomationJob|null>;defer(id:string,availableAt:Date,reason:string):Promise<void>;finish(id:string,status:'DISPATCHED'|'SKIPPED'|'FAILED',detail?:Record<string,unknown>):Promise<void>;listAudit(tenantId:string,jobId?:string):Promise<AutomationAudit[]>;}
export class AutomationValidationError extends Error{constructor(message:string){super(message);this.name='AutomationValidationError';}}
function clean(v:string,name:string,max=160){const x=v?.trim();if(!x)throw new AutomationValidationError(`${name} is required`);return x.slice(0,max);}
export class AutomationService{constructor(private readonly repo:AutomationRepository){} createRule(t:string,i:{name:string;trigger:AutomationTrigger;active?:boolean;offsetMinutes?:number;config?:Record<string,unknown>}){if(!AUTOMATION_TRIGGERS.includes(i.trigger))throw new AutomationValidationError('invalid trigger');const offset=i.offsetMinutes??0;if(!Number.isInteger(offset)||offset < -525600 || offset>525600)throw new AutomationValidationError('offsetMinutes out of range');return this.repo.createRule(t,{name:clean(i.name,'name'),trigger:i.trigger,active:i.active??true,offsetMinutes:offset,config:i.config??{}});} listRules(t:string){return this.repo.listRules(t);} updateRule(t:string,id:string,i:any){if(i.offsetMinutes!==undefined&&(!Number.isInteger(i.offsetMinutes)||i.offsetMinutes< -525600||i.offsetMinutes>525600))throw new AutomationValidationError('offsetMinutes out of range');if(i.name!==undefined)i.name=clean(i.name,'name');return this.repo.updateRule(t,id,i);} schedule(i:{tenantId:string;ruleId?:string|null;trigger:AutomationTrigger;triggerKey:string;windowKey:string;customerId?:string|null;bookingId?:string|null;dueAt:Date|string;payload?:Record<string,unknown>}){if(!AUTOMATION_TRIGGERS.includes(i.trigger))throw new AutomationValidationError('invalid trigger');const due=i.dueAt instanceof Date?i.dueAt:new Date(i.dueAt);if(Number.isNaN(due.valueOf()))throw new AutomationValidationError('invalid dueAt');const triggerKey=clean(i.triggerKey,'triggerKey',200),windowKey=clean(i.windowKey,'windowKey',120);const dedupeKey=`${i.ruleId??'system'}:${i.trigger}:${triggerKey}:${windowKey}`;return this.repo.schedule({...i,triggerKey,windowKey,dedupeKey,dueAt:due});} audit(t:string,j?:string){return this.repo.listAudit(t,j);}}
export * from './lifecycle.js';
export * from './dispatcher.js';
export * from './marketing.js';
