import type{AutomationJob}from'./index.js';
export type MessagingPolicy={tenantId:string;timezone:string;quietStartMinute:number;quietEndMinute:number;allowedWeekdays:number[];marketingEnabled:boolean;transactionalEnabled:boolean;maxMessagesPerMinute:number;updatedAt:Date};
export type ChannelPreference={tenantId:string;customerId:string;whatsappEnabled:boolean;marketingOptIn:boolean;optedOutAt:Date|null;updatedAt:Date};
export type PolicyDecision={decision:'ALLOW'|'DEFER'|'BLOCK';reason:string;nextAttemptAt?:Date};
export interface MessagingPolicyRepository{getPolicy(tenantId:string):Promise<MessagingPolicy>;upsertPolicy(tenantId:string,input:Partial<Omit<MessagingPolicy,'tenantId'|'updatedAt'>>):Promise<MessagingPolicy>;getPreference(tenantId:string,customerId:string):Promise<ChannelPreference>;upsertPreference(tenantId:string,customerId:string,input:{whatsappEnabled?:boolean;marketingOptIn?:boolean}):Promise<ChannelPreference>;countRecentDeliveries(tenantId:string,since:Date):Promise<number>;auditDecision(tenantId:string,input:{customerId?:string|null;jobId?:string|null;decision:PolicyDecision['decision'];reason:string;nextAttemptAt?:Date|null}):Promise<void>;}
export interface MessagingPolicyEvaluator{evaluate(job:AutomationJob,now?:Date):Promise<PolicyDecision>}
function parts(d:Date,tz:string){const x=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d),v=(t:string)=>x.find(p=>p.type===t)?.value??'';return{weekday:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(v('weekday')),minute:Number(v('hour'))*60+Number(v('minute'))}}
function quiet(minute:number,start:number,end:number){if(start===end)return false;return start<end?minute>=start&&minute<end:minute>=start||minute<end}
function allowedAt(d:Date,p:MessagingPolicy){const x=parts(d,p.timezone);return p.allowedWeekdays.includes(x.weekday)&&!quiet(x.minute,p.quietStartMinute,p.quietEndMinute)}
function nextAllowed(now:Date,p:MessagingPolicy){for(let i=1;i<=8*1440;i++){const d=new Date(now.getTime()+i*60000);if(allowedAt(d,p))return d}return new Date(now.getTime()+8*86400000)}
export class MessagingPolicyService implements MessagingPolicyEvaluator{constructor(private readonly repo:MessagingPolicyRepository){}async evaluate(job:AutomationJob,now=new Date()){const p=await this.repo.getPolicy(job.tenantId),marketing=(job.payload as any)?.marketing===true;let decision:PolicyDecision;if(marketing&&!p.marketingEnabled)decision={decision:'BLOCK',reason:'marketing_disabled'};else if(!marketing&&!p.transactionalEnabled)decision={decision:'BLOCK',reason:'transactional_disabled'};else{if(job.customerId){const pref=await this.repo.getPreference(job.tenantId,job.customerId);if(!pref.whatsappEnabled)decision={decision:'BLOCK',reason:'customer_whatsapp_opt_out'};else if(marketing&&!pref.marketingOptIn)decision={decision:'BLOCK',reason:'marketing_consent_required'};else decision={decision:'ALLOW',reason:'preference_ok'};}else decision={decision:'ALLOW',reason:'no_customer_preference'};if(decision.decision==='ALLOW'&&!allowedAt(now,p))decision={decision:'DEFER',reason:'quiet_hours_or_delivery_window',nextAttemptAt:nextAllowed(now,p)};if(decision.decision==='ALLOW'){const recent=await this.repo.countRecentDeliveries(job.tenantId,new Date(now.getTime()-60000));if(recent>=p.maxMessagesPerMinute)decision={decision:'DEFER',reason:'tenant_rate_limit',nextAttemptAt:new Date(now.getTime()+60000)};}}await this.repo.auditDecision(job.tenantId,{customerId:job.customerId,jobId:job.id,decision:decision.decision,reason:decision.reason,nextAttemptAt:decision.nextAttemptAt??null});return decision;}}
export function channelPreferenceFromText(text:string){const x=text.trim().toLowerCase();if(['stop','unsubscribe','berhenti','henti','opt out'].includes(x))return'OPT_OUT' as const;if(['start','subscribe','mula','opt in'].includes(x))return'OPT_IN' as const;return null;}
