import type{Pool}from'pg';import{findAvailabilitySlots,type AvailabilityRepository}from'@wsadmin-business/availability';import{BookingService,type BookingRepository}from'@wsadmin-business/booking';import type{AiBusinessTools}from'@wsadmin-business/ai';
function e164(jid:string){const digits=jid.split('@')[0]!.replace(/\D/g,'');return digits?`+${digits}`:jid;}
export function createAiBusinessTools(pool:Pool,availabilityRepo:AvailabilityRepository,bookingRepo:BookingRepository,faq?:{answer(tenantId:string,question:string):Promise<{answer:string;sources:string[]}|null>}):AiBusinessTools{const bookings=new BookingService(availabilityRepo,bookingRepo);return{
 async resolveService(t,name){const r=await pool.query(`SELECT id,name,price_minor,currency FROM services WHERE tenant_id=$1 AND active=true AND (lower(name)=lower($2) OR name ILIKE '%'||$2||'%') ORDER BY (lower(name)=lower($2)) DESC,sort_order,name LIMIT 1`,[t,name]);return r.rowCount?{id:r.rows[0].id,name:r.rows[0].name,priceMinor:Number(r.rows[0].price_minor),currency:r.rows[0].currency}:null;},
 async resolveLocation(t,name){const r=await pool.query(`SELECT id,name FROM locations WHERE tenant_id=$1 AND active=true AND (lower(name)=lower($2) OR name ILIKE '%'||$2||'%') ORDER BY (lower(name)=lower($2)) DESC,sort_order,name LIMIT 1`,[t,name]);return r.rowCount?{id:r.rows[0].id,name:r.rows[0].name}:null;},
 async findSlots(i){const slots=await findAvailabilitySlots(availabilityRepo,{tenantId:i.tenantId,locationId:i.locationId,serviceId:i.serviceId,localDate:i.date,limit:12});const tzq=i.locationId?await pool.query(`SELECT coalesce(l.timezone,t.default_timezone) timezone FROM locations l JOIN tenants t ON t.id=l.tenant_id WHERE l.tenant_id=$1 AND l.id=$2`,[i.tenantId,i.locationId]):await pool.query('SELECT default_timezone timezone FROM tenants WHERE id=$1',[i.tenantId]);const tz=tzq.rows[0]?.timezone??'Asia/Kuala_Lumpur';return slots.map(s=>({startsAt:s.startsAt.toISOString(),label:new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(s.startsAt)}));},
 async createBooking(i){return bookings.create({tenantId:i.tenantId,customerId:i.customerId,serviceId:i.serviceId,locationId:i.locationId,startsAt:i.startsAt,source:'WHATSAPP'});},
 async listUpcoming(t,c){const r=await pool.query(`SELECT b.id,b.service_id,s.name service_name,b.location_id,b.starts_at FROM bookings b JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id WHERE b.tenant_id=$1 AND b.customer_id=$2 AND b.status IN('PENDING','CONFIRMED') AND b.starts_at>=now()-interval '2 hours' ORDER BY b.starts_at LIMIT 20`,[t,c]);return r.rows.map((x:any)=>({id:x.id,serviceId:x.service_id,serviceName:x.service_name,locationId:x.location_id,startsAt:x.starts_at.toISOString()}));},
 async reschedule(t,id,start){return bookings.reschedule({tenantId:t,bookingId:id,startsAt:start,actorUserId:'ai-orchestrator'});},async cancel(t,id){return bookings.cancel(t,id,'ai-orchestrator','customer AI cancellation');},async answerFaq(t,q){return faq?faq.answer(t,q):null;},
 async enqueueReply(i){const inst=await pool.query('SELECT provider,provider_instance_name FROM whatsapp_instances WHERE tenant_id=$1 AND id=$2',[i.tenantId,i.instanceId]);if(!inst.rowCount)throw new Error('WhatsApp instance not found');const r=await pool.query(`INSERT INTO whatsapp_outbound_deliveries(tenant_id,instance_id,conversation_id,provider,provider_instance_name,to_e164,text_content,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id`,[i.tenantId,i.instanceId,i.conversationId,inst.rows[0].provider,inst.rows[0].provider_instance_name,e164(i.toJid),i.text,i.idempotencyKey]);return{id:r.rows[0].id};}
};}
