import type{Pool}from'pg';import{findAvailabilitySlots,type AvailabilityRepository}from'@wsadmin-business/availability';import{BookingService,type BookingRepository}from'@wsadmin-business/booking';import type{AiBusinessTools}from'@wsadmin-business/ai';
import { getBusinessTypeDefinition } from '@wsadmin-business/verticals';
export function deliveryRecipient(jid:string){const value=jid.trim();if(/@g\.us$/i.test(value))return value;const digits=value.split('@')[0]!.replace(/\D/g,'');return digits?`+${digits}`:value;}
export function createAiBusinessTools(pool:Pool,availabilityRepo:AvailabilityRepository,bookingRepo:BookingRepository,faq?:{answer(tenantId:string,question:string):Promise<{answer:string;sources:string[]}|null>}):AiBusinessTools{const bookings=new BookingService(availabilityRepo,bookingRepo);return{
 async getBusinessContext(t){const result=await pool.query(`SELECT business_type,business_subtype,offering_kind,workflow_kind,setup_config FROM businesses WHERE tenant_id=$1 ORDER BY created_at,id LIMIT 1`,[t]);if(!result.rowCount)throw new Error('business context not found');const row=result.rows[0],definition=getBusinessTypeDefinition(row.business_type??'GENERAL'),ai=row.setup_config?.whatsappAi??{};return{businessType:definition.key,businessSubtype:row.business_subtype,offeringKind:row.offering_kind,workflowKind:row.workflow_kind,offeringSingular:definition.labels.offeringSingular,offeringPlural:definition.labels.offeringPlural,transactionSingular:definition.labels.transactionSingular,customerSingular:definition.labels.customerSingular,aiEnabled:ai.aiEnabled!==false};},
 async resolveService(t,name){const r=await pool.query(`SELECT id,name,price_minor,currency FROM services WHERE tenant_id=$1 AND active=true AND (lower(name)=lower($2) OR name ILIKE '%'||$2||'%') ORDER BY (lower(name)=lower($2)) DESC,sort_order,name LIMIT 1`,[t,name]);return r.rowCount?{id:r.rows[0].id,name:r.rows[0].name,priceMinor:Number(r.rows[0].price_minor),currency:r.rows[0].currency}:null;},
 async resolveLocation(t,name){const r=await pool.query(`SELECT id,name FROM locations WHERE tenant_id=$1 AND active=true AND (lower(name)=lower($2) OR name ILIKE '%'||$2||'%') ORDER BY (lower(name)=lower($2)) DESC,sort_order,name LIMIT 1`,[t,name]);return r.rowCount?{id:r.rows[0].id,name:r.rows[0].name}:null;},
 async findSlots(i){const slots=await findAvailabilitySlots(availabilityRepo,{tenantId:i.tenantId,locationId:i.locationId,serviceId:i.serviceId,localDate:i.date,limit:12});const tzq=i.locationId?await pool.query(`SELECT coalesce(l.timezone,t.default_timezone) timezone FROM locations l JOIN tenants t ON t.id=l.tenant_id WHERE l.tenant_id=$1 AND l.id=$2`,[i.tenantId,i.locationId]):await pool.query('SELECT default_timezone timezone FROM tenants WHERE id=$1',[i.tenantId]);const tz=tzq.rows[0]?.timezone??'Asia/Kuala_Lumpur';return slots.map(s=>({startsAt:s.startsAt.toISOString(),label:new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(s.startsAt)}));},
 async createBooking(i){return bookings.create({tenantId:i.tenantId,customerId:i.customerId,serviceId:i.serviceId,locationId:i.locationId,startsAt:i.startsAt,source:'WHATSAPP'});},
 async listUpcoming(t,c){const r=await pool.query(`SELECT b.id,b.service_id,s.name service_name,b.location_id,b.starts_at FROM bookings b JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id WHERE b.tenant_id=$1 AND b.customer_id=$2 AND b.status IN('PENDING','CONFIRMED') AND b.starts_at>=now()-interval '2 hours' ORDER BY b.starts_at LIMIT 20`,[t,c]);return r.rows.map((x:any)=>({id:x.id,serviceId:x.service_id,serviceName:x.service_name,locationId:x.location_id,startsAt:x.starts_at.toISOString()}));},
 async reschedule(t,id,start){return bookings.reschedule({tenantId:t,bookingId:id,startsAt:start,actorUserId:'ai-orchestrator'});},async cancel(t,id){return bookings.cancel(t,id,'ai-orchestrator','customer AI cancellation');},async answerFaq(t,q){return faq?faq.answer(t,q):null;},
 async resolveProperty(t,name){const result=await pool.query(`SELECT p.*,t.default_currency currency FROM properties p JOIN tenants t ON t.id=p.tenant_id WHERE p.tenant_id=$1 AND p.active=true AND (lower(p.name)=lower($2) OR p.name ILIKE '%'||$2||'%' OR lower(p.property_code)=lower($2)) ORDER BY (lower(p.name)=lower($2)) DESC,p.name LIMIT 1`,[t,name]);if(!result.rowCount)return null;const row=result.rows[0];return{id:row.id,name:row.name,weekdayPriceMinor:Number(row.weekday_price_minor),weekendPriceMinor:Number(row.weekend_price_minor),publicHolidayPriceMinor:Number(row.public_holiday_price_minor),depositMinor:Number(row.deposit_minor),currency:row.currency,maxGuests:Number(row.max_guests),amenities:row.features??[],checkInTime:row.check_in_time,checkOutTime:row.check_out_time};},
 async propertyAvailable(t,propertyId,checkIn,checkOut,excludeStayId){const result=await pool.query(`SELECT 1 FROM properties p WHERE p.tenant_id=$1 AND p.id=$2 AND p.active=true AND $3::date<$4::date AND NOT EXISTS(SELECT 1 FROM property_stays s WHERE s.tenant_id=p.tenant_id AND s.property_id=p.id AND s.status IN('PENDING','CONFIRMED') AND ($5::uuid IS NULL OR s.id<>$5::uuid) AND daterange(s.check_in,s.check_out,'[)')&&daterange($3::date,$4::date,'[)'))`,[t,propertyId,checkIn,checkOut,excludeStayId??null]);return Boolean(result.rowCount);},
 async createPropertyStay(input){try{const result=await pool.query(`INSERT INTO property_stays(tenant_id,property_id,customer_id,check_in,check_out,guest_count,status,source) VALUES($1,$2,$3,$4,$5,$6,'CONFIRMED','WHATSAPP') RETURNING id`,[input.tenantId,input.propertyId,input.customerId??null,input.checkIn,input.checkOut,input.guestCount]);return{id:result.rows[0].id};}catch(error:any){if(error?.code==='23P01')throw new Error('property_overlap');throw error;}},
 async listUpcomingStays(t,customerId){const result=await pool.query(`SELECT s.id,s.property_id,p.name property_name,s.check_in,s.check_out FROM property_stays s JOIN properties p ON p.tenant_id=s.tenant_id AND p.id=s.property_id WHERE s.tenant_id=$1 AND s.customer_id=$2 AND s.status IN('PENDING','CONFIRMED') AND s.check_out>=current_date ORDER BY s.check_in,s.id LIMIT 20`,[t,customerId]);return result.rows.map((row:any)=>({id:row.id,propertyId:row.property_id,propertyName:row.property_name,checkIn:String(row.check_in).slice(0,10),checkOut:String(row.check_out).slice(0,10)}));},
 async reschedulePropertyStay(t,stayId,checkIn,checkOut){try{const result=await pool.query(`UPDATE property_stays SET check_in=$3,check_out=$4,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND status IN('PENDING','CONFIRMED') RETURNING id`,[t,stayId,checkIn,checkOut]);if(!result.rowCount)throw new Error('property stay not found');return{id:result.rows[0].id};}catch(error:any){if(error?.code==='23P01')throw new Error('property_overlap');throw error;}},
 async cancelPropertyStay(t,stayId){const result=await pool.query(`UPDATE property_stays SET status='CANCELLED',updated_at=now() WHERE tenant_id=$1 AND id=$2 AND status IN('PENDING','CONFIRMED') RETURNING id`,[t,stayId]);if(!result.rowCount)throw new Error('property stay not found');return{id:result.rows[0].id};},
 async enqueueReply(i){const inst=await pool.query('SELECT provider,provider_instance_name FROM whatsapp_instances WHERE tenant_id=$1 AND id=$2',[i.tenantId,i.instanceId]);if(!inst.rowCount)throw new Error('WhatsApp instance not found');const r=await pool.query(`INSERT INTO whatsapp_outbound_deliveries(tenant_id,instance_id,conversation_id,provider,provider_instance_name,to_e164,text_content,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id`,[i.tenantId,i.instanceId,i.conversationId,inst.rows[0].provider,inst.rows[0].provider_instance_name,deliveryRecipient(i.toJid),i.text,i.idempotencyKey]);return{id:r.rows[0].id};}
};}
