import type{Pool}from'pg';import type{AiKnowledgeRepository,FaqEntry,KnowledgeSource}from'@wsadmin-business/ai';
const faq=(r:any):FaqEntry=>({id:r.id,tenantId:r.tenant_id,question:r.question,answer:r.answer,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
function money(n:number,c:string){return c==='MYR'?`RM${(n/100).toFixed(2)}`:`${c} ${(n/100).toFixed(2)}`;}
export function createAiKnowledgeRepository(pool:Pool):AiKnowledgeRepository{return{
 async search(t,q,limit=8){const term=q.trim();const out:KnowledgeSource[]=[];const faqs=await pool.query(`SELECT * FROM ai_faq_entries WHERE tenant_id=$1 AND active=true AND (question ILIKE '%'||$2||'%' OR answer ILIKE '%'||$2||'%') ORDER BY sort_order,question LIMIT $3`,[t,term,limit]);for(const x of faqs.rows)out.push({id:`faq:${x.id}`,type:'FAQ',title:x.question,content:x.answer});
 const sv=await pool.query(`SELECT id,name,description,duration_minutes,price_minor,currency FROM services WHERE tenant_id=$1 AND active=true AND (name ILIKE '%'||$2||'%' OR coalesce(description,'') ILIKE '%'||$2||'%') ORDER BY sort_order,name LIMIT $3`,[t,term,limit]);for(const x of sv.rows)out.push({id:`service:${x.id}`,type:'SERVICE',title:x.name,content:`Service ${x.name}. Price ${money(Number(x.price_minor),x.currency)}. Duration ${x.duration_minutes} minutes.${x.description?` ${x.description}`:''}`});
 const loc=await pool.query(`SELECT id,name,address,timezone FROM locations WHERE tenant_id=$1 AND active=true AND (name ILIKE '%'||$2||'%' OR coalesce(address,'') ILIKE '%'||$2||'%') ORDER BY sort_order,name LIMIT $3`,[t,term,limit]);for(const x of loc.rows)out.push({id:`location:${x.id}`,type:'LOCATION',title:x.name,content:`Location ${x.name}.${x.address?` Address ${x.address}.`:''}${x.timezone?` Timezone ${x.timezone}.`:''}`});
 const pol=await pool.query('SELECT * FROM booking_policies WHERE tenant_id=$1',[t]);if(pol.rowCount){const x=pol.rows[0];out.push({id:`policy:${t}`,type:'BOOKING_POLICY',title:'Booking policy',content:`Booking horizon ${x.booking_horizon_days} days. Minimum lead ${x.minimum_lead_minutes} minutes. Cancellation deadline ${x.cancellation_deadline_minutes} minutes before appointment.`});}return out.slice(0,limit);},
 async createFaq(t,i){const q=i.question.trim(),a=i.answer.trim();if(!q||!a)throw new Error('faq_question_answer_required');const r=await pool.query(`INSERT INTO ai_faq_entries(tenant_id,question,answer,active,sort_order) VALUES($1,$2,$3,$4,$5) RETURNING *`,[t,q,a,i.active??true,i.sortOrder??0]);return faq(r.rows[0]);},
 async listFaq(t,inc=false){const r=await pool.query('SELECT * FROM ai_faq_entries WHERE tenant_id=$1 AND ($2::boolean OR active=true) ORDER BY sort_order,question',[t,inc]);return r.rows.map(faq);},
 async updateFaq(t,id,i){const cur=await pool.query('SELECT * FROM ai_faq_entries WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];const r=await pool.query(`UPDATE ai_faq_entries SET question=$3,answer=$4,active=$5,sort_order=$6,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,'question'in i?i.question?.trim():x.question,'answer'in i?i.answer?.trim():x.answer,'active'in i?i.active:x.active,'sortOrder'in i?i.sortOrder:x.sort_order]);return faq(r.rows[0]);}
};}
