import type{Pool}from'pg';import type{AutomationAudit,AutomationJob,AutomationRepository,AutomationRule}from'@wsadmin-business/automation';
const rule=(r:any):AutomationRule=>({id:r.id,tenantId:r.tenant_id,name:r.name,trigger:r.trigger,active:r.active,offsetMinutes:r.offset_minutes,config:r.config??{},createdAt:r.created_at,updatedAt:r.updated_at});
const job=(r:any):AutomationJob=>({id:r.id,tenantId:r.tenant_id,ruleId:r.rule_id,trigger:r.trigger,triggerKey:r.trigger_key,windowKey:r.window_key,dedupeKey:r.dedupe_key,customerId:r.customer_id,bookingId:r.booking_id,dueAt:r.due_at,availableAt:r.available_at,status:r.status,attemptCount:r.attempt_count,payload:r.payload??{},lastError:r.last_error,createdAt:r.created_at,updatedAt:r.updated_at});
const audit=(r:any):AutomationAudit=>({id:r.id,tenantId:r.tenant_id,jobId:r.job_id,ruleId:r.rule_id,eventType:r.event_type,detail:r.detail??{},createdAt:r.created_at});
export function createAutomationRepository(pool:Pool):AutomationRepository{return{
 async createRule(t,i){const r=await pool.query(`INSERT INTO automation_rules(tenant_id,name,trigger,active,offset_minutes,config) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *`,[t,i.name,i.trigger,i.active,i.offsetMinutes,JSON.stringify(i.config)]);return rule(r.rows[0]);},
 async listRules(t){const r=await pool.query('SELECT * FROM automation_rules WHERE tenant_id=$1 ORDER BY created_at,id',[t]);return r.rows.map(rule);},
 async updateRule(t,id,i){const cur=await pool.query('SELECT * FROM automation_rules WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];const r=await pool.query(`UPDATE automation_rules SET name=$3,active=$4,offset_minutes=$5,config=$6::jsonb,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,i.name??x.name,i.active??x.active,i.offsetMinutes??x.offset_minutes,JSON.stringify(i.config??x.config)]);return rule(r.rows[0]);},
 async schedule(i){const c=await pool.connect();try{await c.query('BEGIN');const ins=await c.query(`INSERT INTO automation_jobs(tenant_id,rule_id,trigger,trigger_key,window_key,dedupe_key,customer_id,booking_id,due_at,available_at,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,$10::jsonb) ON CONFLICT(tenant_id,dedupe_key) DO NOTHING RETURNING *`,[i.tenantId,i.ruleId??null,i.trigger,i.triggerKey,i.windowKey,i.dedupeKey,i.customerId??null,i.bookingId??null,i.dueAt,JSON.stringify(i.payload??{})]);if(ins.rowCount){const j=job(ins.rows[0]);await c.query(`INSERT INTO automation_audit(tenant_id,job_id,rule_id,event_type,detail) VALUES($1,$2,$3,'SCHEDULED',$4::jsonb)`,[i.tenantId,j.id,j.ruleId,JSON.stringify({dueAt:j.dueAt,trigger:j.trigger,windowKey:j.windowKey})]);await c.query('COMMIT');return{job:j,duplicate:false};}const ex=await c.query('SELECT * FROM automation_jobs WHERE tenant_id=$1 AND dedupe_key=$2',[i.tenantId,i.dedupeKey]);await c.query('COMMIT');return{job:job(ex.rows[0]),duplicate:true};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async claim(now){const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM automation_jobs WHERE status IN('QUEUED','DEFERRED') AND available_at<=$1 ORDER BY available_at,due_at,created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[now]);if(!r.rowCount){await c.query('COMMIT');return null;}const u=await c.query(`UPDATE automation_jobs SET status='CLAIMED',attempt_count=attempt_count+1,claimed_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[r.rows[0].id]);const j=job(u.rows[0]);await c.query(`INSERT INTO automation_audit(tenant_id,job_id,rule_id,event_type,detail) VALUES($1,$2,$3,'CLAIMED',$4::jsonb)`,[j.tenantId,j.id,j.ruleId,JSON.stringify({attempt:j.attemptCount})]);await c.query('COMMIT');return j;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async defer(id,availableAt,reason){const r=await pool.query(`UPDATE automation_jobs SET status='DEFERRED',available_at=$2,last_error=$3,updated_at=now() WHERE id=$1 RETURNING tenant_id,rule_id`,[id,availableAt,reason]);if(r.rowCount)await pool.query(`INSERT INTO automation_audit(tenant_id,job_id,rule_id,event_type,detail) VALUES($1,$2,$3,'DEFERRED',$4::jsonb)`,[r.rows[0].tenant_id,id,r.rows[0].rule_id,JSON.stringify({availableAt,reason})]);},
 async finish(id,status,detail={}){const r=await pool.query(`UPDATE automation_jobs SET status=$2::wsb_automation_job_status,last_error=CASE WHEN $2::text='FAILED' THEN coalesce($3::jsonb->>'error',last_error) ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING tenant_id,rule_id`,[id,status,JSON.stringify(detail)]);if(r.rowCount)await pool.query(`INSERT INTO automation_audit(tenant_id,job_id,rule_id,event_type,detail) VALUES($1,$2,$3,$4,$5::jsonb)`,[r.rows[0].tenant_id,id,r.rows[0].rule_id,status,JSON.stringify(detail)]);},
 async listAudit(t,j){const r=await pool.query('SELECT * FROM automation_audit WHERE tenant_id=$1 AND ($2::uuid IS NULL OR job_id=$2) ORDER BY created_at,id',[t,j??null]);return r.rows.map(audit);}
};}
