import type{Pool}from'pg';import type{BookingMessageContext,CustomerAutomationProfile,DailyCandidate,LifecycleRepository,LifecycleSettings,MessageTemplate,TemplateKey}from'@wsadmin-business/automation';
const template=(r:any):MessageTemplate=>({id:r.id,tenantId:r.tenant_id,templateKey:r.template_key,name:r.name,body:r.body,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at});
const settings=(r:any):LifecycleSettings=>({tenantId:r.tenant_id,confirmationEnabled:r.confirmation_enabled,reminderMinutes:(r.reminder_minutes??[]).map(Number),thankYouDelayMinutes:r.thank_you_delay_minutes,reviewDelayMinutes:r.review_delay_minutes,birthdayEnabled:r.birthday_enabled,winbackDays:r.winback_days,updatedAt:r.updated_at});

const DEFAULT_TEMPLATES=[['BOOKING_CONFIRMATION','Booking confirmation','Hi {{customer_name}}, booking {{service_name}} anda disahkan pada {{booking_time}}.'],['BOOKING_REMINDER','Booking reminder','Reminder: {{service_name}} anda pada {{booking_time}}.'],['THANK_YOU','Thank you','Terima kasih {{customer_name}} kerana datang hari ini.'],['REVIEW_REQUEST','Review request','Hi {{customer_name}}, bagaimana pengalaman anda? Balas mesej ini untuk berkongsi maklum balas.'],['BIRTHDAY','Birthday','Selamat hari lahir {{customer_name}}! Semoga hari anda indah.'],['WINBACK','Win-back','Hi {{customer_name}}, sudah lama tidak berjumpa. Mahu tempah slot baru?']] as const;
async function ensureTemplates(pool:Pool,t:string){for(const [k,n,b] of DEFAULT_TEMPLATES)await pool.query('INSERT INTO message_templates(tenant_id,template_key,name,body) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[t,k,n,b]);}
const profile=(r:any):CustomerAutomationProfile=>({tenantId:r.tenant_id,customerId:r.customer_id,birthday:r.birthday?String(r.birthday).slice(0,10):null,automationOptOut:r.automation_opt_out,updatedAt:r.updated_at});
export function createLifecycleRepository(pool:Pool):LifecycleRepository{return{
 async upsertTemplate(t,k,i){const r=await pool.query(`INSERT INTO message_templates(tenant_id,template_key,name,body,active) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,template_key) DO UPDATE SET name=excluded.name,body=excluded.body,active=excluded.active,updated_at=now() RETURNING *`,[t,k,i.name,i.body,i.active]);return template(r.rows[0]);},
 async listTemplates(t){await ensureTemplates(pool,t);const r=await pool.query('SELECT * FROM message_templates WHERE tenant_id=$1 ORDER BY template_key',[t]);return r.rows.map(template);},
 async getTemplate(t,k){await ensureTemplates(pool,t);const r=await pool.query('SELECT * FROM message_templates WHERE tenant_id=$1 AND template_key=$2',[t,k]);return r.rowCount?template(r.rows[0]):null;},
 async getSettings(t){await pool.query('INSERT INTO automation_lifecycle_settings(tenant_id) VALUES($1) ON CONFLICT DO NOTHING',[t]);const r=await pool.query('SELECT * FROM automation_lifecycle_settings WHERE tenant_id=$1',[t]);return settings(r.rows[0]);},
 async upsertSettings(t,i){const cur=await this.getSettings(t);const r=await pool.query(`UPDATE automation_lifecycle_settings SET confirmation_enabled=$2,reminder_minutes=$3,thank_you_delay_minutes=$4,review_delay_minutes=$5,birthday_enabled=$6,winback_days=$7,updated_at=now() WHERE tenant_id=$1 RETURNING *`,[t,i.confirmationEnabled??cur.confirmationEnabled,i.reminderMinutes??cur.reminderMinutes,i.thankYouDelayMinutes??cur.thankYouDelayMinutes,i.reviewDelayMinutes??cur.reviewDelayMinutes,i.birthdayEnabled??cur.birthdayEnabled,i.winbackDays??cur.winbackDays]);return settings(r.rows[0]);},
 async getCustomerProfile(t,c){const exists=await pool.query('SELECT 1 FROM customers WHERE tenant_id=$1 AND id=$2',[t,c]);if(!exists.rowCount)throw new Error('customer_not_found');await pool.query('INSERT INTO customer_automation_profiles(tenant_id,customer_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[t,c]);const r=await pool.query('SELECT * FROM customer_automation_profiles WHERE tenant_id=$1 AND customer_id=$2',[t,c]);return profile(r.rows[0]);},
 async upsertCustomerProfile(t,c,i){await this.getCustomerProfile(t,c);const r=await pool.query(`UPDATE customer_automation_profiles SET birthday=CASE WHEN $3::boolean THEN $4::date ELSE birthday END,automation_opt_out=coalesce($5,automation_opt_out),updated_at=now() WHERE tenant_id=$1 AND customer_id=$2 RETURNING *`,[t,c,Object.prototype.hasOwnProperty.call(i,'birthday'),i.birthday??null,i.automationOptOut??null]);return profile(r.rows[0]);},
 async getBookingContext(t,b){const r=await pool.query(`SELECT b.id booking_id,b.starts_at,b.ends_at,c.id customer_id,coalesce(c.name,'Customer') customer_name,CASE WHEN c.phone IS NULL THEN NULL WHEN left(c.phone,1)='+' THEN c.phone ELSE '+'||regexp_replace(c.phone,'\\D','','g') END phone_e164,s.name service_name,wi.id instance_id,wi.provider,wi.provider_instance_name,(SELECT wc.id FROM whatsapp_conversations wc WHERE wc.tenant_id=b.tenant_id AND wc.customer_id=c.id ORDER BY wc.updated_at DESC LIMIT 1) conversation_id FROM bookings b JOIN customers c ON c.tenant_id=b.tenant_id AND c.id=b.customer_id JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id JOIN whatsapp_instances wi ON wi.tenant_id=b.tenant_id AND wi.status='CONNECTED' WHERE b.tenant_id=$1 AND b.id=$2 AND c.status='ACTIVE' AND c.phone IS NOT NULL`,[t,b]);if(!r.rowCount)return null;const x=r.rows[0];return{tenantId:t,bookingId:x.booking_id,customerId:x.customer_id,customerName:x.customer_name,phoneE164:x.phone_e164,serviceName:x.service_name,startsAt:x.starts_at,endsAt:x.ends_at,instanceId:x.instance_id,provider:x.provider,providerInstanceName:x.provider_instance_name,conversationId:x.conversation_id} satisfies BookingMessageContext;},
 async listDailyCandidates(t,date,days){const r=await pool.query(`WITH wi AS (SELECT * FROM whatsapp_instances WHERE tenant_id=$1 AND status='CONNECTED' LIMIT 1),last_visit AS (SELECT customer_id,max(ends_at) last_end FROM bookings WHERE tenant_id=$1 AND status='COMPLETED' GROUP BY customer_id) SELECT c.id customer_id,coalesce(c.name,'Customer') customer_name,CASE WHEN left(c.phone,1)='+' THEN c.phone ELSE '+'||regexp_replace(c.phone,'\\D','','g') END phone_e164,wi.id instance_id,wi.provider,wi.provider_instance_name,(SELECT wc.id FROM whatsapp_conversations wc WHERE wc.tenant_id=c.tenant_id AND wc.customer_id=c.id ORDER BY wc.updated_at DESC LIMIT 1) conversation_id,'BIRTHDAY' kind FROM customers c JOIN customer_automation_profiles cap ON cap.tenant_id=c.tenant_id AND cap.customer_id=c.id CROSS JOIN wi WHERE c.tenant_id=$1 AND c.status='ACTIVE' AND c.phone IS NOT NULL AND cap.birthday IS NOT NULL AND extract(month from cap.birthday)=extract(month from $2::date) AND extract(day from cap.birthday)=extract(day from $2::date) UNION ALL SELECT c.id,coalesce(c.name,'Customer'),CASE WHEN left(c.phone,1)='+' THEN c.phone ELSE '+'||regexp_replace(c.phone,'\\D','','g') END,wi.id,wi.provider,wi.provider_instance_name,(SELECT wc.id FROM whatsapp_conversations wc WHERE wc.tenant_id=c.tenant_id AND wc.customer_id=c.id ORDER BY wc.updated_at DESC LIMIT 1),'WINBACK' FROM customers c JOIN last_visit lv ON lv.customer_id=c.id CROSS JOIN wi WHERE c.tenant_id=$1 AND c.status='ACTIVE' AND c.phone IS NOT NULL AND lv.last_end <= ($2::date - make_interval(days=>$3))`,[t,date,days]);return r.rows.map((x:any):DailyCandidate=>({customerId:x.customer_id,customerName:x.customer_name,phoneE164:x.phone_e164,instanceId:x.instance_id,provider:x.provider,providerInstanceName:x.provider_instance_name,conversationId:x.conversation_id,kind:x.kind}));}
};}
