import type{Pool}from'pg';import type{CustomerCrmProfile,CustomerCrmRepository,CustomerCustomFieldValue,CustomerNote,CustomerTag,CustomerTimelineItem,CustomFieldDefinition}from'@wsadmin-business/customers';
const tag=(r:any):CustomerTag=>({id:r.id,tenantId:r.tenant_id,name:r.name,createdAt:r.created_at});
const note=(r:any):CustomerNote=>({id:r.id,tenantId:r.tenant_id,customerId:r.customer_id,actorUserId:r.actor_user_id,note:r.note,createdAt:r.created_at,updatedAt:r.updated_at});
const field=(r:any):CustomFieldDefinition=>({id:r.id,tenantId:r.tenant_id,key:r.key,label:r.label,fieldType:r.field_type,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
const value=(r:any):CustomerCustomFieldValue=>({definitionId:r.definition_id,key:r.key,label:r.label,fieldType:r.field_type,value:r.value,updatedAt:r.updated_at});
const event=(r:any):CustomerTimelineItem=>({id:r.id,type:r.event_type,sourceType:r.source_type,sourceId:r.source_id,title:r.title,detail:r.detail??{},occurredAt:r.occurred_at});
export function createCustomerCrmRepository(pool:Pool):CustomerCrmRepository{return{
 async createTag(t,n){const r=await pool.query(`INSERT INTO customer_tags(tenant_id,name) VALUES($1,$2) ON CONFLICT(tenant_id,lower(name)) DO UPDATE SET name=excluded.name RETURNING *`,[t,n]);return tag(r.rows[0]);},
 async listTags(t){const r=await pool.query('SELECT * FROM customer_tags WHERE tenant_id=$1 ORDER BY name',[t]);return r.rows.map(tag);},
 async setCustomerTags(t,c,ids){const client=await pool.connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM customers WHERE tenant_id=$1 AND id=$2',[t,c]);if(!exists.rowCount)throw new Error('customer_not_found');await client.query('DELETE FROM customer_tag_links WHERE tenant_id=$1 AND customer_id=$2',[t,c]);for(const id of ids)await client.query('INSERT INTO customer_tag_links(tenant_id,customer_id,tag_id) VALUES($1,$2,$3)',[t,c,id]);const r=await client.query(`SELECT ct.* FROM customer_tags ct JOIN customer_tag_links l ON l.tenant_id=ct.tenant_id AND l.tag_id=ct.id WHERE l.tenant_id=$1 AND l.customer_id=$2 ORDER BY ct.name`,[t,c]);await client.query('COMMIT');return r.rows.map(tag);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}},
 async addNote(t,c,a,n){const r=await pool.query('INSERT INTO customer_notes(tenant_id,customer_id,actor_user_id,note) VALUES($1,$2,$3,$4) RETURNING *',[t,c,a,n]);return note(r.rows[0]);},
 async listNotes(t,c,l){const r=await pool.query('SELECT * FROM customer_notes WHERE tenant_id=$1 AND customer_id=$2 ORDER BY created_at DESC,id DESC LIMIT $3',[t,c,l]);return r.rows.map(note);},
 async createField(t,i){const r=await pool.query(`INSERT INTO customer_custom_field_definitions(tenant_id,key,label,field_type,active,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[t,i.key,i.label,i.fieldType,i.active??true,i.sortOrder??0]);return field(r.rows[0]);},
 async listFields(t,inc=false){const r=await pool.query('SELECT * FROM customer_custom_field_definitions WHERE tenant_id=$1 AND ($2::boolean OR active=true) ORDER BY sort_order,label',[t,inc]);return r.rows.map(field);},
 async setFieldValue(t,c,d,v){const def=await pool.query('SELECT * FROM customer_custom_field_definitions WHERE tenant_id=$1 AND id=$2 AND active=true',[t,d]);if(!def.rowCount)throw new Error('field_not_found');const r=await pool.query(`INSERT INTO customer_custom_field_values(tenant_id,customer_id,definition_id,value) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(tenant_id,customer_id,definition_id) DO UPDATE SET value=excluded.value,updated_at=now() RETURNING *`,[t,c,d,JSON.stringify(v)]);return value({...r.rows[0],...def.rows[0],definition_id:d,value:r.rows[0].value,updated_at:r.rows[0].updated_at});},
 async timeline(t,c,l,o){const r=await pool.query(`
  SELECT id::text,event_type,source_type,source_id,title,detail,occurred_at FROM customer_activity_events WHERE tenant_id=$1 AND customer_id=$2
  UNION ALL SELECT n.id::text,'NOTE','NOTE',n.id::text,'Customer note',jsonb_build_object('note',n.note,'actorUserId',n.actor_user_id),n.created_at FROM customer_notes n WHERE n.tenant_id=$1 AND n.customer_id=$2
  UNION ALL SELECT b.id::text,'BOOKING','BOOKING',b.id::text,'Booking '||s.name,jsonb_build_object('status',b.status,'source',b.source,'startsAt',b.starts_at,'priceMinor',b.price_minor,'currency',b.currency,'staffId',b.staff_id,'resourceId',b.resource_id,'locationId',b.location_id),b.created_at FROM bookings b JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id WHERE b.tenant_id=$1 AND b.customer_id=$2
  UNION ALL SELECT m.id::text,'MESSAGE','WHATSAPP_MESSAGE',m.id::text,CASE WHEN m.direction='INBOUND' THEN 'WhatsApp inbound' ELSE 'WhatsApp outbound' END,jsonb_build_object('direction',m.direction,'text',m.text_content,'messageType',m.message_type,'status',m.status,'mediaKind',m.media_kind),m.occurred_at FROM whatsapp_messages m JOIN whatsapp_conversations wc ON wc.tenant_id=m.tenant_id AND wc.id=m.conversation_id WHERE wc.tenant_id=$1 AND wc.customer_id=$2
  UNION ALL SELECT a.id::text,'AI_ACTION','AI',a.id::text,'AI '||a.action,jsonb_build_object('intent',a.intent,'confidence',a.confidence,'reason',a.reason,'toolResult',a.tool_result),a.created_at FROM ai_action_audit a JOIN whatsapp_conversations wc ON wc.tenant_id=a.tenant_id AND wc.id=a.conversation_id WHERE wc.tenant_id=$1 AND wc.customer_id=$2
  ORDER BY occurred_at DESC,id DESC LIMIT $3 OFFSET $4`,[t,c,l,o]);return r.rows.map(event);},
 async profile(t,c){const exists=await pool.query('SELECT 1 FROM customers WHERE tenant_id=$1 AND id=$2',[t,c]);if(!exists.rowCount)throw new Error('customer_not_found');const[tagRows,noteRows,fieldRows,timelineRows]=await Promise.all([
  pool.query(`SELECT ct.* FROM customer_tags ct JOIN customer_tag_links l ON l.tenant_id=ct.tenant_id AND l.tag_id=ct.id WHERE l.tenant_id=$1 AND l.customer_id=$2 ORDER BY ct.name`,[t,c]),
  pool.query('SELECT * FROM customer_notes WHERE tenant_id=$1 AND customer_id=$2 ORDER BY created_at DESC,id DESC LIMIT 50',[t,c]),
  pool.query(`SELECT d.id definition_id,d.key,d.label,d.field_type,v.value,v.updated_at FROM customer_custom_field_definitions d JOIN customer_custom_field_values v ON v.tenant_id=d.tenant_id AND v.definition_id=d.id WHERE d.tenant_id=$1 AND v.customer_id=$2 AND d.active=true ORDER BY d.sort_order,d.label`,[t,c]),
  this.timeline(t,c,100,0)]);
  return{tags:tagRows.rows.map(tag),notes:noteRows.rows.map(note),customFields:fieldRows.rows.map(value),timeline:timelineRows} satisfies CustomerCrmProfile;},
 async recordEvent(t,c,i){const r=await pool.query(`INSERT INTO customer_activity_events(tenant_id,customer_id,event_type,source_type,source_id,title,detail,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8) RETURNING *`,[t,c,i.eventType,i.sourceType,i.sourceId??null,i.title,JSON.stringify(i.detail??{}),i.occurredAt??new Date()]);return event(r.rows[0]);}
};}
