import type{Pool,PoolClient}from'pg';import type{CustomerControlRepository,CustomerMergeResult,CustomerRestrictionState}from'@wsadmin-business/customers';
const state=(r:any):CustomerRestrictionState=>({customerId:r.id,blacklisted:r.blacklisted,reason:r.blacklist_reason,blacklistedAt:r.blacklisted_at,mergedIntoCustomerId:r.merged_into_customer_id,mergedAt:r.merged_at});
async function move(c:PoolClient,sql:string,args:any[]){const r=await c.query(sql,args);return r.rowCount??0;}
export function createCustomerControlRepository(pool:Pool):CustomerControlRepository{return{
 async getRestriction(t,c){const r=await pool.query('SELECT id,blacklisted,blacklist_reason,blacklisted_at,merged_into_customer_id,merged_at FROM customers WHERE tenant_id=$1 AND id=$2',[t,c]);return r.rowCount?state(r.rows[0]):null;},
 async setBlacklist(t,c,i){const r=await pool.query(`UPDATE customers SET blacklisted=$3,blacklist_reason=CASE WHEN $3 THEN $4 ELSE NULL END,blacklisted_at=CASE WHEN $3 THEN coalesce(blacklisted_at,now()) ELSE NULL END,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,blacklisted,blacklist_reason,blacklisted_at,merged_into_customer_id,merged_at`,[t,c,i.blacklisted,i.reason]);if(!r.rowCount)return null;await pool.query(`INSERT INTO customer_activity_events(tenant_id,customer_id,event_type,source_type,title,detail) VALUES($1,$2,$3,'CRM',$4,$5::jsonb)`,[t,c,i.blacklisted?'BLACKLISTED':'BLACKLIST_REMOVED',i.blacklisted?'Customer blacklisted':'Customer blacklist removed',JSON.stringify({reason:i.reason,actorUserId:i.actorUserId})]);return state(r.rows[0]);},
 async merge(t,target,source,actor){const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM customers WHERE tenant_id=$1 AND id=ANY($2::uuid[]) FOR UPDATE',[t,[target,source]]);if(q.rowCount!==2)throw new Error('customer_not_found');const targetRow=q.rows.find((x:any)=>x.id===target),sourceRow=q.rows.find((x:any)=>x.id===source);if(sourceRow.merged_into_customer_id)throw new Error('customer_already_merged');
  const tags=await move(c,`INSERT INTO customer_tag_links(tenant_id,customer_id,tag_id) SELECT tenant_id,$2,tag_id FROM customer_tag_links WHERE tenant_id=$1 AND customer_id=$3 ON CONFLICT DO NOTHING`,[t,target,source]);
  await c.query('DELETE FROM customer_tag_links WHERE tenant_id=$1 AND customer_id=$2',[t,source]);
  const fields=await move(c,`INSERT INTO customer_custom_field_values(tenant_id,customer_id,definition_id,value,updated_at) SELECT tenant_id,$2,definition_id,value,updated_at FROM customer_custom_field_values WHERE tenant_id=$1 AND customer_id=$3 ON CONFLICT DO NOTHING`,[t,target,source]);
  await c.query('DELETE FROM customer_custom_field_values WHERE tenant_id=$1 AND customer_id=$2',[t,source]);
  const bookings=await move(c,'UPDATE bookings SET customer_id=$2 WHERE tenant_id=$1 AND customer_id=$3',[t,target,source]);
  const conversations=await move(c,'UPDATE whatsapp_conversations SET customer_id=$2,updated_at=now() WHERE tenant_id=$1 AND customer_id=$3',[t,target,source]);
  const treatments=await move(c,'UPDATE treatment_records SET customer_id=$2,updated_at=now() WHERE tenant_id=$1 AND customer_id=$3',[t,target,source]);
  const notes=await move(c,'UPDATE customer_notes SET customer_id=$2,updated_at=now() WHERE tenant_id=$1 AND customer_id=$3',[t,target,source]);
  const events=await move(c,'UPDATE customer_activity_events SET customer_id=$2 WHERE tenant_id=$1 AND customer_id=$3',[t,target,source]);
  await c.query(`UPDATE customers SET name=coalesce(name,'Merged customer'),phone=NULL,email=NULL,status='ARCHIVED',merged_into_customer_id=$3,merged_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2`,[t,source,target]);
  const tr=await c.query(`UPDATE customers SET name=coalesce(name,$3),phone=coalesce(phone,$4),email=coalesce(email,$5),blacklisted=(blacklisted OR $6::boolean),blacklist_reason=CASE WHEN blacklist_reason IS NOT NULL THEN blacklist_reason WHEN $6 THEN $7 ELSE NULL END,blacklisted_at=CASE WHEN blacklisted THEN blacklisted_at WHEN $6 THEN coalesce($8,now()) ELSE NULL END,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id`,[t,target,sourceRow.name,sourceRow.phone,sourceRow.email,sourceRow.blacklisted,sourceRow.blacklist_reason,sourceRow.blacklisted_at]);
  if(!tr.rowCount)throw new Error('customer_not_found');const mergedAt=new Date();const detail={bookings,conversations,treatments,notes,events,tags,customFields:fields};
  await c.query(`INSERT INTO customer_merge_history(tenant_id,source_customer_id,target_customer_id,actor_user_id,detail,created_at) VALUES($1,$2,$3,$4,$5::jsonb,$6)`,[t,source,target,actor,JSON.stringify(detail),mergedAt]);
  await c.query(`INSERT INTO customer_activity_events(tenant_id,customer_id,event_type,source_type,source_id,title,detail,occurred_at) VALUES($1,$2,'CUSTOMER_MERGED','CRM',$3,'Customer records merged',$4::jsonb,$5)`,[t,target,source,JSON.stringify({sourceCustomerId:source,...detail,actorUserId:actor}),mergedAt]);
  await c.query('COMMIT');return{sourceCustomerId:source,targetCustomerId:target,moved:detail,mergedAt} satisfies CustomerMergeResult;
 }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
};}
