import type { Pool } from 'pg';
import type { BusinessReportSnapshot,DashboardBookingItem,DashboardLocationItem,DashboardRepository,DashboardSnapshot,ReportDailyPoint } from '@wsadmin-business/dashboard';
function localDates(from:string,to:string){const out:string[]=[];for(let cursor=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);cursor<=end;cursor=new Date(cursor.getTime()+86400000))out.push(cursor.toISOString().slice(0,10));return out;}
export function createDashboardRepository(pool:Pool):DashboardRepository{return{
  async snapshot(tenantId:string,localDate?:string,locationId?:string):Promise<DashboardSnapshot>{
    const tenant=await pool.query(`SELECT t.default_timezone,l.timezone AS location_timezone FROM tenants t LEFT JOIN locations l ON l.tenant_id=t.id AND l.id=$2::uuid WHERE t.id=$1`,[tenantId,locationId??null]);
    const timezone=tenant.rows[0]?.location_timezone??tenant.rows[0]?.default_timezone??'Asia/Kuala_Lumpur';
    const dateRow=await pool.query(`SELECT coalesce($2::date,(now() AT TIME ZONE $1)::date)::text AS local_date, (coalesce($2::date,(now() AT TIME ZONE $1)::date)::timestamp AT TIME ZONE $1) AS range_start, ((coalesce($2::date,(now() AT TIME ZONE $1)::date)+1)::timestamp AT TIME ZONE $1) AS range_end, extract(dow from coalesce($2::date,(now() AT TIME ZONE $1)::date))::int AS weekday`,[timezone,localDate??null]);
    const d=dateRow.rows[0];
    const summary=await pool.query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE status='PENDING')::int AS pending,count(*) FILTER(WHERE status='CONFIRMED')::int AS confirmed,count(*) FILTER(WHERE status='COMPLETED')::int AS completed,count(*) FILTER(WHERE status='CANCELLED')::int AS cancelled,count(*) FILTER(WHERE status='NO_SHOW')::int AS no_show,coalesce(sum(extract(epoch from (ends_at-starts_at))/60) FILTER(WHERE status<>'CANCELLED'),0)::int AS booked_minutes FROM bookings WHERE tenant_id=$1 AND starts_at<$3 AND $2<ends_at AND ($4::uuid IS NULL OR location_id=$4::uuid)`,[tenantId,d.range_start,d.range_end,locationId??null]);
    const s=summary.rows[0];
    const scheduled=await pool.query(`WITH active_staff AS (SELECT id FROM staff_profiles WHERE tenant_id=$1 AND active=true AND ($4::uuid IS NULL OR EXISTS(SELECT 1 FROM staff_locations sl WHERE sl.tenant_id=staff_profiles.tenant_id AND sl.staff_id=staff_profiles.id AND sl.location_id=$4::uuid))) SELECT count(*)::int AS active_staff,coalesce(sum(CASE WHEN o.cnt>0 THEN o.minutes ELSE coalesce(w.minutes,0) END),0)::int AS scheduled_minutes FROM active_staff sp LEFT JOIN LATERAL (SELECT count(*)::int AS cnt,CASE WHEN bool_or(is_off) THEN 0 ELSE coalesce(sum(end_minute-start_minute) FILTER(WHERE is_off=false),0) END::int AS minutes FROM staff_shift_overrides WHERE tenant_id=$1 AND staff_id=sp.id AND local_date=$2::date) o ON true LEFT JOIN LATERAL (SELECT coalesce(sum(end_minute-start_minute),0)::int AS minutes FROM staff_working_hours WHERE tenant_id=$1 AND staff_id=sp.id AND weekday=$3) w ON true`,[tenantId,d.local_date,d.weekday,locationId??null]);
    const sch=scheduled.rows[0];
    const recentRows=await pool.query(`SELECT b.id,b.status,b.starts_at,b.ends_at,c.name AS customer_name,sv.name AS service_name,sp.display_name AS staff_name,r.name AS resource_name FROM bookings b LEFT JOIN customers c ON c.tenant_id=b.tenant_id AND c.id=b.customer_id JOIN services sv ON sv.tenant_id=b.tenant_id AND sv.id=b.service_id JOIN staff_profiles sp ON sp.tenant_id=b.tenant_id AND sp.id=b.staff_id LEFT JOIN resources r ON r.tenant_id=b.tenant_id AND r.id=b.resource_id WHERE b.tenant_id=$1 AND b.starts_at<$3 AND $2<b.ends_at AND ($4::uuid IS NULL OR b.location_id=$4::uuid) ORDER BY b.starts_at,b.id LIMIT 12`,[tenantId,d.range_start,d.range_end,locationId??null]);
    const recent:DashboardBookingItem[]=recentRows.rows.map((r:any)=>({id:r.id,status:r.status,startsAt:r.starts_at,endsAt:r.ends_at,customerName:r.customer_name,serviceName:r.service_name,staffName:r.staff_name,resourceName:r.resource_name}));
    const byLocationRows=await pool.query(`SELECT b.location_id,coalesce(l.name,'Unassigned') AS location_name,count(*)::int AS total,count(*) FILTER(WHERE b.status='CONFIRMED')::int AS confirmed,count(*) FILTER(WHERE b.status='PENDING')::int AS pending,count(*) FILTER(WHERE b.status='CANCELLED')::int AS cancelled FROM bookings b LEFT JOIN locations l ON l.tenant_id=b.tenant_id AND l.id=b.location_id WHERE b.tenant_id=$1 AND b.starts_at<$3 AND $2<b.ends_at AND ($4::uuid IS NULL OR b.location_id=$4::uuid) GROUP BY b.location_id,l.name ORDER BY l.name NULLS LAST`,[tenantId,d.range_start,d.range_end,locationId??null]);
    const byLocation:DashboardLocationItem[]=byLocationRows.rows.map((x:any)=>({locationId:x.location_id,locationName:x.location_name,totalBookings:x.total,confirmed:x.confirmed,pending:x.pending,cancelled:x.cancelled}));
    const bookedMinutes=Number(s.booked_minutes??0),scheduledMinutes=Number(sch.scheduled_minutes??0);
    const percentage=scheduledMinutes>0?Math.round((bookedMinutes/scheduledMinutes)*10000)/100:0;
    const pending=Number(s.pending??0),noShow=Number(s.no_show??0);
    return{
      tenantId,locationId:locationId??null,localDate:d.local_date,timezone,rangeStart:d.range_start,rangeEnd:d.range_end,
      bookings:{total:Number(s.total??0),pending,confirmed:Number(s.confirmed??0),completed:Number(s.completed??0),cancelled:Number(s.cancelled??0),noShow},
      utilization:{activeStaff:Number(sch.active_staff??0),bookedMinutes,scheduledMinutes,percentage},
      pendingActions:{pendingBookings:pending,noShows:noShow,attentionCount:pending+noShow},recent,byLocation
    };
  },
  async report(tenantId:string,from:string,to:string):Promise<BusinessReportSnapshot>{
    const tenant=await pool.query('SELECT default_timezone,default_currency FROM tenants WHERE id=$1',[tenantId]);
    const timezone=tenant.rows[0]?.default_timezone??'Asia/Kuala_Lumpur',currency=tenant.rows[0]?.default_currency??'MYR';
    const bounds=(await pool.query(`SELECT ($2::date::timestamp AT TIME ZONE $1) AS range_start,(($3::date+1)::timestamp AT TIME ZONE $1) AS range_end`,[timezone,from,to])).rows[0];
    const [bookingResult,scheduledResult,paymentResult,customerResult,automationResult,aiResult,bookingDailyResult,paymentDailyResult]=await Promise.all([
      pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='PENDING')::int pending,count(*) FILTER(WHERE status='CONFIRMED')::int confirmed,count(*) FILTER(WHERE status='COMPLETED')::int completed,count(*) FILTER(WHERE status='CANCELLED')::int cancelled,count(*) FILTER(WHERE status='NO_SHOW')::int no_show,coalesce(sum(extract(epoch from (ends_at-starts_at))/60) FILTER(WHERE status NOT IN('CANCELLED','NO_SHOW')),0)::int booked_minutes FROM bookings WHERE tenant_id=$1 AND starts_at<$3 AND $2<ends_at`,[tenantId,bounds.range_start,bounds.range_end]),
      pool.query(`WITH days AS(SELECT generate_series($2::date,$3::date,interval '1 day')::date local_date),active_staff AS(SELECT id FROM staff_profiles WHERE tenant_id=$1 AND active=true) SELECT count(DISTINCT sp.id)::int active_staff,coalesce(sum(CASE WHEN o.cnt>0 THEN o.minutes ELSE coalesce(w.minutes,0) END),0)::int scheduled_minutes FROM active_staff sp CROSS JOIN days d LEFT JOIN LATERAL(SELECT count(*)::int cnt,CASE WHEN bool_or(is_off) THEN 0 ELSE coalesce(sum(end_minute-start_minute) FILTER(WHERE is_off=false),0) END::int minutes FROM staff_shift_overrides WHERE tenant_id=$1 AND staff_id=sp.id AND local_date=d.local_date)o ON true LEFT JOIN LATERAL(SELECT coalesce(sum(end_minute-start_minute),0)::int minutes FROM staff_working_hours WHERE tenant_id=$1 AND staff_id=sp.id AND weekday=extract(dow from d.local_date)::int)w ON true`,[tenantId,from,to]),
      pool.query(`SELECT coalesce(sum(amount_minor) FILTER(WHERE status IN('PAID','PARTIALLY_REFUNDED','REFUNDED')),0)::bigint gross_minor,coalesce(sum(refunded_minor) FILTER(WHERE status IN('PARTIALLY_REFUNDED','REFUNDED')),0)::bigint refunded_minor,count(*) FILTER(WHERE status IN('PAID','PARTIALLY_REFUNDED','REFUNDED'))::int paid_count FROM payments WHERE tenant_id=$1 AND paid_at>=$2 AND paid_at<$3`,[tenantId,bounds.range_start,bounds.range_end]),
      pool.query(`WITH engaged AS(SELECT customer_id,count(*)::int completed_count FROM bookings WHERE tenant_id=$1 AND customer_id IS NOT NULL AND status='COMPLETED' AND ends_at>=$2 AND ends_at<$3 GROUP BY customer_id) SELECT count(*) FILTER(WHERE status<>'ARCHIVED')::int total,count(*) FILTER(WHERE status<>'ARCHIVED' AND created_at>=$2 AND created_at<$3)::int new_customers,(SELECT count(*)::int FROM engaged)::int engaged_customers,(SELECT count(*)::int FROM engaged WHERE completed_count>=2)::int repeat_customers FROM customers WHERE tenant_id=$1`,[tenantId,bounds.range_start,bounds.range_end]),
      pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status IN('QUEUED','CLAIMED','DEFERRED'))::int queued,count(*) FILTER(WHERE status='DISPATCHED')::int dispatched,count(*) FILTER(WHERE status='SKIPPED')::int skipped,count(*) FILTER(WHERE status='FAILED')::int failed FROM automation_jobs WHERE tenant_id=$1 AND created_at>=$2 AND created_at<$3`,[tenantId,bounds.range_start,bounds.range_end]),
      pool.query(`SELECT count(*)::int requests,count(*) FILTER(WHERE success=true)::int successful,count(*) FILTER(WHERE success=false)::int failed,coalesce(sum(input_tokens),0)::bigint input_tokens,coalesce(sum(output_tokens),0)::bigint output_tokens,coalesce(avg(latency_ms),0)::numeric latency_avg FROM ai_usage_logs WHERE tenant_id=$1 AND created_at>=$2 AND created_at<$3`,[tenantId,bounds.range_start,bounds.range_end]),
      pool.query(`SELECT (starts_at AT TIME ZONE $4)::date::text local_date,count(*)::int bookings,count(*) FILTER(WHERE status='COMPLETED')::int completed FROM bookings WHERE tenant_id=$1 AND starts_at>=$2 AND starts_at<$3 GROUP BY 1 ORDER BY 1`,[tenantId,bounds.range_start,bounds.range_end,timezone]),
      pool.query(`SELECT (paid_at AT TIME ZONE $4)::date::text local_date,coalesce(sum(amount_minor) FILTER(WHERE status IN('PAID','PARTIALLY_REFUNDED','REFUNDED')),0)::bigint revenue_minor,coalesce(sum(refunded_minor) FILTER(WHERE status IN('PARTIALLY_REFUNDED','REFUNDED')),0)::bigint refunded_minor FROM payments WHERE tenant_id=$1 AND paid_at>=$2 AND paid_at<$3 GROUP BY 1 ORDER BY 1`,[tenantId,bounds.range_start,bounds.range_end,timezone])
    ]);
    const b=bookingResult.rows[0],s=scheduledResult.rows[0],p=paymentResult.rows[0],c=customerResult.rows[0],a=automationResult.rows[0],ai=aiResult.rows[0];
    const bookingDaily=new Map(bookingDailyResult.rows.map((row:any)=>[row.local_date,row])),paymentDaily=new Map(paymentDailyResult.rows.map((row:any)=>[row.local_date,row]));
    const daily:ReportDailyPoint[]=localDates(from,to).map(localDate=>{const booking:any=bookingDaily.get(localDate),payment:any=paymentDaily.get(localDate);return{localDate,bookings:Number(booking?.bookings??0),completed:Number(booking?.completed??0),revenueMinor:Number(payment?.revenue_minor??0),refundedMinor:Number(payment?.refunded_minor??0)};});
    const bookedMinutes=Number(b.booked_minutes??0),scheduledMinutes=Number(s.scheduled_minutes??0),grossMinor=Number(p.gross_minor??0),refundedMinor=Number(p.refunded_minor??0),engagedCustomers=Number(c.engaged_customers??0),repeatCustomers=Number(c.repeat_customers??0);
    return{tenantId,from,to,timezone,currency,
      bookings:{total:Number(b.total??0),pending:Number(b.pending??0),confirmed:Number(b.confirmed??0),completed:Number(b.completed??0),cancelled:Number(b.cancelled??0),noShow:Number(b.no_show??0)},
      revenue:{grossMinor,refundedMinor,netMinor:grossMinor-refundedMinor,paidCount:Number(p.paid_count??0)},
      utilization:{activeStaff:Number(s.active_staff??0),bookedMinutes,scheduledMinutes,percentage:scheduledMinutes?Math.round(bookedMinutes/scheduledMinutes*10000)/100:0},
      customers:{total:Number(c.total??0),newCustomers:Number(c.new_customers??0),engagedCustomers,repeatCustomers,repeatRatePercentage:engagedCustomers?Math.round(repeatCustomers/engagedCustomers*10000)/100:0},
      automation:{total:Number(a.total??0),queued:Number(a.queued??0),dispatched:Number(a.dispatched??0),skipped:Number(a.skipped??0),failed:Number(a.failed??0)},
      ai:{requests:Number(ai.requests??0),successful:Number(ai.successful??0),failed:Number(ai.failed??0),inputTokens:Number(ai.input_tokens??0),outputTokens:Number(ai.output_tokens??0),latencyAvgMs:Math.round(Number(ai.latency_avg??0))},daily};
  }
};}
