import type{Pool}from'pg';import{contactE164,type Conversation,type ConversationSearch,type InboxMessage,type InboxRepository}from'@wsadmin-business/inbox';import type{NormalizedWhatsAppEvent,WhatsAppProviderEventRecord}from'@wsadmin-business/whatsapp';
const convo=(r:any):Conversation=>({id:r.id,tenantId:r.tenant_id,instanceId:r.instance_id,customerId:r.customer_id,channel:r.channel,remoteJid:r.remote_jid,contactE164:r.contact_e164,displayName:r.display_name,status:r.status,unreadCount:r.unread_count,lastMessageAt:r.last_message_at,lastMessagePreview:r.last_message_preview,aiIntent:r.ai_intent??null,aiConfidence:r.ai_confidence===null||r.ai_confidence===undefined?null:Number(r.ai_confidence),aiAction:r.ai_action??null,aiReason:r.ai_reason??null,aiAttentionState:r.ai_attention_state??'NONE',aiUpdatedAt:r.ai_updated_at??null,createdAt:r.created_at,updatedAt:r.updated_at});
const msg=(r:any):InboxMessage=>({id:r.id,tenantId:r.tenant_id,conversationId:r.conversation_id,providerEventId:r.provider_event_id,providerMessageId:r.provider_message_id,direction:r.direction,senderJid:r.sender_jid,messageType:r.message_type,textContent:r.text_content,occurredAt:r.occurred_at,status:r.status,createdAt:r.created_at});
export function createInboxRepository(pool:Pool):InboxRepository{return{
 async project(record:WhatsAppProviderEventRecord,event:NormalizedWhatsAppEvent){const m=event.message;if(!m?.remoteJid){await pool.query('UPDATE whatsapp_provider_events SET processed_at=coalesce(processed_at,now()) WHERE tenant_id=$1 AND id=$2',[record.tenantId,record.id]);return null;}const c=await pool.connect();try{await c.query('BEGIN');
  const phone=contactE164(event);let customerId:string|null=null,customerName:string|null=null;
  if(phone){await c.query(`INSERT INTO customers(tenant_id,phone,locale) VALUES($1,$2,'ms-MY') ON CONFLICT(tenant_id,phone) WHERE phone IS NOT NULL DO NOTHING`,[record.tenantId,phone]);const cq=await c.query('SELECT id,name FROM customers WHERE tenant_id=$1 AND phone=$2 LIMIT 1',[record.tenantId,phone]);customerId=cq.rows[0]?.id??null;customerName=cq.rows[0]?.name??null;}
  const cv=await c.query(`INSERT INTO whatsapp_conversations(tenant_id,instance_id,customer_id,remote_jid,contact_e164,display_name,status) VALUES($1,$2,$3,$4,$5,$6,'OPEN') ON CONFLICT(tenant_id,instance_id,remote_jid) DO UPDATE SET customer_id=coalesce(whatsapp_conversations.customer_id,excluded.customer_id),contact_e164=coalesce(whatsapp_conversations.contact_e164,excluded.contact_e164),display_name=coalesce(whatsapp_conversations.display_name,excluded.display_name),status=CASE WHEN whatsapp_conversations.status='CLOSED' THEN 'OPEN'::wsb_conversation_status ELSE whatsapp_conversations.status END,updated_at=now() RETURNING *`,[record.tenantId,record.instanceId,customerId,m.remoteJid,phone,customerName]);
  const conversation=convo(cv.rows[0]);const occurredAt=event.occurredAt??record.receivedAt;const direction=m.fromMe===true?'OUTBOUND':'INBOUND';const sender=m.fromMe===true?null:(m.participant??m.remoteJid);
  const ins=await c.query(`INSERT INTO whatsapp_messages(tenant_id,conversation_id,provider_event_id,provider_message_id,direction,sender_jid,message_type,text_content,occurred_at,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(tenant_id,provider_event_id) DO NOTHING RETURNING *`,[record.tenantId,conversation.id,record.id,m.providerMessageId,direction,sender,m.messageType,m.text,occurredAt,direction==='INBOUND'?'RECEIVED':'SENT']);
  let message:InboxMessage;if(ins.rowCount){message=msg(ins.rows[0]);await c.query(`UPDATE whatsapp_conversations SET unread_count=unread_count+$3,last_message_at=CASE WHEN last_message_at IS NULL OR last_message_at<=$4 THEN $4 ELSE last_message_at END,last_message_preview=CASE WHEN last_message_at IS NULL OR last_message_at<=$4 THEN $5 ELSE last_message_preview END,updated_at=now() WHERE tenant_id=$1 AND id=$2`,[record.tenantId,conversation.id,direction==='INBOUND'?1:0,occurredAt,m.text?.slice(0,240)??`[${m.messageType??'message'}]`]);}else{const existing=await c.query('SELECT * FROM whatsapp_messages WHERE tenant_id=$1 AND provider_event_id=$2',[record.tenantId,record.id]);message=msg(existing.rows[0]);}
  await c.query('UPDATE whatsapp_provider_events SET processed_at=coalesce(processed_at,now()) WHERE tenant_id=$1 AND id=$2',[record.tenantId,record.id]);const fresh=await c.query('SELECT * FROM whatsapp_conversations WHERE tenant_id=$1 AND id=$2',[record.tenantId,conversation.id]);await c.query('COMMIT');return{conversation:convo(fresh.rows[0]),message};
 }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async listConversations(t,q:ConversationSearch){const term=q.q?.trim()??'';const r=await pool.query(`SELECT * FROM whatsapp_conversations WHERE tenant_id=$1 AND ($2::text IS NULL OR status=$2::wsb_conversation_status) AND ($3='' OR coalesce(display_name,'') ILIKE '%'||$3||'%' OR coalesce(contact_e164,'') ILIKE '%'||$3||'%' OR remote_jid ILIKE '%'||$3||'%') ORDER BY last_message_at DESC NULLS LAST,updated_at DESC LIMIT $4 OFFSET $5`,[t,q.status??null,term,q.limit??50,q.offset??0]);return r.rows.map(convo);},
 async getConversation(t,id){const r=await pool.query('SELECT * FROM whatsapp_conversations WHERE tenant_id=$1 AND id=$2',[t,id]);return r.rowCount?convo(r.rows[0]):null;},
 async listMessages(t,id,limit,offset){const r=await pool.query('SELECT * FROM whatsapp_messages WHERE tenant_id=$1 AND conversation_id=$2 ORDER BY occurred_at DESC,id DESC LIMIT $3 OFFSET $4',[t,id,limit,offset]);return r.rows.map(msg);},
 async updateStatus(t,id,status){const r=await pool.query('UPDATE whatsapp_conversations SET status=$3,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *',[t,id,status]);return r.rowCount?convo(r.rows[0]):null;},
 async markRead(t,id){const r=await pool.query('UPDATE whatsapp_conversations SET unread_count=0,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *',[t,id]);return r.rowCount?convo(r.rows[0]):null;},
 async recordAiState(t,id,i){const r=await pool.query(`UPDATE whatsapp_conversations SET ai_intent=$3,ai_confidence=$4,ai_action=$5,ai_reason=$6,ai_attention_state=$7,ai_updated_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,i.intent,i.confidence,i.action,i.reason,i.attentionState]);return r.rowCount?convo(r.rows[0]):null;}
};}
