import type{Pool,PoolClient}from'pg';import{LocationValidationError,type Location,type LocationRepository,type UpdateLocationInput}from'@wsadmin-business/locations';
const map=(r:any):Location=>({id:r.id,tenantId:r.tenant_id,businessId:r.business_id,name:r.name,code:r.code,timezone:r.timezone,address:r.address,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
function translate(e:unknown):never{if(typeof e==='object'&&e&&'code'in e){const c=(e as any).code;if(c==='23505')throw new LocationValidationError('location code/name conflict');if(c==='23503')throw new LocationValidationError('business/staff/service does not belong to tenant');}throw e;}
async function replace(c:PoolClient,table:string,column:string,t:string,l:string,ids:string[]){await c.query(`DELETE FROM ${table} WHERE tenant_id=$1 AND location_id=$2`,[t,l]);for(const id of ids)await c.query(`INSERT INTO ${table}(tenant_id,location_id,${column}) VALUES($1,$2,$3)`,[t,l,id]);return ids;}
export function createLocationRepository(pool:Pool):LocationRepository{return{
 async create(t,i){try{const r=await pool.query(`INSERT INTO locations(tenant_id,business_id,name,code,timezone,address,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[t,i.businessId,i.name,i.code,i.timezone??null,i.address??null,i.active??true,i.sortOrder??0]);return map(r.rows[0]);}catch(e){return translate(e);}},
 async get(t,id){const r=await pool.query('SELECT * FROM locations WHERE tenant_id=$1 AND id=$2',[t,id]);return r.rowCount?map(r.rows[0]):null;},
 async list(t,inc=false){const r=await pool.query('SELECT * FROM locations WHERE tenant_id=$1 AND ($2::boolean OR active=true) ORDER BY sort_order,name',[t,inc]);return r.rows.map(map);},
 async update(t,id,i:UpdateLocationInput){const cur=await pool.query('SELECT * FROM locations WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];try{const r=await pool.query(`UPDATE locations SET name=$3,code=$4,timezone=$5,address=$6,active=$7,sort_order=$8,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,'name'in i?i.name:x.name,'code'in i?i.code:x.code,'timezone'in i?i.timezone:x.timezone,'address'in i?i.address:x.address,'active'in i?i.active:x.active,'sortOrder'in i?i.sortOrder:x.sort_order]);return map(r.rows[0]);}catch(e){return translate(e);}},
 async setStaff(t,l,ids){const c=await pool.connect();try{await c.query('BEGIN');const out=await replace(c,'staff_locations','staff_id',t,l,ids);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');return translate(e);}finally{c.release();}},
 async setServices(t,l,ids){const c=await pool.connect();try{await c.query('BEGIN');const out=await replace(c,'service_locations','service_id',t,l,ids);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');return translate(e);}finally{c.release();}},
 async getStaff(t,l){const r=await pool.query('SELECT staff_id FROM staff_locations WHERE tenant_id=$1 AND location_id=$2 ORDER BY staff_id',[t,l]);return r.rows.map(x=>x.staff_id as string);},
 async getServices(t,l){const r=await pool.query('SELECT service_id FROM service_locations WHERE tenant_id=$1 AND location_id=$2 ORDER BY service_id',[t,l]);return r.rows.map(x=>x.service_id as string);}
};}
