import type{Pool}from'pg';import type{CampaignCandidate,CampaignSegment,CustomerSurvey,MarketingCampaign,MarketingRepository,SurveyContext}from'@wsadmin-business/automation';
const campaign=(r:any):MarketingCampaign=>({id:r.id,tenantId:r.tenant_id,name:r.name,body:r.body,segment:r.segment??{},status:r.status,scheduledAt:r.scheduled_at,createdByUserId:r.created_by_user_id,createdAt:r.created_at,updatedAt:r.updated_at});
const survey=(r:any):CustomerSurvey=>({id:r.id,tenantId:r.tenant_id,bookingId:r.booking_id,customerId:r.customer_id,status:r.status,questions:r.questions??[],expiresAt:r.expires_at,createdAt:r.created_at,completedAt:r.completed_at});
export function createMarketingRepository(pool:Pool):MarketingRepository{return{
 async createCampaign(t,i){const r=await pool.query(`INSERT INTO marketing_campaigns(tenant_id,name,body,segment,scheduled_at,created_by_user_id) VALUES($1,$2,$3,$4::jsonb,$5,$6) RETURNING *`,[t,i.name,i.body,JSON.stringify(i.segment),i.scheduledAt??null,i.createdByUserId??null]);return campaign(r.rows[0]);},
 async getCampaign(t,id){const r=await pool.query('SELECT * FROM marketing_campaigns WHERE tenant_id=$1 AND id=$2',[t,id]);return r.rowCount?campaign(r.rows[0]):null;},
 async listCampaigns(t){const r=await pool.query('SELECT * FROM marketing_campaigns WHERE tenant_id=$1 ORDER BY created_at DESC,id DESC',[t]);return r.rows.map(campaign);},
 async selectCandidates(t,s:CampaignSegment){const tags=s.tagIds?.length?s.tagIds:null,min=s.minCompletedBookings??0;const r=await pool.query(`WITH stats AS (SELECT customer_id,count(*) FILTER(WHERE status='COMPLETED')::int completed_count,max(ends_at) FILTER(WHERE status='COMPLETED') last_visit FROM bookings WHERE tenant_id=$1 GROUP BY customer_id),wi AS (SELECT * FROM whatsapp_instances WHERE tenant_id=$1 AND status='CONNECTED' LIMIT 1) SELECT c.id customer_id,coalesce(c.name,'Customer') customer_name,CASE WHEN left(c.phone,1)='+' THEN c.phone ELSE '+'||regexp_replace(c.phone,'\\D','','g') END phone_e164,wi.id instance_id,wi.provider,wi.provider_instance_name,(SELECT wc.id FROM whatsapp_conversations wc WHERE wc.tenant_id=c.tenant_id AND wc.customer_id=c.id ORDER BY wc.updated_at DESC LIMIT 1) conversation_id FROM customers c CROSS JOIN wi LEFT JOIN stats st ON st.customer_id=c.id LEFT JOIN customer_automation_profiles cap ON cap.tenant_id=c.tenant_id AND cap.customer_id=c.id WHERE c.tenant_id=$1 AND c.status='ACTIVE' AND c.phone IS NOT NULL AND coalesce(cap.automation_opt_out,false)=false AND coalesce(st.completed_count,0)>=$3 AND ($2::uuid[] IS NULL OR EXISTS(SELECT 1 FROM customer_tag_links l WHERE l.tenant_id=c.tenant_id AND l.customer_id=c.id AND l.tag_id=ANY($2::uuid[]))) AND ($4::date IS NULL OR st.last_visit >= $4::date) AND ($5::date IS NULL OR st.last_visit < ($5::date + interval '1 day')) ORDER BY c.id`,[t,tags,min,s.lastVisitAfter??null,s.lastVisitBefore??null]);return r.rows.map((x:any):CampaignCandidate=>({customerId:x.customer_id,customerName:x.customer_name,phoneE164:x.phone_e164,instanceId:x.instance_id,provider:x.provider,providerInstanceName:x.provider_instance_name,conversationId:x.conversation_id}));},
 async recordRecipient(t,c,customer,job,status,reason=null){await pool.query(`INSERT INTO marketing_campaign_recipients(tenant_id,campaign_id,customer_id,status,automation_job_id,reason) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,campaign_id,customer_id) DO UPDATE SET status=excluded.status,automation_job_id=excluded.automation_job_id,reason=excluded.reason`,[t,c,customer,status,job,reason]);},
 async updateCampaignStatus(t,id,status){await pool.query('UPDATE marketing_campaigns SET status=$3,updated_at=now() WHERE tenant_id=$1 AND id=$2',[t,id,status]);},
 async getSurveyContext(t,b){const r=await pool.query(`SELECT b.id booking_id,c.id customer_id,coalesce(c.name,'Customer') customer_name,CASE WHEN left(c.phone,1)='+' THEN c.phone ELSE '+'||regexp_replace(c.phone,'\\D','','g') END phone_e164,wi.id instance_id,wi.provider,wi.provider_instance_name,(SELECT wc.id FROM whatsapp_conversations wc WHERE wc.tenant_id=c.tenant_id AND wc.customer_id=c.id ORDER BY wc.updated_at DESC LIMIT 1) conversation_id FROM bookings b JOIN customers c ON c.tenant_id=b.tenant_id AND c.id=b.customer_id JOIN whatsapp_instances wi ON wi.tenant_id=b.tenant_id AND wi.status='CONNECTED' WHERE b.tenant_id=$1 AND b.id=$2 AND c.status='ACTIVE' AND c.phone IS NOT NULL`,[t,b]);if(!r.rowCount)return null;const x=r.rows[0];return{bookingId:x.booking_id,customerId:x.customer_id,customerName:x.customer_name,phoneE164:x.phone_e164,instanceId:x.instance_id,provider:x.provider,providerInstanceName:x.provider_instance_name,conversationId:x.conversation_id} satisfies SurveyContext;},
 async createSurvey(t,i){const r=await pool.query(`INSERT INTO customer_surveys(tenant_id,booking_id,customer_id,token_hash,questions,expires_at) VALUES($1,$2,$3,$4,$5::jsonb,$6) RETURNING *`,[t,i.bookingId,i.customerId,i.tokenHash,JSON.stringify(i.questions),i.expiresAt]);return survey(r.rows[0]);},
 async listSurveys(t){const r=await pool.query('SELECT * FROM customer_surveys WHERE tenant_id=$1 ORDER BY created_at DESC,id DESC',[t]);return r.rows.map(survey);},
 async getSurveyByTokenHash(h){const r=await pool.query('SELECT * FROM customer_surveys WHERE token_hash=$1',[h]);return r.rowCount?survey(r.rows[0]):null;},
 async submitSurvey(h,answers){const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query(`SELECT * FROM customer_surveys WHERE token_hash=$1 FOR UPDATE`,[h]);if(!q.rowCount||q.rows[0].status!=='OPEN'||q.rows[0].expires_at<=new Date()){await c.query('ROLLBACK');return null;}await c.query(`INSERT INTO customer_survey_responses(survey_id,answers) VALUES($1,$2::jsonb)`,[q.rows[0].id,JSON.stringify(answers)]);const u=await c.query(`UPDATE customer_surveys SET status='COMPLETED',completed_at=now() WHERE id=$1 RETURNING *`,[q.rows[0].id]);await c.query('COMMIT');return survey(u.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
};}
