import type{Pool}from'pg';import type{ChannelPreference,MessagingPolicy,MessagingPolicyRepository}from'@wsadmin-business/automation';
const policy=(r:any):MessagingPolicy=>({tenantId:r.tenant_id,timezone:r.timezone,quietStartMinute:r.quiet_start_minute,quietEndMinute:r.quiet_end_minute,allowedWeekdays:(r.allowed_weekdays??[]).map(Number),marketingEnabled:r.marketing_enabled,transactionalEnabled:r.transactional_enabled,maxMessagesPerMinute:r.max_messages_per_minute,updatedAt:r.updated_at});
const pref=(r:any):ChannelPreference=>({tenantId:r.tenant_id,customerId:r.customer_id,whatsappEnabled:r.whatsapp_enabled,marketingOptIn:r.marketing_opt_in,optedOutAt:r.opted_out_at,updatedAt:r.updated_at});
export function createMessagingPolicyRepository(pool:Pool):MessagingPolicyRepository{return{
 async getPolicy(t){await pool.query(`INSERT INTO tenant_messaging_policies(tenant_id,timezone) SELECT id,default_timezone FROM tenants WHERE id=$1 ON CONFLICT DO NOTHING`,[t]);const r=await pool.query('SELECT * FROM tenant_messaging_policies WHERE tenant_id=$1',[t]);if(!r.rowCount)throw new Error('tenant_not_found');return policy(r.rows[0]);},
 async upsertPolicy(t,i){const cur=await this.getPolicy(t);const r=await pool.query(`UPDATE tenant_messaging_policies SET timezone=$2,quiet_start_minute=$3,quiet_end_minute=$4,allowed_weekdays=$5::smallint[],marketing_enabled=$6,transactional_enabled=$7,max_messages_per_minute=$8,updated_at=now() WHERE tenant_id=$1 RETURNING *`,[t,i.timezone??cur.timezone,i.quietStartMinute??cur.quietStartMinute,i.quietEndMinute??cur.quietEndMinute,i.allowedWeekdays??cur.allowedWeekdays,i.marketingEnabled??cur.marketingEnabled,i.transactionalEnabled??cur.transactionalEnabled,i.maxMessagesPerMinute??cur.maxMessagesPerMinute]);return policy(r.rows[0]);},
 async getPreference(t,c){const exists=await pool.query('SELECT 1 FROM customers WHERE tenant_id=$1 AND id=$2',[t,c]);if(!exists.rowCount)throw new Error('customer_not_found');await pool.query('INSERT INTO customer_channel_preferences(tenant_id,customer_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[t,c]);const r=await pool.query('SELECT * FROM customer_channel_preferences WHERE tenant_id=$1 AND customer_id=$2',[t,c]);return pref(r.rows[0]);},
 async upsertPreference(t,c,i){const cur=await this.getPreference(t,c),nextWa=i.whatsappEnabled??cur.whatsappEnabled,nextMarketing=i.marketingOptIn??cur.marketingOptIn;const r=await pool.query(`UPDATE customer_channel_preferences SET whatsapp_enabled=$3,marketing_opt_in=$4,opted_out_at=CASE WHEN $3=false THEN coalesce(opted_out_at,now()) ELSE NULL END,updated_at=now() WHERE tenant_id=$1 AND customer_id=$2 RETURNING *`,[t,c,nextWa,nextMarketing]);return pref(r.rows[0]);},
 async countRecentDeliveries(t,since){const r=await pool.query(`SELECT count(*)::int count FROM whatsapp_outbound_deliveries WHERE tenant_id=$1 AND created_at>=$2`,[t,since]);return Number(r.rows[0]?.count??0);},
 async auditDecision(t,i){await pool.query(`INSERT INTO messaging_policy_audit(tenant_id,customer_id,automation_job_id,decision,reason,next_attempt_at) VALUES($1,$2,$3,$4,$5,$6)`,[t,i.customerId??null,i.jobId??null,i.decision,i.reason,i.nextAttemptAt??null]);}
};}
