import type { Pool,PoolClient } from 'pg';
import { ResourceConflictError,type Resource,type ResourceRepository,type ResourceSearch,type UpdateResourceInput } from '@wsadmin-business/resources';
const map=(r:any):Resource=>({id:r.id,tenantId:r.tenant_id,name:r.name,type:r.type,capacity:r.capacity,active:r.active,sortOrder:r.sort_order,description:r.description,createdAt:r.created_at,updatedAt:r.updated_at});
function translate(e:unknown):never{if(typeof e==='object'&&e&&'code'in e){const c=(e as any).code;if(c==='23505')throw new ResourceConflictError('resource name already exists for this tenant');if(c==='23503')throw new ResourceConflictError('resource or service does not belong to tenant');}throw e;}
async function replaceServices(client:PoolClient,t:string,r:string,ids:string[]){await client.query('DELETE FROM resource_services WHERE tenant_id=$1 AND resource_id=$2',[t,r]);for(const id of ids)await client.query('INSERT INTO resource_services(tenant_id,resource_id,service_id) VALUES($1,$2,$3)',[t,r,id]);return ids;}
export function createResourceRepository(pool:Pool):ResourceRepository{return{
  async create(t,i){try{const r=await pool.query(`INSERT INTO resources(tenant_id,name,type,capacity,active,sort_order,description) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[t,i.name,i.type,i.capacity??1,i.active??true,i.sortOrder??0,i.description??null]);return map(r.rows[0]);}catch(e){return translate(e);}},
  async get(t,id){const r=await pool.query('SELECT * FROM resources WHERE tenant_id=$1 AND id=$2',[t,id]);return r.rowCount?map(r.rows[0]):null;},
  async search(t,q:ResourceSearch){const term=q.q?.trim()??'';const r=await pool.query(`SELECT r.* FROM resources r WHERE r.tenant_id=$1 AND ($2::text IS NULL OR r.type=$2::wsb_resource_type) AND ($3::text IS NULL OR r.active=$3::boolean) AND ($4='' OR r.name ILIKE '%'||$4||'%' OR coalesce(r.description,'') ILIKE '%'||$4||'%') AND ($5::uuid IS NULL OR EXISTS(SELECT 1 FROM resource_services rs WHERE rs.tenant_id=r.tenant_id AND rs.resource_id=r.id AND rs.service_id=$5::uuid)) ORDER BY r.sort_order,r.name LIMIT $6 OFFSET $7`,[t,q.type??null,q.active===undefined?null:q.active,term,q.serviceId??null,q.limit??50,q.offset??0]);return r.rows.map(map);},
  async update(t,id,i:UpdateResourceInput){const cur=await pool.query('SELECT * FROM resources WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];try{const r=await pool.query(`UPDATE resources SET name=$3,type=$4,capacity=$5,active=$6,sort_order=$7,description=$8,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,'name'in i?i.name:x.name,'type'in i?i.type:x.type,'capacity'in i?i.capacity:x.capacity,'active'in i?i.active:x.active,'sortOrder'in i?i.sortOrder:x.sort_order,'description'in i?i.description:x.description]);return map(r.rows[0]);}catch(e){return translate(e);}},
  async setServices(t,r,ids){const c=await pool.connect();try{await c.query('BEGIN');const exists=await c.query('SELECT 1 FROM resources WHERE tenant_id=$1 AND id=$2',[t,r]);if(!exists.rowCount)throw new Error('resource_not_found');const out=await replaceServices(c,t,r,ids);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');if(e instanceof Error&&e.message==='resource_not_found')throw e;return translate(e);}finally{c.release();}},
  async getServices(t,r){const rows=await pool.query('SELECT service_id FROM resource_services WHERE tenant_id=$1 AND resource_id=$2 ORDER BY service_id',[t,r]);return rows.rows.map(x=>x.service_id as string);},
  async isCompatible(t,r,s){const row=await pool.query('SELECT 1 FROM resource_services rs JOIN resources r ON r.tenant_id=rs.tenant_id AND r.id=rs.resource_id JOIN services sv ON sv.tenant_id=rs.tenant_id AND sv.id=rs.service_id WHERE rs.tenant_id=$1 AND rs.resource_id=$2 AND rs.service_id=$3 AND r.active=true AND sv.active=true',[t,r,s]);return Boolean(row.rowCount);}
};}
