import type { Pool } from 'pg';
import { SaasError, type BillingCheckout, type BillingInvoice, type BillingProviderEvent, type BillingSummary, type Plan, type SaasBillingRepository, type Subscription, type SubscriptionStatus } from '@wsadmin-business/saas';

const plan=(r:any):Plan=>({id:r.id,code:r.code,name:r.name,monthlyPriceMinor:Number(r.monthly_price_minor),currency:r.currency,entitlements:r.entitlements??{},active:r.active});
const checkout=(r:any):BillingCheckout=>({id:r.id,tenantId:r.tenant_id,planCode:r.plan_code,provider:r.provider,reference:r.reference,providerSubscriptionId:r.provider_subscription_id,status:r.status,checkoutUrl:r.checkout_url,amountMinor:Number(r.amount_minor),currency:r.currency,customerEmail:r.customer_email,createdByUserId:r.created_by_user_id,lastError:r.last_error,createdAt:r.created_at,updatedAt:r.updated_at});
const invoice=(r:any):BillingInvoice=>({id:r.id,tenantId:r.tenant_id,checkoutId:r.checkout_id,provider:r.provider,providerChargeId:r.provider_charge_id,amountMinor:Number(r.amount_minor),currency:r.currency,status:r.status,paidAt:r.paid_at,createdAt:r.created_at});
const subscription=(r:any):Subscription=>({tenantId:r.tenant_id,planCode:r.plan_code,status:r.status,trialEndsAt:r.trial_ends_at,currentPeriodEndsAt:r.current_period_ends_at,cancelAtPeriodEnd:r.cancel_at_period_end,updatedAt:r.updated_at});

export function createSaasBillingRepository(pool:Pool):SaasBillingRepository{return{
  async getPlan(code){const r=await pool.query('SELECT * FROM saas_plans WHERE code=$1',[code]);return r.rowCount?plan(r.rows[0]):null;},
  async createBillingCheckout(input){try{const r=await pool.query(`WITH generated AS(SELECT gen_random_uuid() id) INSERT INTO saas_billing_checkouts(id,tenant_id,plan_code,provider,reference,amount_minor,currency,customer_email,created_by_user_id) SELECT id,$1,$2,$3,'wsb:'||id::text,$4,$5,lower($6),$7 FROM generated RETURNING *`,[input.tenantId,input.planCode,input.provider,input.amountMinor,input.currency,input.customerEmail,input.createdByUserId]);return checkout(r.rows[0]);}catch(error){if((error as any)?.code==='23505')throw new SaasError('A billing checkout is already in progress','checkout_in_progress');throw error;}},
  async attachBillingProvider(id,input){const r=await pool.query(`UPDATE saas_billing_checkouts SET provider_subscription_id=$2,checkout_url=$3,status=$4,updated_at=now() WHERE id=$1 RETURNING *`,[id,input.providerSubscriptionId,input.checkoutUrl,input.status]);return checkout(r.rows[0]);},
  async failBillingCheckout(id,error){const r=await pool.query(`UPDATE saas_billing_checkouts SET status='FAILED',last_error=$2,updated_at=now() WHERE id=$1 RETURNING *`,[id,error.slice(0,500)]);return checkout(r.rows[0]);},
  async getBillingOverview(tenantId){const [c,i]=await Promise.all([pool.query(`SELECT * FROM saas_billing_checkouts WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 1`,[tenantId]),pool.query(`SELECT * FROM saas_billing_invoices WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 50`,[tenantId])]);return{checkout:c.rowCount?checkout(c.rows[0]):null,invoices:i.rows.map(invoice)};},
  async recordBillingEvent(provider,event:BillingProviderEvent,payload){const r=await pool.query(`INSERT INTO saas_billing_events(provider,event_id,event_name,provider_subscription_id,reference,raw_status,payload) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(provider,event_id) DO NOTHING RETURNING id`,[provider,event.eventId,event.eventName,event.providerSubscriptionId,event.reference,event.rawStatus,JSON.stringify(payload)]);return Boolean(r.rowCount);},
  async findBillingCheckout(provider,providerSubscriptionId,reference){if(!providerSubscriptionId&&!reference)return null;const r=await pool.query(`SELECT * FROM saas_billing_checkouts WHERE provider=$1 AND (($2::text IS NOT NULL AND provider_subscription_id=$2) OR ($3::text IS NOT NULL AND reference=$3)) ORDER BY (provider_subscription_id=$2) DESC,created_at DESC LIMIT 1`,[provider,providerSubscriptionId,reference]);return r.rowCount?checkout(r.rows[0]):null;},
  async updateBillingCheckout(id,status){const r=await pool.query(`UPDATE saas_billing_checkouts SET status=$2,last_error=null,updated_at=now() WHERE id=$1 RETURNING *`,[id,status]);return checkout(r.rows[0]);},
  async finishBillingEvent(provider,eventId,input){await pool.query(`UPDATE saas_billing_events SET tenant_id=$3,checkout_id=$4,outcome=$5,processed_at=now() WHERE provider=$1 AND event_id=$2`,[provider,eventId,input.tenantId,input.checkoutId,input.outcome]);},
  async setSubscription(tenantId,input){const r=await pool.query(`INSERT INTO tenant_subscriptions(tenant_id,plan_code,status,trial_ends_at,current_period_ends_at,cancel_at_period_end) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id) DO UPDATE SET plan_code=excluded.plan_code,status=excluded.status,trial_ends_at=excluded.trial_ends_at,current_period_ends_at=excluded.current_period_ends_at,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=now() RETURNING *`,[tenantId,input.planCode,input.status,input.trialEndsAt??null,input.currentPeriodEndsAt??null,input.cancelAtPeriodEnd??false]);return subscription(r.rows[0]);},
  async recordBillingInvoice(input){await pool.query(`INSERT INTO saas_billing_invoices(tenant_id,checkout_id,provider,provider_charge_id,amount_minor,currency,status,paid_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(provider,provider_charge_id) DO UPDATE SET status=excluded.status,paid_at=coalesce(excluded.paid_at,saas_billing_invoices.paid_at),updated_at=now()`,[input.tenantId,input.checkoutId,input.provider,input.providerChargeId,input.amountMinor,input.currency,input.status,input.paidAt]);},
  async getBillingSummary():Promise<BillingSummary>{const r=await pool.query(`SELECT coalesce(sum(CASE WHEN s.status='ACTIVE' THEN 1 ELSE 0 END),0)::int active,coalesce(sum(CASE WHEN s.status='PAST_DUE' THEN 1 ELSE 0 END),0)::int past_due,coalesce(sum(CASE WHEN s.status='ACTIVE' THEN p.monthly_price_minor ELSE 0 END),0)::bigint mrr,(SELECT coalesce(sum(amount_minor),0)::bigint FROM saas_billing_invoices WHERE status='PAID') paid,(SELECT count(*)::int FROM saas_billing_checkouts WHERE status IN('PENDING','ACTION_REQUIRED')) pending FROM tenant_subscriptions s JOIN saas_plans p ON p.code=s.plan_code`);const row=r.rows[0];return{currency:'MYR',activeSubscriptions:Number(row.active),pastDueSubscriptions:Number(row.past_due),monthlyRecurringRevenueMinor:Number(row.mrr),paidRevenueMinor:Number(row.paid),pendingCheckouts:Number(row.pending)};},
};}
