import type { Pool } from 'pg';
import { ServiceConflictError, type CreateCategoryInput, type CreateServiceInput, type Service, type ServiceCategory, type ServiceRepository, type ServiceSearch, type UpdateCategoryInput, type UpdateServiceInput } from '@wsadmin-business/services';
const mapCategory=(r:any):ServiceCategory=>({id:r.id,tenantId:r.tenant_id,name:r.name,sortOrder:r.sort_order,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at});
const mapService=(r:any):Service=>({id:r.id,tenantId:r.tenant_id,categoryId:r.category_id,name:r.name,description:r.description,durationMinutes:r.duration_minutes,bufferBeforeMinutes:r.buffer_before_minutes,bufferAfterMinutes:r.buffer_after_minutes,priceMinor:Number(r.price_minor),currency:r.currency,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
function translate(error:unknown):never{if(typeof error==='object'&&error&&'code' in error){const code=(error as any).code;if(code==='23505')throw new ServiceConflictError('name already exists for this tenant');if(code==='23503')throw new ServiceConflictError('category does not belong to tenant');}throw error;}
export function createServiceRepository(pool:Pool):ServiceRepository{return{
  async createCategory(t,i){try{const r=await pool.query('INSERT INTO service_categories(tenant_id,name,sort_order,active) VALUES($1,$2,$3,$4) RETURNING *',[t,i.name,i.sortOrder??0,i.active??true]);return mapCategory(r.rows[0]);}catch(e){return translate(e);}},
  async listCategories(t,inc=false){const r=await pool.query('SELECT * FROM service_categories WHERE tenant_id=$1 AND ($2::boolean OR active=true) ORDER BY sort_order,name',[t,inc]);return r.rows.map(mapCategory);},
  async updateCategory(t,id,i){const cur=await pool.query('SELECT * FROM service_categories WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];try{const r=await pool.query('UPDATE service_categories SET name=$3,sort_order=$4,active=$5,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *',[t,id,'name'in i?i.name:x.name,'sortOrder'in i?i.sortOrder:x.sort_order,'active'in i?i.active:x.active]);return mapCategory(r.rows[0]);}catch(e){return translate(e);}},
  async createService(t,i){try{const r=await pool.query(`INSERT INTO services(tenant_id,category_id,name,description,duration_minutes,buffer_before_minutes,buffer_after_minutes,price_minor,currency,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[t,i.categoryId??null,i.name,i.description??null,i.durationMinutes,i.bufferBeforeMinutes??0,i.bufferAfterMinutes??0,i.priceMinor??0,i.currency??'MYR',i.active??true,i.sortOrder??0]);return mapService(r.rows[0]);}catch(e){return translate(e);}},
  async getService(t,id){const r=await pool.query('SELECT * FROM services WHERE tenant_id=$1 AND id=$2',[t,id]);return r.rowCount?mapService(r.rows[0]):null;},
  async searchServices(t,q:ServiceSearch){const term=q.q?.trim()??'';const active=q.active;const r=await pool.query(`SELECT * FROM services WHERE tenant_id=$1 AND ($2::text IS NULL OR active=$2::boolean) AND ($3::uuid IS NULL OR category_id=$3::uuid) AND ($4='' OR name ILIKE '%'||$4||'%' OR coalesce(description,'') ILIKE '%'||$4||'%') ORDER BY sort_order,name LIMIT $5 OFFSET $6`,[t,active===undefined?null:active,q.categoryId??null,term,q.limit??50,q.offset??0]);return r.rows.map(mapService);},
  async updateService(t,id,i:UpdateServiceInput){const cur=await pool.query('SELECT * FROM services WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];try{const r=await pool.query(`UPDATE services SET category_id=$3,name=$4,description=$5,duration_minutes=$6,buffer_before_minutes=$7,buffer_after_minutes=$8,price_minor=$9,currency=$10,active=$11,sort_order=$12,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,'categoryId'in i?i.categoryId:x.category_id,'name'in i?i.name:x.name,'description'in i?i.description:x.description,'durationMinutes'in i?i.durationMinutes:x.duration_minutes,'bufferBeforeMinutes'in i?i.bufferBeforeMinutes:x.buffer_before_minutes,'bufferAfterMinutes'in i?i.bufferAfterMinutes:x.buffer_after_minutes,'priceMinor'in i?i.priceMinor:x.price_minor,'currency'in i?i.currency:x.currency,'active'in i?i.active:x.active,'sortOrder'in i?i.sortOrder:x.sort_order]);return mapService(r.rows[0]);}catch(e){return translate(e);}}
};}
