import type{Pool}from'pg';import{ServiceOptionValidationError,type ServiceOption,type ServiceOptionGroup,type ServiceOptionRepository}from'@wsadmin-business/services';
const group=(r:any):ServiceOptionGroup=>({id:r.id,tenantId:r.tenant_id,serviceId:r.service_id,name:r.name,selectionMode:r.selection_mode,required:r.required,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
const option=(r:any):ServiceOption=>({id:r.id,tenantId:r.tenant_id,groupId:r.group_id,name:r.name,durationDeltaMinutes:r.duration_delta_minutes,priceDeltaMinor:Number(r.price_delta_minor),requiredResourceType:r.required_resource_type,active:r.active,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
function translate(e:unknown):never{if(typeof e==='object'&&e&&'code'in e){const c=(e as any).code;if(c==='23505')throw new ServiceOptionValidationError('duplicate option group/option name');if(c==='23503'||c==='22P02')throw new ServiceOptionValidationError('service/group/resource type is invalid for tenant');}throw e;}
export function createServiceOptionRepository(pool:Pool):ServiceOptionRepository{return{
 async createGroup(t,s,i){try{const r=await pool.query(`INSERT INTO service_option_groups(tenant_id,service_id,name,selection_mode,required,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[t,s,i.name,i.selectionMode??'SINGLE',i.required??false,i.active??true,i.sortOrder??0]);return group(r.rows[0]);}catch(e){return translate(e);}},
 async listGroups(t,s,inc=false){const r=await pool.query('SELECT * FROM service_option_groups WHERE tenant_id=$1 AND service_id=$2 AND ($3::boolean OR active=true) ORDER BY sort_order,name',[t,s,inc]);return r.rows.map(group);},
 async createOption(t,g,i){try{const r=await pool.query(`INSERT INTO service_options(tenant_id,group_id,name,duration_delta_minutes,price_delta_minor,required_resource_type,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[t,g,i.name,i.durationDeltaMinutes??0,i.priceDeltaMinor??0,i.requiredResourceType??null,i.active??true,i.sortOrder??0]);return option(r.rows[0]);}catch(e){return translate(e);}},
 async updateOption(t,id,i){const cur=await pool.query('SELECT * FROM service_options WHERE tenant_id=$1 AND id=$2',[t,id]);if(!cur.rowCount)return null;const x=cur.rows[0];try{const r=await pool.query(`UPDATE service_options SET name=$3,duration_delta_minutes=$4,price_delta_minor=$5,required_resource_type=$6,active=$7,sort_order=$8,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[t,id,'name'in i?i.name:x.name,'durationDeltaMinutes'in i?i.durationDeltaMinutes:x.duration_delta_minutes,'priceDeltaMinor'in i?i.priceDeltaMinor:x.price_delta_minor,'requiredResourceType'in i?i.requiredResourceType:x.required_resource_type,'active'in i?i.active:x.active,'sortOrder'in i?i.sortOrder:x.sort_order]);return option(r.rows[0]);}catch(e){return translate(e);}},
 async listOptions(t,s,inc=false){const r=await pool.query(`SELECT o.* FROM service_options o JOIN service_option_groups g ON g.tenant_id=o.tenant_id AND g.id=o.group_id WHERE o.tenant_id=$1 AND g.service_id=$2 AND ($3::boolean OR (o.active=true AND g.active=true)) ORDER BY g.sort_order,o.sort_order,o.name`,[t,s,inc]);return r.rows.map(option);}
};}
