import type { Pool,PoolClient } from 'pg';
import type { ShiftOverride,StaffScheduleRepository,StaffTimeBlock,WeeklyHours } from '@wsadmin-business/staff';
const mapOverride=(r:any):ShiftOverride=>({id:r.id,tenantId:r.tenant_id,staffId:r.staff_id,localDate:String(r.local_date).slice(0,10),startMinute:r.start_minute,endMinute:r.end_minute,isOff:r.is_off,createdAt:r.created_at});
const mapBlock=(r:any):StaffTimeBlock=>({id:r.id,tenantId:r.tenant_id,staffId:r.staff_id,type:r.type,startsAt:r.starts_at,endsAt:r.ends_at,reason:r.reason,createdAt:r.created_at});
async function ensureStaff(client:Pool|PoolClient,t:string,s:string){const r=await client.query('SELECT 1 FROM staff_profiles WHERE tenant_id=$1 AND id=$2',[t,s]);if(!r.rowCount)throw new Error('staff_not_found');}
export function createStaffScheduleRepository(pool:Pool):StaffScheduleRepository{return{
  async setWeeklyHours(t,s,intervals){const c=await pool.connect();try{await c.query('BEGIN');await ensureStaff(c,t,s);await c.query('DELETE FROM staff_working_hours WHERE tenant_id=$1 AND staff_id=$2',[t,s]);for(const x of intervals)await c.query('INSERT INTO staff_working_hours(tenant_id,staff_id,weekday,start_minute,end_minute) VALUES($1,$2,$3,$4,$5)',[t,s,x.weekday,x.startMinute,x.endMinute]);await c.query('COMMIT');return intervals;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
  async getWeeklyHours(t,s){const r=await pool.query('SELECT weekday,start_minute,end_minute FROM staff_working_hours WHERE tenant_id=$1 AND staff_id=$2 ORDER BY weekday,start_minute',[t,s]);return r.rows.map((x:any):WeeklyHours=>({weekday:x.weekday,startMinute:x.start_minute,endMinute:x.end_minute}));},
  async addShiftOverride(t,s,i){await ensureStaff(pool,t,s);const r=await pool.query('INSERT INTO staff_shift_overrides(tenant_id,staff_id,local_date,start_minute,end_minute,is_off) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[t,s,i.localDate,i.startMinute,i.endMinute,i.isOff]);return mapOverride(r.rows[0]);},
  async listShiftOverrides(t,s,from,to){const r=await pool.query(`SELECT * FROM staff_shift_overrides WHERE tenant_id=$1 AND staff_id=$2 AND ($3::date IS NULL OR local_date >= $3::date) AND ($4::date IS NULL OR local_date <= $4::date) ORDER BY local_date,start_minute NULLS FIRST`,[t,s,from??null,to??null]);return r.rows.map(mapOverride);},
  async addTimeBlock(t,s,i){await ensureStaff(pool,t,s);const r=await pool.query('INSERT INTO staff_time_blocks(tenant_id,staff_id,type,starts_at,ends_at,reason) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[t,s,i.type,i.startsAt,i.endsAt,i.reason??null]);return mapBlock(r.rows[0]);},
  async listTimeBlocks(t,s,from,to){const r=await pool.query(`SELECT * FROM staff_time_blocks WHERE tenant_id=$1 AND staff_id=$2 AND ($3::timestamptz IS NULL OR ends_at >= $3) AND ($4::timestamptz IS NULL OR starts_at <= $4) ORDER BY starts_at`,[t,s,from??null,to??null]);return r.rows.map(mapBlock);}
};}
