import type{Pool}from'pg';import type{PublicTreatmentView,TreatmentAuditEvent,TreatmentShare,TreatmentSharingRepository}from'@wsadmin-business/treatments';
const share=(r:any):TreatmentShare=>({id:r.id,tenantId:r.tenant_id,treatmentRecordId:r.treatment_record_id,includeNotes:r.include_notes,expiresAt:r.expires_at,revokedAt:r.revoked_at,createdByUserId:r.created_by_user_id,createdAt:r.created_at,lastAccessedAt:r.last_accessed_at});const audit=(r:any):TreatmentAuditEvent=>({id:r.id,tenantId:r.tenant_id,treatmentRecordId:r.treatment_record_id,shareId:r.share_id,actorUserId:r.actor_user_id,eventType:r.event_type,detail:r.detail??{},occurredAt:r.occurred_at});
export function createTreatmentSharingRepository(pool:Pool):TreatmentSharingRepository{return{
 async createShare(t,r,i){const c=await pool.connect();try{await c.query('BEGIN');const exists=await c.query('SELECT 1 FROM treatment_records WHERE tenant_id=$1 AND id=$2',[t,r]);if(!exists.rowCount)throw new Error('treatment_not_found');const q=await c.query(`INSERT INTO treatment_share_links(tenant_id,treatment_record_id,token_hash,include_notes,expires_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[t,r,i.tokenHash,i.includeNotes,i.expiresAt,i.actorUserId]);const s=share(q.rows[0]);await c.query(`INSERT INTO treatment_audit_events(tenant_id,treatment_record_id,share_id,actor_user_id,event_type,detail) VALUES($1,$2,$3,$4,'SHARE_CREATED',$5::jsonb)`,[t,r,s.id,i.actorUserId,JSON.stringify({expiresAt:i.expiresAt,includeNotes:i.includeNotes})]);await c.query('COMMIT');return s;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async revokeShare(t,r,s,a){const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query(`UPDATE treatment_share_links SET revoked_at=coalesce(revoked_at,now()) WHERE tenant_id=$1 AND treatment_record_id=$2 AND id=$3 RETURNING *`,[t,r,s]);if(!q.rowCount){await c.query('ROLLBACK');return false;}await c.query(`INSERT INTO treatment_audit_events(tenant_id,treatment_record_id,share_id,actor_user_id,event_type) VALUES($1,$2,$3,$4,'SHARE_REVOKED')`,[t,r,s,a]);await c.query('COMMIT');return true;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async publicView(tokenHash,now){const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query(`SELECT sl.*,tr.id record_id,tr.occurred_at,tr.summary,tr.notes,tr.service_id FROM treatment_share_links sl JOIN treatment_records tr ON tr.tenant_id=sl.tenant_id AND tr.id=sl.treatment_record_id WHERE sl.token_hash=$1 AND sl.revoked_at IS NULL AND sl.expires_at>$2 FOR UPDATE OF sl`,[tokenHash,now]);if(!q.rowCount){await c.query('ROLLBACK');return null;}const x=q.rows[0];const m=await c.query(`SELECT media_kind,storage_ref,caption FROM treatment_media WHERE tenant_id=$1 AND treatment_record_id=$2 AND customer_visible=true ORDER BY created_at,id`,[x.tenant_id,x.record_id]);await c.query('UPDATE treatment_share_links SET last_accessed_at=$2 WHERE id=$1',[x.id,now]);await c.query(`INSERT INTO treatment_audit_events(tenant_id,treatment_record_id,share_id,event_type,detail,occurred_at) VALUES($1,$2,$3,'SHARE_VIEWED',$4::jsonb,$5)`,[x.tenant_id,x.record_id,x.id,JSON.stringify({public:true}),now]);await c.query('COMMIT');return{shareId:x.id,recordId:x.record_id,occurredAt:x.occurred_at,summary:x.summary,notes:x.include_notes?x.notes:null,serviceId:x.service_id,media:m.rows.map((z:any)=>({mediaKind:z.media_kind,storageRef:z.storage_ref,caption:z.caption}))} satisfies PublicTreatmentView;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async audit(t,r,l){const q=await pool.query('SELECT * FROM treatment_audit_events WHERE tenant_id=$1 AND treatment_record_id=$2 ORDER BY occurred_at DESC,id DESC LIMIT $3',[t,r,l]);return q.rows.map(audit);},
 async setMediaVisibility(t,r,m,v,a){const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('UPDATE treatment_media SET customer_visible=$4 WHERE tenant_id=$1 AND treatment_record_id=$2 AND id=$3 RETURNING id',[t,r,m,v]);if(!q.rowCount){await c.query('ROLLBACK');return false;}await c.query(`INSERT INTO treatment_audit_events(tenant_id,treatment_record_id,actor_user_id,event_type,detail) VALUES($1,$2,$3,'MEDIA_VISIBILITY_UPDATED',$4::jsonb)`,[t,r,a,JSON.stringify({mediaId:m,customerVisible:v})]);await c.query('COMMIT');return true;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
};}
