import type{Pool,PoolClient}from'pg';import type{CreateTreatmentInput,TreatmentMedia,TreatmentRecord,TreatmentRepository}from'@wsadmin-business/treatments';
const media=(r:any):TreatmentMedia=>({id:r.id,tenantId:r.tenant_id,treatmentRecordId:r.treatment_record_id,mediaKind:r.media_kind,storageRef:r.storage_ref,caption:r.caption,customerVisible:r.customer_visible,createdAt:r.created_at});
const record=(r:any):TreatmentRecord=>({id:r.id,tenantId:r.tenant_id,customerId:r.customer_id,bookingId:r.booking_id,staffId:r.staff_id,serviceId:r.service_id,occurredAt:r.occurred_at,summary:r.summary,notes:r.notes,status:r.status,createdByUserId:r.created_by_user_id,createdAt:r.created_at,updatedAt:r.updated_at,media:(r.media??[]).map((x:any)=>typeof x==='string'?JSON.parse(x):x).filter(Boolean).map((x:any)=>media({...x,tenant_id:r.tenant_id,treatment_record_id:r.id}))});
async function addMedia(c:PoolClient,t:string,id:string,m:any){const r=await c.query(`INSERT INTO treatment_media(tenant_id,treatment_record_id,media_kind,storage_ref,caption,customer_visible) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[t,id,m.mediaKind,m.storageRef,m.caption??null,m.customerVisible??false]);return media(r.rows[0]);}
async function createOne(c:PoolClient,t:string,i:CreateTreatmentInput&{occurredAt:Date;createdByUserId:string|null}){const r=await c.query(`INSERT INTO treatment_records(tenant_id,customer_id,booking_id,staff_id,service_id,occurred_at,summary,notes,status,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[t,i.customerId,i.bookingId??null,i.staffId??null,i.serviceId??null,i.occurredAt,i.summary,i.notes??null,i.status??'FINAL',i.createdByUserId]);const row=record({...r.rows[0],media:[]});for(const m of i.media??[])row.media.push(await addMedia(c,t,row.id,m));return row;}
export function createTreatmentRepository(pool:Pool):TreatmentRepository{return{
 async create(t,i){const c=await pool.connect();try{await c.query('BEGIN');const row=await createOne(c,t,i);await c.query('COMMIT');return row;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async get(t,id){const r=await pool.query(`SELECT tr.*,coalesce(jsonb_agg(to_jsonb(tm) ORDER BY tm.created_at,tm.id) FILTER(WHERE tm.id IS NOT NULL),'[]'::jsonb) media FROM treatment_records tr LEFT JOIN treatment_media tm ON tm.tenant_id=tr.tenant_id AND tm.treatment_record_id=tr.id WHERE tr.tenant_id=$1 AND tr.id=$2 GROUP BY tr.id`,[t,id]);return r.rowCount?record(r.rows[0]):null;},
 async listCustomer(t,cust,l,o){const r=await pool.query(`SELECT tr.*,coalesce(jsonb_agg(to_jsonb(tm) ORDER BY tm.created_at,tm.id) FILTER(WHERE tm.id IS NOT NULL),'[]'::jsonb) media FROM treatment_records tr LEFT JOIN treatment_media tm ON tm.tenant_id=tr.tenant_id AND tm.treatment_record_id=tr.id WHERE tr.tenant_id=$1 AND tr.customer_id=$2 GROUP BY tr.id ORDER BY tr.occurred_at DESC,tr.id DESC LIMIT $3 OFFSET $4`,[t,cust,l,o]);return r.rows.map(record);},
 async addMedia(t,id,i){const c=await pool.connect();try{await c.query('BEGIN');const exists=await c.query('SELECT 1 FROM treatment_records WHERE tenant_id=$1 AND id=$2',[t,id]);if(!exists.rowCount)throw new Error('treatment_not_found');const row=await addMedia(c,t,id,i);await c.query('COMMIT');return row;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}},
 async exportRows(t,cust){const r=await pool.query(`SELECT tr.*,coalesce(jsonb_agg(to_jsonb(tm) ORDER BY tm.created_at,tm.id) FILTER(WHERE tm.id IS NOT NULL),'[]'::jsonb) media FROM treatment_records tr LEFT JOIN treatment_media tm ON tm.tenant_id=tr.tenant_id AND tm.treatment_record_id=tr.id WHERE tr.tenant_id=$1 AND ($2::uuid IS NULL OR tr.customer_id=$2) GROUP BY tr.id ORDER BY tr.occurred_at,tr.id`,[t,cust??null]);return r.rows.map(record);},
 async importMany(t,rows){const c=await pool.connect();const out:TreatmentRecord[]=[];try{await c.query('BEGIN');for(const i of rows)out.push(await createOne(c,t,i));await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
};}
