import type{Pool}from'pg';import type{ManagementConversation,ManagementSession,UpcomingBooking,WhatsAppBookingManagementRepository}from'@wsadmin-business/whatsapp-booking';
function date(v:any){if(v===null||v===undefined)return null;if(typeof v==='string')return v.slice(0,10);if(v instanceof Date)return v.toISOString().slice(0,10);return String(v).slice(0,10);}
const sess=(r:any):ManagementSession=>({tenantId:r.tenant_id,conversationId:r.conversation_id,state:r.state,requestedAction:r.requested_action,bookingOptions:Array.isArray(r.booking_options)?r.booking_options:[],bookingId:r.booking_id,localDate:date(r.local_date),slotOptions:Array.isArray(r.slot_options)?r.slot_options:[],expiresAt:r.expires_at});
const booking=(r:any):UpcomingBooking=>({id:r.id,locationId:r.location_id,serviceId:r.service_id,serviceName:r.service_name,startsAt:r.starts_at,status:r.status,optionIds:Array.isArray(r.option_ids)?r.option_ids:[]});
export function createWhatsAppBookingManagementRepository(pool:Pool):WhatsAppBookingManagementRepository{return{
 async getConversation(t,id){const r=await pool.query('SELECT tenant_id,id,instance_id,customer_id,remote_jid,status FROM whatsapp_conversations WHERE tenant_id=$1 AND id=$2',[t,id]);if(!r.rowCount)return null;const x=r.rows[0];return{tenantId:x.tenant_id,conversationId:x.id,instanceId:x.instance_id,customerId:x.customer_id,remoteJid:x.remote_jid,status:x.status} as ManagementConversation;},
 async getSession(t,id){const r=await pool.query('SELECT * FROM whatsapp_booking_management_sessions WHERE tenant_id=$1 AND conversation_id=$2',[t,id]);return r.rowCount?sess(r.rows[0]):null;},
 async saveSession(s){const r=await pool.query(`INSERT INTO whatsapp_booking_management_sessions(tenant_id,conversation_id,state,requested_action,booking_options,booking_id,local_date,slot_options,expires_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8::jsonb,$9) ON CONFLICT(tenant_id,conversation_id) DO UPDATE SET state=excluded.state,requested_action=excluded.requested_action,booking_options=excluded.booking_options,booking_id=excluded.booking_id,local_date=excluded.local_date,slot_options=excluded.slot_options,expires_at=excluded.expires_at,updated_at=now() RETURNING *`,[s.tenantId,s.conversationId,s.state,s.requestedAction,JSON.stringify(s.bookingOptions),s.bookingId,s.localDate,JSON.stringify(s.slotOptions),s.expiresAt]);return sess(r.rows[0]);},
 async clearSession(t,id){await pool.query('DELETE FROM whatsapp_booking_management_sessions WHERE tenant_id=$1 AND conversation_id=$2',[t,id]);},
 async listUpcomingBookings(t,customerId){const r=await pool.query(`SELECT b.id,b.location_id,b.service_id,s.name AS service_name,b.starts_at,b.status,ARRAY(SELECT bso.option_id::text FROM booking_service_options bso WHERE bso.tenant_id=b.tenant_id AND bso.booking_id=b.id ORDER BY bso.option_id) AS option_ids FROM bookings b JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id WHERE b.tenant_id=$1 AND b.customer_id=$2 AND b.status IN ('PENDING','CONFIRMED') AND b.starts_at>=now()-interval '2 hours' ORDER BY b.starts_at,b.id LIMIT 20`,[t,customerId]);return r.rows.map(booking);},
 async getBooking(t,id){const r=await pool.query(`SELECT b.id,b.location_id,b.service_id,s.name AS service_name,b.starts_at,b.status,ARRAY(SELECT bso.option_id::text FROM booking_service_options bso WHERE bso.tenant_id=b.tenant_id AND bso.booking_id=b.id ORDER BY bso.option_id) AS option_ids FROM bookings b JOIN services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id WHERE b.tenant_id=$1 AND b.id=$2`,[t,id]);return r.rowCount?booking(r.rows[0]):null;},
 async getTimezone(t,locationId){if(locationId){const r=await pool.query('SELECT coalesce(l.timezone,t.default_timezone) AS timezone FROM locations l JOIN tenants t ON t.id=l.tenant_id WHERE l.tenant_id=$1 AND l.id=$2',[t,locationId]);if(r.rowCount)return r.rows[0].timezone;}const r=await pool.query('SELECT default_timezone FROM tenants WHERE id=$1',[t]);return r.rows[0]?.default_timezone??'Asia/Kuala_Lumpur';},
 async enqueueReply(i){const r=await pool.query(`INSERT INTO whatsapp_outbound_messages(tenant_id,instance_id,conversation_id,to_jid,text_content,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id`,[i.tenantId,i.instanceId,i.conversationId,i.toJid,i.text,i.idempotencyKey]);return{id:r.rows[0].id};}
};}
