import type{Pool}from'pg';import type{BookingFlowSession,FlowConversation,FlowLocation,FlowService,WhatsAppBookingFlowRepository}from'@wsadmin-business/whatsapp-booking';
function localDate(v:any):string|null{if(v===null||v===undefined)return null;if(typeof v==='string')return v.slice(0,10);if(v instanceof Date)return v.toISOString().slice(0,10);return String(v).slice(0,10);}
const session=(r:any):BookingFlowSession=>({tenantId:r.tenant_id,conversationId:r.conversation_id,state:r.state,locationId:r.location_id,serviceId:r.service_id,localDate:localDate(r.local_date),slotOptions:Array.isArray(r.slot_options)?r.slot_options:[],selectedStartsAt:r.selected_starts_at,expiresAt:r.expires_at});
export function createWhatsAppBookingFlowRepository(pool:Pool):WhatsAppBookingFlowRepository{return{
 async getConversation(t,id){const r=await pool.query('SELECT tenant_id,id,instance_id,customer_id,remote_jid,status FROM whatsapp_conversations WHERE tenant_id=$1 AND id=$2',[t,id]);if(!r.rowCount)return null;const x=r.rows[0];return{tenantId:x.tenant_id,conversationId:x.id,instanceId:x.instance_id,customerId:x.customer_id,remoteJid:x.remote_jid,status:x.status} as FlowConversation;},
 async getSession(t,id){const r=await pool.query('SELECT * FROM whatsapp_booking_sessions WHERE tenant_id=$1 AND conversation_id=$2',[t,id]);return r.rowCount?session(r.rows[0]):null;},
 async saveSession(s){const r=await pool.query(`INSERT INTO whatsapp_booking_sessions(tenant_id,conversation_id,state,location_id,service_id,local_date,slot_options,selected_starts_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) ON CONFLICT(tenant_id,conversation_id) DO UPDATE SET state=excluded.state,location_id=excluded.location_id,service_id=excluded.service_id,local_date=excluded.local_date,slot_options=excluded.slot_options,selected_starts_at=excluded.selected_starts_at,expires_at=excluded.expires_at,updated_at=now() RETURNING *`,[s.tenantId,s.conversationId,s.state,s.locationId,s.serviceId,s.localDate,JSON.stringify(s.slotOptions),s.selectedStartsAt,s.expiresAt]);return session(r.rows[0]);},
 async clearSession(t,id){await pool.query('DELETE FROM whatsapp_booking_sessions WHERE tenant_id=$1 AND conversation_id=$2',[t,id]);},
 async listLocations(t){const r=await pool.query('SELECT id,name FROM locations WHERE tenant_id=$1 AND active=true ORDER BY sort_order,name',[t]);return r.rows.map((x:any):FlowLocation=>({id:x.id,name:x.name}));},
 async listServices(t,locationId){const r=locationId?await pool.query(`SELECT s.id,s.name,s.price_minor,s.currency FROM services s JOIN service_locations sl ON sl.tenant_id=s.tenant_id AND sl.service_id=s.id WHERE s.tenant_id=$1 AND sl.location_id=$2 AND s.active=true ORDER BY s.sort_order,s.name`,[t,locationId]):await pool.query('SELECT id,name,price_minor,currency FROM services WHERE tenant_id=$1 AND active=true ORDER BY sort_order,name',[t]);return r.rows.map((x:any):FlowService=>({id:x.id,name:x.name,priceMinor:Number(x.price_minor),currency:x.currency}));},
 async getService(t,id){const r=await pool.query('SELECT id,name,price_minor,currency FROM services WHERE tenant_id=$1 AND id=$2 AND active=true',[t,id]);if(!r.rowCount)return null;const x=r.rows[0];return{id:x.id,name:x.name,priceMinor:Number(x.price_minor),currency:x.currency};},
 async getTimezone(t,locationId){if(locationId){const r=await pool.query('SELECT coalesce(l.timezone,t.default_timezone) AS timezone FROM locations l JOIN tenants t ON t.id=l.tenant_id WHERE l.tenant_id=$1 AND l.id=$2',[t,locationId]);if(r.rowCount)return r.rows[0].timezone;}const r=await pool.query('SELECT default_timezone FROM tenants WHERE id=$1',[t]);return r.rows[0]?.default_timezone??'Asia/Kuala_Lumpur';},
 async enqueueReply(i){const r=await pool.query(`INSERT INTO whatsapp_outbound_messages(tenant_id,instance_id,conversation_id,to_jid,text_content,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id`,[i.tenantId,i.instanceId,i.conversationId,i.toJid,i.text,i.idempotencyKey]);return{id:r.rows[0].id};}
};}
